### ISSUE TITLE
Taiga not finding folder despite detecting episode

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#100]
Title pretty much explains the whole of it. Taiga will detect that I have episodes of an anime, but asking it to open the folder will show the "Taiga couldn't find the folder of this anime. Would you like to set it manually?" prompt.

**Comment by erengy** [comment]
What are the names of the anime and the folder? When the folder name is not identical<sup>1</sup> to the anime title, Taiga doesn't set it automatically in order to avoid setting common folders as anime folders.

<sup>1</sup> Technically, it doesn't need to be identical, it just needs to match the main title or one of the synonyms in their normalized form.

**Comment by ConnorKrammer** [comment]
After updating to 1.2's new release version (I made this issue while running the beta) it's seems to work fine. I think you fixed it in the interim.
