### ISSUE TITLE
Recognition error in version 1.2 (maybe other versions as well)

### ISSUE THREAD

**Issue by avue** [erengy/taiga#103]
I found an error in the recognition engine. I have a file named "5 Centimeters Per Second - (Movie)" without the quotes. The name of the movie as Tiaga knows it is "Byousoku 5 Centimeter" but even after filling out the alternate title field with the name of the move as I have it on my computer,Tiaga was unable to recognize it. I then renamed the file on my system to match the name that is used in Tiaga and it still was unable to recognize it. Just thought you might like the heads up.

**Comment by rr-** [comment]
Just to clear the obvious: are you sure you placed the file in a folder that Taiga can discover?

**Comment by erengy** [comment]
This issue is actually not related to the anime title. On MAL, [Byousoku 5 Centimeter](http://myanimelist.net/anime/1689/) is listed as having 3 episodes. Since the file of yours doesn't have any episode number in it, Taiga eliminates this anime from the list of possible matches. You can confirm this by renaming the file to something like:

- `5 Centimeters Per Second - (Movie) - 1`
- `5 Centimeters Per Second - (Movie) - 1-3`

**Comment by avue** [comment]
I see, so I guess this is a non issue then. You can consider this solved.

**Comment by erengy** [comment]
Specifically, Taiga [allows](https://github.com/erengy/taiga/blob/63d101f2e59396a8d5e92b4f2bfa799c6fcd01a5/src/track/recognition.cpp#L273-L278) a filename to not have an episode number only when the matching anime has a single episode, or when it's a batch torrent release. I currently can't think of a way to make this work without breaking something else, but it's something worth looking into.

**Comment by avue** [comment]
I just normally named my movies like that and even thought the aforementioned movie is actually 3eps. I encoded them all into 1 file and named it like that. It's not a big deal at the end of the day. Nice job on the update though.
