### ISSUE TITLE
[Suggestion] Go to Now Playing when an episode is not recognized

### ISSUE THREAD

**Issue by DDD19** [erengy/taiga#104]
Hi, I'd like to have the option to go to Now Playing when the episode is or isn't recognized. Due to my use of fullscreen exclusive mode with mpc-hc/madvr I don't seem to see the notifications if I set it to notify me when an episode is not recognized because windows is in the middle of turning off aero at that point. Having the screen change to now playing (with all the suggestions) would work for alerting me that the anime was not detected (taiga on one monitor, mpc on another.)

Thank you for reading and thanks for your hard work on such an awesome program.

**Comment by vendethiel** [comment]
Where recognized is "parsed and in the anime DB"?

**Comment by erengy** [comment]
Hi there @DDD19. You basically want another option here, right?

![notrecognized](https://cloud.githubusercontent.com/assets/1078430/7252210/94e1de82-e83b-11e4-92c0-795636ed0d82.png)

I'm generally wary of adding new options, but given your case, this seems like a reasonable thing to do. I wonder if merging these options would be undesirable for some users.

@vendethiel Yes. I personally describe recognition to be made of two subprocesses: Parsing and identification. First, a filename is parsed with [Anitomy](https://github.com/erengy/anitomy), then the result is compared against a set of database entries in order to find a match.

**Comment by vendethiel** [comment]
If it doesn't alert on tv shows, then I'm all for it :-).

**Comment by rr-** [comment]
As long as you don't put your tv shows in anime folders, it won't.

**Comment by DDD19** [comment]
@erengy Exactly. I think keeping them seperate is fine, I may just enable it for when the episode isn't recognized, frankly I wouldn't mind having the program not change pages when the episode is recognized. Thanks!
