### ISSUE TITLE
Cannot identify episode beginning with a prefix like [horriblesubs] [anidl] etc

### ISSUE THREAD

**Issue by MooseZM** [erengy/taiga#1042]
As said in the title, taiga can't identify titles with prefixes in the beginning of the name. For example it'll identify "Neon Genesis Evangelion - 01 [BD 1080p 10bit]" just fine but "[AniDL] Neon Genesis Evangelion - 01 [BD 720p 10bit][Beatrice-Raws]" is impossibe to identify. The suggested tites never include the actual title and when i try the "help taiga identify" option it doesn't work even if i find the title i'm looking for. Is there some sort of option that i missed that helps with this?

**Comment by paulo27ms** [comment]
What player?

**Comment by MooseZM** [comment]
mpv

**Comment by erengy** [comment]
I really don't think the issue is due to group prefix.

Are you using a custom [window title](https://mpv.io/manual/master/#options-title) format in your `mpv.conf`? If so, try changing it to `${filename} - mpv` and see if it helps. Also try playing the same files with a different media player (e.g. VLC).
