### ISSUE TITLE
Taiga tries to access a non authorized folder

### ISSUE THREAD

**Issue by luizfernando788** [erengy/taiga#1047]
Hello! 

The program starts to try to access this folder (E:\Windows Apps\) every new sync partly because my achieves are in this disk (E:), but is inaccessible by any user even administrator and doing so the program enters in a loop of trying to enter this folder and get rejected (sad) using a lot of memory (if you leave it going can consume all memory available) and consuming about 20% to 30% of the processor (Ryzen 5 2500u), there is any way to tell the program to not try to enter this folder?
[Taiga.log](https://github.com/erengy/taiga/files/7937367/Taiga.log)

**Comment by FreezyLemon** [comment]
As far as I know, there is no way to exclude folders from being scanned.
I think the easiest way to solve this would be to create a folder for your anime files (E:\Anime, for example) and then set this as your library folder in Taiga, instead of E:

**Comment by luizfernando788** [comment]
Yea, i done that (downloads and animes) but its continues to try to access, yesterday i removed completely taiga, removed the folder inside the appdata and reinstall and until now it stops to access but need to remove everyting about taiga to that to work, thanks for the response

**Comment by erengy** [comment]
Ideally, you shouldn't have anything other than anime videos in your library folders. If you added `E:` as a library folder, Taiga will try scanning all subfolders, including `E:\WindowsApps\`.

If you don't actually need the WindowsApps folder to be there, you can go to *System > Storage > Where new content is saved* from Windows settings and select a different drive. You can also move your videos to a folder such as `E:\Anime\` and add that as a library folder instead of just `E:\`, as you've already done.

This could eventually be solved with #887.
