### ISSUE TITLE
AniList website using Cloudflare DDoS protection page fails connection to API

### ISSUE THREAD

**Issue by snickler** [erengy/taiga#1089]
It seems that AniList is now using the Cloudflare DDoS protection that makes you wait for a few seconds before redirecting via JavaScript. This means currently AniList integration is broken at the moment.   

![image](https://user-images.githubusercontent.com/4016293/200031328-99340249-c9f0-4d77-8489-4e6490d260fd.png)

![image](https://user-images.githubusercontent.com/4016293/200031528-40b9d5c3-3dd1-4e91-a135-3bfbbf3ab678.png)

![image](https://user-images.githubusercontent.com/4016293/200031714-047d9896-3700-48ed-875b-75e01957153d.png)

**Comment by erengy** [comment]
This happened before at least once for AniList (#935), but it's more common with torrent feeds (e.g. #236, #326, #845). Bypassing the protection is neither feasible nor ethical, in my opinion. AniList should exclude their API from DDoS protection instead, if it's not a target. So it should be their call.

Taiga does [display](https://github.com/erengy/taiga/blob/1eb4f98c0ed9a63b9210e30523d4c27e8450f405/src/track/feed_aggregator.cpp#L54-L73) a more meaningful `"Cannot connect to {host} because of DDoS protection (Server: {server})"` error for torrent feeds though, so maybe we can use that for AniList too.
