### ISSUE TITLE
Twitter ending free access to its API

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#1112]
Source: https://twitter.com/TwitterDev/status/1621026986784337922

> Starting February 9, we will no longer support free access to the Twitter API, both v2 and v1.1. A paid basic tier will be available instead (...) We’ll be back with more details on what you can expect next week.

Taiga [uses](https://github.com/erengy/taiga/blob/master/src/link/twitter.cpp) the standard [v1.1 API](https://developer.twitter.com/en/docs/twitter-api/v1) for being able to post tweets, which may stop working if Twitter goes through with this decision.

**Comment by niihari** [comment]
On Thursday afternoon, [Musk claimed](https://twitter.com/elonmusk/status/1621259936524300289) that the free API “being abused badly” by “bot scammers” and “opinion manipulators.” He believes that “Just ~$100/month for API access with ID verification will clean things up greatly,” but we’ll have to wait and see if that pans out once free access goes away.

**Comment by erengy** [comment]
Update: https://twitter.com/TwitterDev/status/1641222783601631233

> Introducing a new form of Free (v2) access for write-only use cases and those testing the Twitter API with 1,500 Tweets/month at the app level, media upload endpoints, and Login with Twitter.

More from [Twitter Developer Platform](https://developer.twitter.com/):

> For write-only use cases and testing the Twitter API
> 
> - Rate limited access to v2 tweet posting and media upload endpoints 
> - 1,500 Tweets per month - posting limit at the app level
> - 1 app ID
> - Login with Twitter 
> - Cost: Free

Doesn't seem like the new free tier would suffice for Taiga's use case. 1,500 Tweets/month would cover no more than one or two dozen active users who prefer posting about every episode they watch.

I wonder if we could make this work by requiring users to enter their own API keys.

**Comment by erengy** [comment]
Someone just [reported](https://twitter.com/borjapertega/status/1659946778320424960) that Taiga's Twitter sharing feature was working fine until today.

@Diablofan Taiga's Twitter app was registered at your developer account, right? Could you check if it's still active? If so, what's the monthly tweet cap usage like?

**Comment by pruebark9** [comment]
It was working without any problem but I changed my PC and when I installed Taiga again, it does not let me link my Twitter account. Have you not planned for everyone to generate their own token and enter it into the program so that they can tweet?

**Comment by Diablofan** [comment]
> @Diablofan Taiga's Twitter app was registered at your developer account, right? Could you check if it's still active? If so, what's the monthly tweet cap usage like?

I believe that Twitter is revoking API keys for accounts that have not agreed to the new API terms to force people into agreeing to the new API terms. Unfortunately, I did not receive such an email, assuming they sent one, as I put them on their own account since I didn't feel comfortable attaching it to my personal twitter accounts. However, I have completely lost what the account credentials were since I (completely stupidly I might add) never wrote them down somewhere.

> Doesn't seem like the new free tier would suffice for Taiga's use case. 1,500 Tweets/month would cover no more than one or two dozen active users who prefer posting about every episode they watch.
> 
> I wonder if we could make this work by requiring users to enter their own API keys.

In that case we'd have to make every user provide their own key and secret since they are generated on a per-app basis. Which would involve creating a developer account, registering an app on twitter, and then putting the oauth keys into the app. 

That is all assuming anyone *still can do that*, since Twitter is trying to actively deprecate and remove the Twitter v1 API and force everyone on v2 API. Plus, according to my research on the v2 API, while our basic case of "posting a tweet" is implemented just fine, authentication in an out-of-band way like we are today with pin based authentication, doesn't seem to be supported. So, there would have to be significant leg work done in order to get Twitter integration working again.

---

At this point I see four ways forward:

1. Remove Twitter Support
2. Keep Twitter Support and use the Free Tier
3. Keep Twitter Support and Pay Up for Basic Tier
4. Keep Twitter Support, and make each user plug in an oauth key and secret and store that in the config.

With options 2, 3 and 4, we theoretically can get Twitter integration working again. This would require significant leg work though including the introduction of a web view in the app so we can perform oauth2 logins since oauth1 out-of-band authentication isn't supported on the v2 API according to my research. 

Option 2 and 3 means we get mostly the same experience we have today for logging into twitter, user clicks a button, performs a login and auth on twitter, and they're good to go.

Option 4 would require the user to:
1. Create a Twitter Developer Account
2. Create a Project and Application
3. Plugin the oauth key and secret into taiga
4. Perform login as usual
Then we don't have to worry about the rate limit as much as that will be tied to the individual user at that point.

Personally, I believe we should go with option 1. Yes, removing a feature sucks, but with the way twitter is being managed, plus the cost of time and (potentially) money, actually making the feature work and useful again is at least in my eye a bit high.

**Comment by erengy** [comment]
Thanks, @Diablofan. Posting limit of the Free tier isn't enough, and paying $100/month for the Basic tier is out of the question. So it's either option 1 or option 4 for Taiga, I think.

I just registered a new app from the Developer Portal (though I wasn't able to name it "Taiga" because it already exists). Attempting to post a tweet with the new keys resulted in `403 Forbidden` error with the following explanation:

> Could not update Twitter status. (You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product)

From what I gather, API v1 is pretty much dead. Fixing the integration requires migrating to API v2 and a new authentication flow. And people would still need to register their own apps for things to work. This doesn't seem feasible to me at the moment, so unless someone has another suggestion, I'm planning to remove Twitter support from Taiga in the next release.

**Comment by adrclavijo** [comment]
Maybe it's not the right place to suggest it, but maybe if Ttwitter support is being dropped it could be a cool idea to replace it with [Mastodon](https://docs.joinmastodon.org/client/intro/) support, since many twitter users are migrating there.
