### ISSUE TITLE
Lingering Window Frame

### ISSUE THREAD

**Issue by tucculent** [erengy/taiga#1128]
Sometimes when I close taiga the window frame stays on my screen and stays there until I restart my system.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/91495483/233948437-fd27af48-088e-43df-ab8a-913c93fb7f94.png">
When I attempt to reopen taiga after this occurs it opens a new window and the bugged out window frame stays.
<img width="921" alt="image" src="https://user-images.githubusercontent.com/91495483/233948771-469b9684-61e1-4874-b558-e706ff44fba9.png">
I cannot move or close the window frame and looking for it in task manager doesn't seem to work.

**Comment by erengy** [comment]
That's pretty weird. I'd have said Taiga isn't shutting down properly, but that's unlikely if Taiga doesn't appear in Task Manager while the frame is still there.

For starters, you can try restarting Windows Explorer from Task Manager (rather than completely restarting your system) to see if it gets rid of the empty frame.

**Comment by tucculent** [comment]
It finally happened again and restarting Windows Explorer didn't touch it at all. My thoughts are maybe this is a windows bug but it's still weird that this app is the only one doing this. Either way sorry for bothering you if this actually isn't something you can fix.
<img width="1124" alt="image" src="https://github.com/erengy/taiga/assets/91495483/317b2ec9-122c-4eeb-bdc0-f541d30b65ff">

**Comment by erengy** [comment]
Maybe it's both a Windows bug and also related to something Taiga does differently than other apps. But yeah, I can't really fix it without figuring out what that something is.

In any case, I'm currently rewriting the entire UI code for v2 in a different framework, so that might just get rid of the issue.

**Comment by tucculent** [comment]
I'll let you know if the bug ever happens once you release it then. If not, you'll never hear from me again.

**Comment by tucculent** [comment]
Came back to say it hasn't appeared again ever since I removed my video driver and reinstalled because I was also having video problems with some games and a black flicker in visual novels. Will probably never happen again and with other people.
