### ISSUE TITLE
Jojo's Bizarre Adventure : SC torrent not being automatically checked

### ISSUE THREAD

**Issue by Koroeskohr** [erengy/taiga#113]
It has happened before but I can honestly not remember if that happened every time. Basically, JBA:SC torrents are not automatically checked even though I double checked my filters. Filters that should apply are :
- Fansub for JBA:SC : HorribleSubs
- Prefer high-res files
- Select currently watching

It also didn't warn me when the episode was available, even though that's probably the same issue.

Might be a problem with it being second season and episode count (#58)

**Comment by erengy** [comment]
Are the relevant torrents correctly identified by Taiga? Can you see the blue/green status markers beside them (i.e. the little squares next to checkboxes), or are they colored in gray?

**Comment by Koroeskohr** [comment]
Yeah there's correctly identified, they just weren't checked and didnt warn me

There you go : VEFJAAUAMS4yLjBkDXic1ZbbbtNAEIav6VMMliquorbpGTWV0hpoC0EFV6EIoWjincSrrHfNHhKFJ+AZeDyehLXTpG1C3FOKlCtLe/j3/2Zm13PALaWAseVK1gJDgmIbQIo2TmoBymEAKhvNMeqgE36SJLYFsVpgtaMAJKZUC6JiJ8ROa5JWDGGQS3DZDQ5XXhzESjKey4BflvoFtcAZ0i1j0TqTn0EardK1gH44FH6kj8J52Y0A1g5XDtZyl/57yyzjJkbN/u024YzmWA1H+wAlA0a5Wh8tgVS2wmVFcGP9FE/pac7XH+u8PM5j80V4aQSBfeQiXwuUcaMYmXnWr+Zb0qVt0jfdC5o4X73SXi0I/qkjVIyiNVabnF8SjouC4bERGSdpTlDONXVIQ8K7SUWTUcIVdjtc3B2Kvi8U1bredZPBl8QUxm51PXvexLaRQeEJejQcKM3uSWCH2a34+w0Wuby2Xm+ezk/oA7XC0+blwsQ+fFqY1OdG82hhYlG4MKkvjebCtC6bp2FJCWbFXbiuQCHKKrDji3tSgt/eojSu/R3qZc/f2G5XK5eV3PgTpTX3p0Sube6Gv0vtWKUpL3tBHsZ98+ZNsENCm8A5amQj+uI3ANyvr+5Vq5tPp5iJybOxXKjeUMG7RDkBf379rk/z7O7t7y8Tzwlv8x69hDcuS5TkLp0B2t9bKqCP2PUO4Kvr8UqcoPT9B0Q+XSbh1rhpup3N7Y1lontPvR5yiEgaktMwW1ubS5WqM3WmXhk44j/Rd7dQZ31v1Gl6DZH1v2znG8Zj7Yx/NbSBqm/IIkKjZrB31re3lwk7dLJL3qLk+cvIYaCgoaxKSbu8WAcIDfQtvi9jS9yPheitQw9nns6N6v+r3ZkO7P7g4w6MaZVlxJ7W/m/d8vgXDUKbwg==

**Comment by erengy** [comment]
I think your filters are fine; it's because your progress on JoJo is wrong. Your anime list says that you recently watched the 40th episode, which is actually the 16th episode of the 2nd Season. After you fix your progress, your filters will select the 17th episode.

**Comment by Koroeskohr** [comment]
Why is it a normal behaviour ? Shouldn't it still warn you even though you're not up to date ?

**Comment by Zarggg** [comment]
Some sub groups number episodes of sequel seasons as if they were a continuation of the original season, even though it is a different "series" from the perspective of production.

It is "normal" behavior because the application (and tracking site) expect the episode number and series to be different from the one you are currently using, and therefore "incorrect."

**Comment by erengy** [comment]
Thanks for the explanation, @Zarggg. I'd like to add that even if you were not using Taiga, your progress would be incorrect. If the entry on MAL had an episode count of 26 for instance, your progress would be "40 out of 26", which doesn't make sense. Still, it's partially Taiga's fault, because it didn't handle these situations well prior to v1.2.

If you're asking why the torrent itself is discarded, that's because of your "Discard watched and available episodes" filter. Since `17` is less than `40`, the torrent is discarded (i.e. it's not automatically checked and you're not notified).
