### ISSUE TITLE
Update Failed, Reason: HTTP error #35: SSL Connect Error

### ISSUE THREAD

**Issue by MrSleepyguy** [erengy/taiga#114]
I got this pop up today and it comes up every 5-10 minutes while I'm watching anime, I'm not sure how to respond to this as it hasn't done it before

popup window of the message -
![2015-05-04_17-01-00](https://cloud.githubusercontent.com/assets/12236989/7456325/ed48d3da-f283-11e4-84fd-abb8e320d0bc.png)

Log File - https://db.tt/6RatqXad

**Comment by rr-** [comment]
Seems like it's either a problem with your Internet connection, or (more unlikely) a problem with cURL library.

**Comment by MrSleepyguy** [comment]
Well my internet dropped earlier, but I've restarted my pc and internet but it continued the message

**Comment by Woozie321** [comment]
It actually happened for me for a few times. Are you using Hummingbird?

**Comment by MrSleepyguy** [comment]
Yes, I'm using Hummingbird as well

**Comment by erengy** [comment]
Thanks for sharing the log file, @MrSleepyguy. It didn't help as far as this issue is concerned, but I realized that a lot of unnecessary errors are being logged when season data is loaded for the first time. Will get rid of them in the next release.

Considering that the previous SSL issues (#44 and #63) got resolved by itself, I'm inclined to believe that it's a problem on your end or on Hummingbird's server. You can try running Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) for additional information.

**Comment by MrSleepyguy** [comment]
The problem stopped occurring after I had finished the anime I was watching, it was the only anime that it did it with and haven't had the problem since. Thanks for the help though, it was most likely communication problems with the server.
