### ISSUE TITLE
Taiga blocked from anidex.info due to ddos-guard

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#1150]
![image](https://github.com/erengy/taiga/assets/2414202/9dc98a09-0c97-48fc-8edb-d47e301e8d5c)

I've been unable to automatically download torrents from Anidex.info, I'm assuming because of some new layer of protection.

**Comment by erengy** [comment]
See #845 for previous discussion.

DDoS-Guard (and Cloudflare, in other cases) basically adds a layer upon the service that requires solving a JavaScript challenge to make the actual HTTP connection. This is, by design, meant to be solved by web browsers only. Which is why Taiga cannot reach the RSS feed and displays an error instead.

Note that the protection is not blocking Taiga specifically. Visiting anidex.info from a web browser will show you this too:

![image](https://github.com/erengy/taiga/assets/1078430/07e2e078-a8ea-4497-a12e-11d15a702e6b)

**Comment by Statharas** [comment]
Seeing as how an RSS feed is meant for external consumption, does this mean this was not intended by anidex?

**Comment by erengy** [comment]
That may or may not be the case. You can ask them if it's possible to exclude the feed from DDoS protection.  But then whoever is attacking the website may just use the feed URL, which defeats the purpose of having protection.
