### ISSUE TITLE
Taiga doesnt re-download relations if they get deleted.

### ISSUE THREAD

**Issue by SacredZenpie** [erengy/taiga#1151]
Played with anime relations today, noticed that if the file gets deleted it doesn't re-download it.

Is this intended or is this a bug?

**Comment by erengy** [comment]
Taiga reads `anime-relations.txt` once per session, when recognition engine is initialized. So if you deleted the file while Taiga is running, it will realize the file is missing after a restart and then download the latest file next time you check for updates.

Note that the recognition engine is not automatically initialized at startup. You need to trigger it by watching a video, scanning available episodes, checking new torrents, etc.

**Comment by SacredZenpie** [comment]
Oh that's how it works, interesting. Is there a reason why taiga doesnt download anime-relation on startup if the file isnt present?

Also 1 more thing Ive been meaning to ask, is there a reason why the scan on startup is not ScanAvailableEpisodes? Asking because the ScanAvailableEpisodesQuick doesnt detect properly sometimes.

**Comment by erengy** [comment]
Initialization of the recognition engine (which includes reading anime relations) is delayed until it's needed to avoid extending startup time. Also, there's usually no reason for `anime-relations.txt` to be missing.

As the name implies, `ScanAvailableEpisodesQuick` is faster than `ScanAvailableEpisodes`. The former scans individual anime folders (e.g. `C:\Anime\Toradora\`), while the latter scans library folders (e.g. `C:\Anime\`). The reason is the same as above, though this might change in future releases (see #305 and #371).

**Comment by SacredZenpie** [comment]
Thank you for the explanations

**Comment by SacredZenpie** [comment]
Forgot to mention that I didn't notice any significant difference startup diff in my modified taiga between the 2 scans.

**Comment by erengy** [comment]
I haven't tested it lately, but it did make a difference for me at the time. Not everyone has SSDs, some people use network drives, some of them have hundreds of thousands of extra files in their library folders... So, it depends on the user's setup. Also note that the same scan can be slower or faster depending on when it's executed (e.g. it can be slower right after you boot up your computer, but faster later on because the OS has the necessary data cached in memory).

**Comment by baulaergrungim** [comment]
> Taiga reads `anime-relations.txt` once per session, when recognition engine is initialized. So if you deleted the file while Taiga is running, it will realize the file is missing after a restart and then download the latest file next time you check for updates.

In my case, relations weren't updated since sometime last year. I refreshed them by hand last night. It now recognizes "mahoutsukai no yome s2 pt 2", but for some reason stopped recognizing pt 1 files, asking what it is, and giving good results, but the next time I play the ep, it can't recognize it again.

**Comment by erengy** [comment]
> In my case, relations weren't updated since sometime last year. I refreshed them by hand last night.

If you have the *Settings → Application → General → Startup → Check for application updates* option disabled, Taiga won't automatically update anime relations either. In that case, you need to do that manually via *Help → Check for updates*.

> It now recognizes "mahoutsukai no yome s2 pt 2", but for some reason stopped recognizing pt 1 files, asking what it is, and giving good results, but the next time I play the ep, it can't recognize it again.

Could you give an example filename that is not being recognized?

**Comment by soredake** [comment]
> In my case, relations weren't updated since sometime last year.

I have the same problem, year without relations updates, checking for updates manually is not updating relations either.

**Comment by erengy** [comment]
If you have `Failure when receiving data from the peer` errors in your `Taiga\Taiga.log`, it's probably because of the bug that was fixed in b6f440e48b2827dd9b0c680861cf6c498748c306. In that case, using the [latest build](https://taiga.moe/latest.html) should fix the issue (or you can wait for v1.4.1).

**Comment by soredake** [comment]
@erengy thank you! Latest build fixes this problem, will wait for the new version.
