### ISSUE TITLE
Episodes missing

### ISSUE THREAD

**Issue by Geniusssmit** [erengy/taiga#1154]
something breaks some episodes recognition, looks like ".""one symbol""." after the episode number

![image](https://github.com/erengy/taiga/assets/24941285/af329d5f-6133-4bc0-83de-52d7aff8c768)
![2023_10_12_02_56_28_214_oBMJz89Lsn](https://github.com/erengy/taiga/assets/24941285/fe357e52-34dc-413d-b1c4-71b5bd47faea)

**Comment by erengy** [comment]
Previously mentioned at https://github.com/erengy/taiga/issues/752#issuecomment-508516943. This is due to Anitomy [avoiding](https://github.com/erengy/anitomy/blob/a4fa0a5604e988f6a4802a81c2d2649f98f99d93/anitomy/tokenizer.cpp#L206-L227) single-character tokens (e.g. `I` in episode 5, `A` in episode 7 and 13). Unfortunately, there's no easy fix without breaking other cases.

**Comment by erengy** [comment]
Anitomy's development branch is now able to parse these correctly. Will be available in v2.

```
>anitomy "The.Eminence.in.Shadow.S01E05.I.Am....1080p.BluRay.DD2.0.x265-ExCaLiBuR.mkv"
┌───────────────────────────────────────────┐
│ Element          │ Value                  │
│───────────────────────────────────────────│
│ title            │ The Eminence in Shadow │
│ season           │ 01                     │
│ episode          │ 05                     │
│ episode_title    │ I Am                   │
│ video_resolution │ 1080p                  │
│ source           │ BluRay                 │
│ video_term       │ x265                   │
│ file_extension   │ mkv                    │
└───────────────────────────────────────────┘
```
