### ISSUE TITLE
Unknown Error (200)

### ISSUE THREAD

**Issue by TwelveNights** [erengy/taiga#116]
My Taiga's status bar shows Unknown Error (200) every time I try to synchronize to MAL, while being unable to sync to it to update my local list with my MAL account.

**Comment by erengy** [comment]
It seems there's a common issue with MAL applications right now, possibly due to a recent change on MAL servers. I'm looking into it now, but could not reproduce the error so far. Could you run Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) (mind the warning) and try to sync again? `Taiga.log` should then contain all HTTP requests and responses, which I can examine.

**Comment by TwelveNights** [comment]
It seemed to have resolved itself overnight, miraculously. I'll post the log if it occurs again.
