### ISSUE TITLE
Remove MALgraph from external links

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#117]
Since [MALgraph](http://mal.oko.im) is going to shut down on June 1st, 2015, I'm planning to remove its URL from Taiga's [default external links](https://github.com/erengy/taiga/blob/812097150fb63037e0f3848ac0541964c89cef17/src/taiga/settings.cpp#L49-L54) list.

An alternative would be to change the link to [graph.anime.sc](http://graph.anime.sc). However, I'm a bit put off by the fact that the website doesn't mention the original developers (even [the fork](https://github.com/animesc/graph) is not a fork; the history just isn't there). May I ask why this is the case, @gineika?

I'd like to hear other people's opinions on this as well. Speaking of external links, let me know if you have any other URLs in mind that can be added to the default list.

@rr- @tehoko In case you missed it on the forums before: https://i.imgur.com/aNeAMSS.png

**Comment by vendethiel** [comment]
Aw :(. Is the original code somewhere? (except for that fork)

**Comment by erengy** [comment]
Yes, it's still available at [rr-/malgraph4](https://github.com/rr-/malgraph4).

**Comment by tehoko** [comment]
@erengy we didn't miss it, I even had it on my phone wallpaper for a while. :) Thanks!

I'm all for removing it, since the original URL serves no purpose anymore.
As for replacing it with graph.anime.sc, do as you wish. It's true that repository looks like it had been created manually instead of being properly forked, and all the commits are titled "Update", which is kinda weird. I noticed the author has just put a link to the original repo on their readme.md, which, in turn, is nice.

One thing that needs to be noted is that MAL admins said they consider adding some MALgraph's features in the future, so having a separate page might be redundant soon. Time will tell how it turns out, so right now it's your call what to do.

> I wonder why the development has been stopped (and the site removed)?

You can read the announcement here: http://myanimelist.net/forum/?topicid=1373476. In short: it became too difficult to maintain in the long run.

**Comment by vendethiel** [comment]
> One thing that needs to be noted is that MAL admins said they consider adding some MALgraph's features in the future, so having a separate page might be redundant soon. Time will tell how it turns out, so right now it's your call what to do.

Have they said anything about an API? :)

> You can read the announcement here: http://myanimelist.net/forum/?topicid=1373476. In short: it became too difficult to maintain in the long run.

I see. I wondered if it was because of the code or because of the servers, but I guess it's both. Hope you'll come up with more cool projects then (with all the new technical experience ~~grinded~~ earned)

**Comment by tehoko** [comment]
> Have they said anything about an API? :)

There was some API-related discussion about two years ago, but I don't think any of the suggestions posted by multiple developers were implemented yet. MAL went through some major changes recently, and now they're slowly catching up the missed time, with a new development team and organization - so there's hope things will change soon.

**Comment by vendethiel** [comment]
That's amazing to hear :-). I hope the behemoth can lose some weight (yay for yak-shaving)

**Comment by rr-** [comment]
Regarding the image - I don't have my way with words like @tehoko so instead I'll just post this:

![bear](https://cloud.githubusercontent.com/assets/1045476/7592040/868a1b78-f8d1-11e4-88b2-948809ddcc9f.jpg)

**Comment by tehoko** [comment]
You might want to change the link again, as they seem to have moved to a new domain.

**Comment by erengy** [comment]
Oh. Thanks.
