### ISSUE TITLE
MAL: Unknown error (403 Forbiden)

### ISSUE THREAD

**Issue by randi-raharja** [erengy/taiga#1174]
When I try to sync or do anything with MAL, MAL seems to be returning an HTTP 403 Forbidden error,When I try to sync or do anything with MAL, MAL seems to be returning an HTTP 403 Forbidden error. What's can i do ?
![image](https://github.com/erengy/taiga/assets/57124040/24b56f22-82ab-4c6f-9b63-503be5e9da5a)
![image](https://github.com/erengy/taiga/assets/57124040/52c0374a-b44d-4c47-b3ce-ea43f39ef0a9)

**Comment by erengy** [comment]
`403 Forbidden` is a generic HTTP status code that roughly means the server (MyAnimeList) is refusing to authorize your request. If it's because of incorrect credentials, re-authorizing from *Settings → Services → MyAnimeList* should resolve the issue. Otherwise it could be because your account or IP address is banned (see #481 for a previous issue).

**Comment by shaggyze** [comment]
MAL was having issues with its API server, https://myanimelist.net/forum/?topicid=2143705
