### ISSUE TITLE
Seasons Tab does not render (On linux, wine)

### ISSUE THREAD

**Issue by wolfsilver00** [erengy/taiga#1201]
Hi hi, been trying to work this out for a couple days.. Ive tried everything but can´t get it to work. 
Tried with bottles, lutris, steam.. Nothing works, the Seasons tab doesnt render. (Neither does the little pop up when you hover on an item on the animelist, the one showing details on episodes watched)

![image](https://github.com/user-attachments/assets/683bb3d2-b7c6-4edc-a65d-86564cd03f0d)

As you can see, previous tabs ghost the seasons one with its columns. 

Any idea what may be happening? I think there may be a dependency (ive installed all the usual ones) or some way this tab is rendered, that is different to the others.. 

I know there is no official support for linux but I can run almost any game on wine no problem, so there has to be a way to make this work.

OS data:

![image](https://github.com/user-attachments/assets/72ceb09d-d130-45f4-b66f-63d5c3bde83b)

**Comment by ghost** [comment]
I can confirm that this happens also on Zorin. As for solution itself, I don't think there is any, because like you said Linux is not officially supported. And btw, just because you can run almost any game does not mean you can run almost any program on Linux. Programs have very different dependecies compared to games.
But you could try using Bottles again and installing all Visual Studio 22 and C++ related options. And try using Caffe or Proton GE for the runner. I have not tested if this works, but that's frankly only method I can think of, I highly doubt it will work. Easiest solution would be running a small VM with Windows on it obviously.

I'll try fiddling with it and post again if I figure it out.

**Comment by wolfsilver00** [comment]
I did try with a bottle with, well, all conceivable requirements and every
runner possible, still no dice

**Comment by erengy** [comment]
This is likely the same issue mentioned at #790. Seasons page uses the [`LV_VIEW_TILE`](https://learn.microsoft.com/en-us/windows/win32/controls/list-view-controls-overview#list-view-styles-and-views) mode of the list-view control and custom-draws the items by handling the `NM_CUSTOMDRAW` message, which is apparently not supported on Wine.

This won't be an issue in v2, since it uses Qt and is going to run natively on Linux.

**Comment by wolfsilver00** [comment]
OOh that makes a lot of sense, good news about v2 going for Qt. 
Thanks!
