### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by wplanetary** [erengy/taiga#121]
First wanted you to know that you did an awesome job with Taiga. It's so practical, I only need to boot Taiga when I want to watch anime, it notifies me of new releases and practically download these for me, and helps me keep track of what I have watched and what I haven't. I wished there was that for non-Japanese series and movies, to be honest. Anyway.
I know this isn't a really necessary feature and probably quite hard to implement, but as I've made [an ugly Metro design mockup](https://hummingbird.me/stories/5465786), I wondered if it'd give you the idea of allowing users to make custom skins. Of course, most music players or whatever software that allow that have huge codebase ([MusicBee is awesome when it comes to customization](http://i.imgur.com/lxMmXKt.png)) and that probably doesn't fit with Taiga's simplicity but I thought I'd give a shot at suggesting it.
So, what do you think of this? If I were able to write C, I would totally help you with that, even if I had to fork it and do it on my own, but I'm just a poor CSS user :(

**Comment by rr-** [comment]
This is pretty huge, the whole code behind the windows (and appearance!) would need to be abstracted away into some .xml.

Perhaps a shift towards QT (that allows just that) would be sufficient... and it'd give insta support for Linux, which means two birds with one stone.

**Comment by TheCoward** [comment]
I'd sure love that, because back a while ago, I had problems with my HDD and had to use Linux on a live USB for a while. I sure missed Taiga back then. But then Qt means rewriting the whole codebase from scratch to a new language?

**Comment by rr-** [comment]
Qt is a framework for designing cross platform interfaces. While it's still C++, the methodology shift is so significant that this might as well qualify for a full rewrite.

**Comment by TheCoward** [comment]
Yeah, I knew about Qt being an UI thing, but not what language it was. Then again, I guess that's one of your _long-term_ projects either way, but I'd be really tight if this was ever implemented.

**Comment by erengy** [comment]
Hi there @TheCoward. I'm glad you find the application useful!

Qt is indeed pretty good when it comes to UI customization, thanks to its CSS-like style sheets. It makes things a lot easier than rolling out your own syntax, parser, custom controls, etc., which is not worth the effort unless you really need the feature.

As @rr- mentioned, it's a huge task (i.e. requires hundreds of work hours) for Taiga to switch to Qt. I don't think it's going to happen anytime soon (i.e. this year), but that's what I intend to do for v2.0. For now, I'm trying to pave the way for an easier transition.

Honestly, I don't plan on providing complete control over the UI to the user, even after we make the switch to Qt. In my opinion, adhering to the design guidelines of the operating system and displaying the same look to all users are more important than UI customization, due to various idealistic and practical reasons. But my current decision isn't set in stone; we'll cross that bridge when we come to it.

**Comment by vendethiel** [comment]
Good thing is that taiga's ui code is pretty abstracted. It'd be amazing if taiga could be made xplatform :)

**Comment by erengy** [comment]
Closing this issue until v2.0.
