### ISSUE TITLE
Re:Zero S3 episodes not recognized

### ISSUE THREAD

**Issue by Atario** [erengy/taiga#1212]
Example filename:  `[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 52 (720p) [64254B79].mkv`

**Comment by erengy** [comment]
The relevant rule was added last week: https://github.com/erengy/anime-relations/commit/2fbdadc504d0ebf2dbcd4e373426ef32cef404d4

Make sure you have the latest anime relations, using *Help → Check for updates*. You can also check `Taiga\data\db\anime-relations.txt` manually to see if the file is up to date.

Otherwise you might have conflicting alternative titles preventing Taiga from matching the filename with the latest series. For instance, if you previously set `Re Zero kara Hajimeru Isekai Seikatsu` as an alternative title to S2, removing that may resolve the issue.

**Comment by Atario** [comment]
Ah, `Check for updates` did it.  I didn't know that's how this was done; I had been expecting the Sync button to do this (too), or maybe for Taiga to just figure it out on its own.

**Comment by erengy** [comment]
If you have *Settings → Application → General → Startup → Check for application updates* enabled, Taiga automatically downloads the latest anime relations too. Though it doesn't get triggered if you never restart Taiga (#1161).

Thanks for the feedback. I'll try to make this more obvious and perhaps work on #1161 for v2.
