### ISSUE TITLE
[Torrents] Unable to parse episodes with "|" in the title

### ISSUE THREAD

**Issue by GeorgeSummers** [erengy/taiga#1218]
Erai-raws changed title format for torrents in a rss feed and now Taiga cannot parse it.
For example, if entry in the feed is named `Dan Da Dan | Dandadan` and I am tracking anime with title `Dandadan` it's filtered out in the torrents list unless I specify `Dan Da Dan | Dandadan` in the "alternative title" as is.
Screenshots:
List:
![image](https://github.com/user-attachments/assets/513f8bcb-6efc-47fc-b6e5-a9559d4abfd0)
Torrents:
![image](https://github.com/user-attachments/assets/a58f0be5-9aa0-4a2b-a03a-0eb5b970297a)
After manually adding title:
![image](https://github.com/user-attachments/assets/db8b9e54-36e9-4e8e-bb9b-51efeff06cc9)

Is it a bug or how do I set a template for the new format?

**Comment by erengy** [comment]
I don't think there's any way around this at the moment other than adding an alternative title, as you did.

Since file names cannot contain `|`, this issue is specific to torrent names. Is it common enough to justify adding a special case? DB seems to be doing the same thing in their releases[^1]. Are there any other examples?

[^1]: e.g. `[DB] Dungeon Meshi | Delicious in Dungeon [Dual Audio 10bit BD1080p][HEVC-x265]`

**Comment by GeorgeSummers** [comment]
> Since file names cannot contain `|`, this issue is specific to torrent names. Is it common enough to justify adding a special case? DB seems to be doing the same thing in their releases[^1]. Are there any other examples?

Except for Erai-raws and your example I did not find any other cases as for now. Seems to be a new thing, but curious that it happened to 2 different release feeds.

**Comment by GeorgeSummers** [comment]
Seems like Erai-raws stopped using this template in their feed, tracking works fine once again.
