### ISSUE TITLE
Add exception for Classroom Crisis

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#128]
Expected behavior: Searching for "classroom crisis" on MAL through Taiga returns Classroom☆Crisis.
Actual behavior: No results, because MAL only returns the correct show if it contains ☆ or you search for a shorter substring.
Solution: I'm actually not sure how this could be fixed, besides just adding an exception for this show if you have such a system in place. This is entirely MAL's fault.

**Comment by erengy** [comment]
This issue is caused by a bug in MAL's search API, which I've reported multiple times to no avail. It's not the only issue with the search method either.<sup>[[1]](http://myanimelist.net/forum/?topicid=1382824)[[2]](http://myanimelist.net/forum/?topicid=30866&show=7950#msg39552596)</sup>

There are many other titles (e.g. `Aldnoah Zero` / `Aldnoah.Zero`, `Clannad After Story` / `Clannad: After Story`, `Fate stay night` / `Fate/stay night`) affected by the same issue. But I don't think adding exceptions for search queries is a good idea.
