### ISSUE TITLE
Information view: producer is always "unknown"

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#145]
Right now when I look at the information view of a show the producer is always listed as unknown. This includes both old shows and newly-added ones. The anime service I use is MAL.

**Comment by erengy** [comment]
Taiga cannot retrieve the information automatically, because MAL's API doesn't provide it. However, Taiga should display the producers for recent anime, because I include them manually in [season data](https://github.com/erengy/taiga/blob/6db2d8183f2b10d43c1e8177135e2c80be6baa22/data/db/season/2015_summer.xml).

**Comment by ConnorKrammer** [comment]
That makes sense then, and is sort of what I suspected. Closing, because there doesn't seem to be anything to be done.
