### ISSUE TITLE
Posting updates to Hummingbird throws SSL connect error

### ISSUE THREAD

**Issue by tulongest** [erengy/taiga#146]
It was working 40 minutes ago. Any idea what could have caused the error?

**Comment by tulongest** [comment]
I just had to re-open the application for the issue to disappear. It may come up again.

**Comment by erengy** [comment]
Related to #44, #63, #114, #122.

If you can, try running Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) and see if you get the same error (0x80092013) as in #122.

**Comment by ZetaHunter** [comment]
Happens to me too, only for me it throws it after I resume my windows session after putting it to sleep.
For example yesterday after watching animeh, I went to sleep and put it to sleep.
Today morning watching Monster Musume it started throwing SSL connect error 405 too.
That could be because the ssl timeouts or something? I don't know.
Also this has been happening essentially every time I put my pc to sleep with taiga still open.
