### ISSUE TITLE
Torrent download always fails

### ISSUE THREAD

**Issue by Amer2703** [erengy/taiga#154]
This issue started after upgrading to Windows 10. When attempting to download the status bar shows: "Downloading torrent file...(1-100%)"  "Torrent download error: Torrent file doesn't exist". I am using uTorrent 2.2.1.

**Comment by erengy** [comment]
Where did you install Taiga? If you installed it under a protected directory (such as Program Files) rather than the default location, User Account Control might be preventing Taiga from saving the .torrent files. If that is the case, you can either run Taiga as administrator or reinstall it to its default location where it doesn't need the privileges.

**Comment by Amer2703** [comment]
I kinda guessed it had something to do with permissions since w10 has been giving me problems with that since I installed it. Anyway I set it to run as administrator and that fixed it so thanks for your help.
