### ISSUE TITLE
MyAnimeList returns 400 Bad Request

### ISSUE THREAD

**Issue by n341** [erengy/taiga#157]
Every time I try to update any Anime to MyAnimeList, the following message appears in a pop up window
![sin titulo](https://cloud.githubusercontent.com/assets/13727496/9162799/a781250a-3f1d-11e5-8cf9-5743b0c6c89c.jpg)

**Comment by erengy** [comment]
It seems MyAnimeList changed something on their backend and broke the API's list update method. Other users of the API are reporting the same issue. I'm looking into it right now, but we probably can't do anything but let MAL know and wait for them to fix it.

**Comment by Manny331** [comment]
Well this sucks I guess we'll have to wait till MAL does something on their end..

**Comment by erengy** [comment]
Reported the issue: http://myanimelist.net/forum/?topicid=1415479

**Comment by erengy** [comment]
Need a little help. Could anyone try out [this build](https://dl.dropboxusercontent.com/u/2298899/Taiga/TaigaSetup.exe) and see if it resolves the issue? If you can, please try adding and removing anime, as well as updating existing items on your list.

**Comment by ConnorKrammer** [comment]
I just installed it. Is it supposed to be build 1.1.11?

**Comment by erengy** [comment]
Nope. Sorry, just updated the build, could you try it again now?

**Comment by ConnorKrammer** [comment]
Seems to work perfectly. I tried adding new items as well as updating existing ones and there wasn't any problem.

**Comment by erengy** [comment]
Just released v1.2.2, which should work as expected. I'll keep this issue open for now, until MAL actually fixes the underlying problem.

**Comment by ConnorKrammer** [comment]
Hopefully MAL will be updating/extending their API soon. There was an AMA on the anime subreddit by MAL's founder on Sunday, and [a number of questions involved the API](https://www.reddit.com/r/anime/comments/3gedyl/im_xinil_creator_and_lead_admin_of_myanimelist/). Supposedly it's supposed to happen by the end of the year; hopefully it does and it isn't just an instance of Coming Soon&trade;

May or may not be news to you, but I thought I'd put it here since it's somewhat relevant.

**Comment by erengy** [comment]
MAL has fixed the bug on August 12, so I'm closing this issue.

In hindsight, I think it was a good decision not to wait for MAL and release v1.2.2. It took ~60 hours for them to fix it, so that'd have been an additional two days with errors and no synchronization, if not for the update. In the meantime, it seems some MALU users have tried out Taiga too.
