### ISSUE TITLE
Seasons: View improvements

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#162]
Just some comments on Taiga's seasons view:

- It would be nice if the previously selected season persisted between sessions, or if the current season was displayed by default. This reduces the frequency with which a user has to use the "Select season" dropdown.
- The season selection dropdown could be improved somewhat (see GIF for example) by the following:
  1. Bolding the current year to draw the user's eye
  2. Pinning the current year to the top of the list and differentiating it with a divider
  3. Making the rest of the year list forward chronological instead of reverse chronological. This point could be argued, but the vast majority of people find it easier to count forwards rather than backwards. There's an added degree of mental incongruity in this particular case because we're dealing with dates; among numbers, time in particular is viewed as linear and forward-moving. Points i. and ii. allow preserving the convenience of having the current year at the top.
  4. Making the season list forward chronological instead of reverse chronological. This is mostly to reduce confusion with other mental models the user may have regarding seasons. This gets a bit messy, but here's my best attempt at an elaboration:
    - The order of the physical seasons is Winter > Spring > Summer > Fall, but they are often depicted visually as Spring > Summer > Fall > Winter, to better represent the idea of growth > maturity > decline > death. (For somewhat-scientific evidence of this, a [Google image search](https://www.google.com/search?q=seasons&safe=off&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMI6K7qmZCnxwIVAVU-Ch0BNQr9&biw=1372&bih=802) for "seasons" is worthwhile.) The issue with this in regards to Taiga's order is that Taiga lists the seasons in reverse chronological order, which results in an overlap between Winter from the two mental models (Taiga uses the actual order where Winter is first, but then flips it, resulting in Winter being last -- something that you'd expect from the spring-first order). Normally even this isn't that bad, except that we're talking about time here; it's not unnatural for the user to expect the latest season to be last on the list. It's also relevant that a user used to navigating menus can click through to the expected location of an item and barely even read the actual labels. All of this combined facilitates accidental selection of the winter season when the users actually want whichever one is most recent. (Although it's only anecdotal, I myself have definitely done this.)

Those are my thoughts on it. I mocked up a before/after GIF of what the dropdown would look like with the suggested changes:

![season dropdown v1](https://cloud.githubusercontent.com/assets/1044441/9264360/c1bb4f96-41e2-11e5-83e6-588fb091b421.gif)

And yes, I'm sorry for always making you read so much. At least I use pictures right?

**Comment by erengy** [comment]
I've done some work under the [`seasons` branch](https://github.com/erengy/taiga/compare/seasons) recently:

- Taiga can now automatically download season data from a remote location (e.g. this GitHub repository). This means that we no longer need to release a new version in order to distribute new season data. Also, I can now remove all those XML files from the installer, although I'll probably wait until v1.3 for this.

- Taiga now remembers the last selected season after you restart the application. I went with this rather than displaying the current season by default. This suggestion is so obvious in hindsight, but I somehow had not thought of it until you mentioned it.

- The latest two seasons are now displayed on top of Select Season menu for quick access. There's also an indicator for the currently selected season.

This is how it looks right now:

![select-season](https://cloud.githubusercontent.com/assets/1078430/12100585/98996c16-b338-11e5-9b2d-0bf7ced54657.png)

I kept the reverse chronological order, simply because it's more likely for the user to look for the newer seasons. Changing the order increases the cursor's travel distance in most cases, and it gets worse as we add more seasons (in either direction).

I could at least sort the submenus as `Winter, Spring, Summer, Fall`, but this makes things somewhat inconsistent (i.e. the season names are sorted chronologically, while the years are sorted in reverse). I haven't made up my mind on this one, though.

**Comment by chriswen** [comment]
This sounds great.

**Comment by cyalins** [comment]
Sorry about the duplicate issue on the season stuff. Looking forward to the new release, good luck!

**Comment by erengy** [comment]
v1.2.3 is going to be ready within a few days, if not tomorrow. I've updated the [latest build](http://taiga.moe/latest.html) for those who'd like to test it beforehand.

**Comment by erengy** [comment]
Now that v1.2.3 is released, I'll be closing this issue. Thanks for the suggestions, @ConnorKrammer!
