### ISSUE TITLE
Anime name recognition?

### ISSUE THREAD

**Issue by brandonho36** [erengy/taiga#172]
Sorry if this has been asked before or if this is a dumb question

Anyway, I just installed Taiga and added my folder "Anime" as my Library folder. The program was able to detect shows such as Shirobako and Shimoneta, but it was unable to detect Gekkan Shoujo, Mirai Nikki, and No Game No Life. I added the folders on my own by right clicking the show and doing "set manually", but I still am unable to launch episodes from those shows using Taiga.

So 1) What can I do to make the program detect those folders
2) If I can't do anything, how can I make the program detect the episodes after I add the folders to the corresponding shows?

This is the folder: http://imgur.com/B2urTbL

**Comment by brandonho36** [comment]
I restarted Taiga and two things happened.

1) Windows detected it as malware, or at least a malware notification appeared when I opened Taiga

2) Taiga no longer detects Shimoneta. I know for sure it used to detect this show. I didn't change anything about the folder

**Comment by erengy** [comment]
*Mirai Nikki* is a special case, because there are two anime with the same name (the OVA and the TV series). Taiga should be able to play/identify episode 2 and onwards as expected (because the OVA has a single episode, the ambiguity is resolved). But you could also add `Mirai Nikki` as an alternative title for the TV series.

There shouldn't be any issues with *Gekkan Shoujo Nozaki-kun* or *No Game No Life*, unless you changed the default filenames of HorribleSubs' and Underwater-FFF's releases. Is Taiga able to identify the episodes if you open them manually rather than trying to play them from within the application? If not, what do you see in the Now Playing page?

Note that setting the folder for an anime doesn't affect recognition. It's basically just a hint for Taiga to look into that folder first, so it doesn't have to scan your entire anime library.

**Comment by brandonho36** [comment]
Thanks for the response. Here is what I see on the now playing page, I opened episode #3 this is what I see: http://i.imgur.com/7tWkid2.png

I did end up changing the file names for Mirai Nikki, NGNL, and Gekkan Shoujo. However, I also changed the filenames to Shirobako similarly (#. Episode Title) before installing Taiga and Taiga still automatically recognized those files. 

Is there any way to directly correspond a show's episodes to a file? In this case, so I can fix the stuff with Mirai Nikki OVA/Episode 1, although knowing how to do this would be useful in the future


Thanks

**Comment by brandonho36** [comment]
I also recently downloaded the Commie release of Oregairu Zoku through nyaa and Taiga won't recognize it. I didn't change any of the file names this time, and you can see the folder name I have at the top
http://i.imgur.com/5sYtfBj.png

**Comment by erengy** [comment]
Gekkan Shoujo Nozaki-kun [HorribleSubs] (1080p)\3. Violence vs. the Prince.mkv

When the filename itself doesn't include the anime title, Taiga checks the upper directories. However:

1. It expects the directory name to be equivalent to the anime title, without any additional release information such as `HorribleSubs` or `1080p`.
2. It assumes that the release group never immediately follows the anime title.

The first point is easy enough for me to fix. But the second one is almost certainly going to break some other cases, so I'll need to spend some time testing things. For now, you can rename the folder to `Gekkan Shoujo Nozaki-kun` or add `Gekkan Shoujo Nozaki-kun [HorribleSubs] (1080p)` as an alternative title for the series.

> I also changed the filenames to Shirobako similarly (#. Episode Title) before installing Taiga and Taiga still automatically recognized those files.

This is because the folder name you have for the series is `Shirobako` only.

> Is there any way to directly correspond a show's episodes to a file? In this case, so I can fix the stuff with Mirai Nikki OVA/Episode 1, although knowing how to do this would be useful in the future

In this case, using `Mirai Nikki (TV)` rather than `Mirai Nikki` should work.

> I also recently downloaded the Commie release of Oregairu Zoku through nyaa and Taiga won't recognize it.

Note that Commie's files have the title as `Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - My Teenage RomCom SNAFU TOO!`, with the extra English part. You just need to add that as an alternative title for the series, which you can do with a single-click via Now Playing page or manually via Anime Information dialog.
