### ISSUE TITLE
[question] torrent checking

### ISSUE THREAD

**Issue by brubblu** [erengy/taiga#175]
Hello,
I would like to be able to add a custom RSS feed, but in settings -> torrents -> discovery all I see is a drop down menu, with no "Add" function. Also it would be really great if there was a quicker way to change the RSS feed for discovery, or even to let you search in all of them. It is possible that this functionality already exists but I was not able to find it, but I think that the way things are now, the torrent search function is quite confusing.

**Comment by erengy** [comment]
Hi there @brubblu.

It's not possible to "add" a custom RSS feed, but you can still enter your own URL rather than choosing one from the list Taiga provides. The list is just there to provide some default options.

As far as I know, only Nyaa provides a proper search function, so it's not quite possible to make it search more. That being said, I do intend to allow checking multiple feeds in the future, as described in #40.

**Comment by brubblu** [comment]
Hi,
thank you for your quick response. The only way to enter my own is to rewrite one of the two given URLs, am I correct?

**Comment by erengy** [comment]
Yes, that' right. It's just a regular dropdown list that allows the user to enter a choice that isn't in the list. It's not something specific to Taiga; it's used all around Windows.

Example:

![drowdown](https://cloud.githubusercontent.com/assets/1078430/9831739/49fc1ff8-596b-11e5-8335-c6995e03b5fd.png)
