### ISSUE TITLE
Rewatching anime and total time spent watching

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#198]
When you mark a show as being rewatched, the total "Life spent watching" stat decreases by the length of the show in question and eventually reaches its old level when the show is completed again. This is different from the expected behaviour, which would be for the total time statistic to stay the same and increase above its previous value with each new episode rewatched. On the extreme end of things, marking all anime as being rewatched would result in a total time spent watching of zero minutes.

Related to this, it would be useful to see how many times a show has been watched. I know that this is possible using MAL (I'm not sure about other services), though I don't think they supply an API endpoint for it. I like the idea of Taiga tracking it anyway, since it could be synced if they ever overhaul/complete their API.

**Comment by erengy** [comment]
Tracking how many times a series has been re-watched is not possible due to the limitations of MAL API. Basically, it lets you update the value, but it doesn't tell you what the initial value was. Taiga does [increment it](https://github.com/erengy/taiga/blob/6a1246384fe86b7f9212937d7229467ce0b8db6a/src/library/anime_util.cpp#L464) internally, but avoids overwriting the remote value.

I believe that the bug you described on the first paragraph should be easy enough to fix, though.
