### ISSUE TITLE
Download anime_relations.txt from repository

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#207]
I noticed that you added the ability to download season data from the repository in the seasons branch. I think anime_relations.txt should be treated the same way. This would make it easier to push new data to users and it's one less file that you distribute with the installer.

**Comment by erengy** [comment]
This is [already the case since v1.2.0](https://github.com/erengy/taiga/commit/0ae1c101f65b2fcdedf4cfe673c92234167492ee). Taiga downloads the latest `anime_relations.txt` when the user checks for an update, even if there's no new version of the application. After merging the `seasons` branch, I'm planning to expand the functionality to automatic updates.
