### ISSUE TITLE
Now Playing: Differentiate similar titles when current one is unknown

### ISSUE THREAD

**Issue by Zenithtb** [erengy/taiga#230]
I don't know if this is an 'issue' or simple User Error:

Sometimes when I have an Unknown Anime, and I perform the Search there are many results.

On occasion I have misidentified the correct result.

(Eg, I select [Name OVA] instead of [Name; OVA]
NameOVA may have 3 episodes
Name;OVA may have 4, pointing out I clicked the wrong result).

Is there a way to Undo this click, or somehow make Taiga 'forget'?

So far the only way I've managed to do it is load up the Anime.XML in an XML or text editor, find the relevant entry and delete it.

Is there a more user-friendly method? Is this a Missing Feature?

If I've failed to explain properly, just say so - I found it a bit hard to be clear!

Many thanks

**Comment by erengy** [comment]
By "this click", do you mean clicking on an anime title on Now Playing page? If so, all it does is to add the current title as an alternative title for that anime, which can be removed via the Anime Information dialog. However, removing an alternative title is currently not possible if the anime is not in your list (see #183).

**Comment by Zenithtb** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13133658/13023330/30c9c9b8-d1e8-11e5-8a64-0987d76812d7.png)

(Many thanks for the quick reply)
I think we understand each other.
(See picture)

So if I _have_ the 'correct' in my list, I can find it and delete the **alternative** title, and that will make the file I'm playing 'unknown' again, and I can select the correct entry from the Now Playing screen?

However if I don't have the correct anime in my list, it's issue #183?

If I understood you, many thank for the support, and consider this Resolved.

**Comment by Zenithtb** [comment]
Can I change my mind, please? Would it be in any way possible to have

[Name of anime] [Link]

as the formula in the MAL search results, where [Name] is what is currently displayed, but [Link] will jump you to the MAL page of that name?

So many names (especially OVAs) have names that are so similar you need to read the anime description to know which one is which. Having a page-link next to it to open in a browser would help many times.

Many thanks if you find time to read this.

**Comment by OsaSoft** [comment]
Adding a Link to MAL there seems like a fairly good idea. I'll try doing and see how it goes

**Comment by OsaSoft** [comment]
@Zenithtb before I get to it, would something like this work? After clicking the link, the anime details window would pop up.
(pardon the quick mspaint job >.<)
![taiga4](https://cloud.githubusercontent.com/assets/8895463/14003239/5de5423c-f151-11e5-898b-e82da4539808.png)

**Comment by Zenithtb** [comment]
Yeah, just like that. 

I can't be the only one who hasn't memorised each and every anime, can I?   :-P

A chance to check the details before adding is needed, and having to go to MAL manually is tricky. 

So a simple [Info] link would help immensely...

**Comment by erengy** [comment]
Instead of adding more links beside anime titles, which would make the page look way too crowded, we may use the existing links for the same purpose. Clicking on a link would display a context menu where the user could either display more information about the anime or add the current title as an alternative title for it.

Preferably, I'd like to keep the current left click behavior and display the context menu on a right click. But I don't know if SysLink controls send a notification when the user clicks on a link with the right mouse button.

**Comment by OsaSoft** [comment]
a right click behavior would be the best solution, I wouldnt want to replace the current leftclick behavior either. Although I dont see how an extra link would make the page too crowdod, considering todays resolutions and screen sizes. 
In any case, Ill see what can be done

**Comment by Zenithtb** [comment]
@OsaSoft 

Just noticed that you said "After clicking the link, the anime details window would pop up." - regardless of whether right-click, extra link etc, I noticed a problem;

Is it not true that Taiga knows nothing about an anime until it is added to your list?

So surely popping up the Anime Details window would not be possible until the anime is already added?

Pulling the info from MAL before adding would be needed... If I understand how Taiga works...

**Comment by OsaSoft** [comment]
@Zenithtb You can open the anime info window for example by clicking an anime in the season browser, or when searching MAL. So that shouldnt be a problem.

**Comment by OsaSoft** [comment]
Hi everyone! So I finally managed to get around to this! While the edit itself was not too dificult, took me some time to wrap my head around the project and the workings of the application.
Ive decided to go with the extra link, because honestly it seems better than the rightclick functionality @erengy suggested. Its more intuitive (since you dont have to know about a right click functionality in order to use it) and doesnt take much space, so the page doesnt feel crowded, even at lower resolutions (tested on 1080p, 720p and 1024x768) with different window sizes.

Anyway, heres some actual screenshots:
![link](https://cloud.githubusercontent.com/assets/8895463/15270580/11f4a19a-1a25-11e6-9a0a-6e14234626da.jpg)

After clicking the link, the anime info window shows:
![after](https://cloud.githubusercontent.com/assets/8895463/15270581/1c42a0e8-1a25-11e6-9b1d-bf1f401aab88.jpg)

**Comment by ConnorKrammer** [comment]
Not bad; this'll be useful when you aren't sure which show is which.

Feedback: I think this is a good candidate for using an icon or symbol to indicate more info. A question mark or similar icon sounds like a good candidate; to avoid excessive visual impact or distraction, I'd set it to 50% opacity unless the name is being hovered over. That keeps distraction to a minimum and avoids using excessive screen space, because at the moment there is a significant addition of clutter to the screen.
On 14/05/2016 2:44:10 PM, Oscar Hernández <notifications@github.com> wrote:
Hi everyone! So I finally managed to get around to this! While the edit itself was not too dificult, took me some time to wrap my head around the project and the workings of the application.
Ive decided to go with the extra link, because honestly it seems better than the rightclick functionality @erengy [https://github.com/erengy] suggested. Its more intuitive (since you dont have to know about a right click functionality in order to use it) and doesnt take much space, so the page doesnt feel crowded, even at lower resolutions (tested on 1080p, 720p and 1024x768) with different window sizes.
Anyway, heres some actual screenshots:
[link] [https://cloud.githubusercontent.com/assets/8895463/15270580/11f4a19a-1a25-11e6-9a0a-6e14234626da.jpg]
After clicking the link, the anime info window shows:
[after] [https://cloud.githubusercontent.com/assets/8895463/15270581/1c42a0e8-1a25-11e6-9b1d-bf1f401aab88.jpg]

**Comment by OsaSoft** [comment]
@ConnorKrammer oooh, an icon is actually a really nice idea. Ill try and see how it works.

**Comment by Zenithtb** [comment]
Looking good! I also like the Icon idea. Even a simple '?' would be enough for most people to guess the meaning.

Where/how can I check this current version? It looks like it's going to be really helpful!

**Comment by OsaSoft** [comment]
Ok! So becuase the text here is a syslink, I dont know of a simple solution to get an actual icon in there, since it only supports text and links. BUT! I figured a workaround - emoji! Sadly, the "i" bubble emoji looks bad, but i think this questionmark emoji looks pretty good, what do you guys think?
![emoji](https://cloud.githubusercontent.com/assets/8895463/15276099/319fcac4-1ade-11e6-9420-acfcc3f2b88a.jpg)

@Zenithtb Dont think you can check this out for yourself unless you downlaod my code and build it yourself. But hopefully if @erengy likes it enough he'll merge my change and include it in a future update of Taiga.

**Comment by ConnorKrammer** [comment]
@OsaSoft Definitely better than before.

To get even more polished, have you tried using a proper icon font, such as [Font Awesome](https://github.com/erengy/taiga/issues/230#issuecomment-219303271)? Icon fonts tend to have dedicated question mark and info icons. For Font Awesome in particular, you can view these by typing "question" or "info" into the search bar on the previously-linked page.

That still requires you to be able to change the font for the link, however, and I don't know if that's possible.

**Comment by wopian** [comment]
Right clicking to bring up context menu still seems the better option, both visually and functionally.

**Comment by ConnorKrammer** [comment]
Going the right-click route is definitely better visually. However, it poses a problem: How does the user know that they can right click? Adding additional functionality to a hyperlink via context menu isn't a standard UI paradigm, and in the absence of that the only way for a user to discover the functionality is to *guess*.

That's not great, from a usability perspective.

**Comment by OsaSoft** [comment]
@wopian I agree with @ConnorKrammer on this one. Right-click functionality is very nonstandard for hyperlinks and users would have to _know_ that its there. Not to mention AFAIK the hyperlink functionality in SysLink only registers left-clicks and keyboard activity (space or enter when link is selected).
As for FontAwesome, itd be great to use something like that, but from what ive been able to dig up you cant change the font in the text of a syslink object.
I imagine a viable solution would be to rewrite the entire thing using something like MSHTML, but thats more trouble than its worth, specially considering the longterm goal of rewriting Taiga's UI into something non windows-specific, such as QT.

**Comment by erengy** [comment]
As I mentioned previously, displaying additional text such as `(See anime info)` beside anime titles is a no go. In that regard, `❔‍` takes up less space, at least. If it was possible, I'd try adding muted icons like this, as @ConnorKrammer suggests:

![i-cheated-and-used-html](https://cloud.githubusercontent.com/assets/1078430/15276735/3a21afbc-1af9-11e6-90c8-f911056520c9.png)

However, the measly SysLink control we have is not capable of such intricacies. Anything above the current use requires a custom-drawn control, or at least a RichEdit box. And I'm personally not planning to make significant changes on the UI until v2.0, where we'll be able to do much more.

If we're bent on following this through now, I'd probably go with one of the following options:

- Put the info links at the left side, with or without bullets. I imagine that they'd be a little less distraction when they're aligned.
- Display a context menu. Note that, while I haven't fully researched it, capturing the right-click event is likely not possible. So the menu will always be displayed on left-click. This requires an extra click, but on the other hand, gets rid of the "how does the user know" problem.
- Display a tooltip when the user hovers on an anime title. Again, I don't think the SysLink control allows this.

**Comment by wopian** [comment]
>Adding additional functionality to a hyperlink via context menu isn't a standard UI paradigm

Uh, ok. Right clicking for additional functionality is a pretty basic use case in apps and the web.

![](http://i.imgur.com/p9bXJnl.png)

**Comment by Zenithtb** [comment]
I'd agree with r-click if you were planning to have additional options in the future (maybe 'Score', 'Move to...' or something).

For a single 'View Anime Info' though, r-click seems a little overkill. A '?' to the left or right of the name seems to fit in better with the UI, is more discoverable, and needs fewer clicks to use.

IMHO, OC

**Comment by OsaSoft** [comment]
Thanks for all the feedback! Replacing the bullet point seems like the best idea, since it doesnt take up any new space. Whether to put the icon left or right of the anime title, I prefer on the right, but tell me what you guys think.
Muted icons really seem impossible with SysLink.
Pulling up a menu on left click seems excessive if we only have two choices (Select this anime & See anime info) if we dont plan more features there in the future and it complicates selecting the proper anime when the choice is clear (which id say is about 90% of the time at least)
Anyway, ive tried replacing the bullet point and using different emojis, which do you think would fit the role best?
![emoji-choice](https://cloud.githubusercontent.com/assets/8895463/15292084/a31cbfe2-1b81-11e6-9048-8aa6eb8d9a7c.jpg)

**Comment by Zenithtb** [comment]
@OsaSoft I like the solid Question-Mark and the magnifying glass/

The Eye would imply 'Watch' to me, and although I could understand an argument for the 'i' (for Information) it'd be a touch small to click on.

I use Taiga on a TV with a wireless keyboard/track-pad combo, so 'More obvious and easier to click' is better in this usage case.

Although if we're going into this much detail over a single character, an Ini file preference would be the most obvious choice, keep the character within the source as a variable. Even if the character choice was not not exposed in the Preferences, I think most people using Taiga could manage an Ini-file edit if they're that desperate  :P

**Comment by ConnorKrammer** [comment]
I agree with @Zenithtb about the solid question mark and the magnifying glass, with a preference for the former over the later. The magnifying glass carries the additional implication of "searching" which conflicts somewhat with the call-to-action, "Not in the list? **Search** for more." below the list.

The other challenge is to clearly differentiate between the emoji as a link and the title as a link; their proximity and colour make it easy for an inattentive user to confuse them for the same link. Padding the emoji out with more than one space character might fix this, but I'd have to actually whip up a test in Photoshop to confirm for sure.

After thinking about it for a bit, the ideal UI element to use for selecting the correct show is probably more along the lines of a [set of radio buttons](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/radio-button) (as only one show can be selected) with a clear "submit choice" button below them. That would also allow clearer differentiation between the action of selecting a show and of opening its information view. Unfortunately, it's also more work and might be better considered after the UI overhaul that will come with v2.0.

---

@wopian With regards to adding functionality to a hyperlink via right-click, I could have been clearer, so I'll elaborate a bit. When a browser registers a right-click on a hyperlink, it opens a context menu with a variety of actions. These actions fall under two categories: treating the link as text ("Copy link address"), or as a gateway to another page ("Open link in new tab", "Save link as..."). These don't actually add new functionality to the link; rather, they act as shortcuts for common actions that could still be performed were the context menu removed. If the user were for some reason unaware that context menus existed, they could still complete whichever task they desired.

| R-click command | Alternate method |
|---------------------------------|-----------------------|
| **Open link in new tab** | Click link, copy URL from address bar, open new tab, paste in new tab, return to original page in previous tab |
| **Open link in new window** | Same as above, but with a new window instead of a tab |
| **Open link in Incognito window** | Same as above, but with an incognito window |
| **Save link as...** | Open link, then save the page as an .htm file |
| **Copy link address** | Click link, copy URL from address bar, return to previous page |

However, Taiga's case is a bit different: the proposed context menu option adds additional functionality that's unreachable from anywhere else in the application. I say that doing so isn't a "standard UI paradigm", because if it were then the expected user behaviour would be to right-click on anything that looked even remotely actionable, and that's not particularly kind to the user.

**Comment by erengy** [comment]
I was able to somewhat differentiate the two links by changing the new one's color to the default one (cannot change it to something else or remove the underline). Here's how it looks:

![fake-anime](https://cloud.githubusercontent.com/assets/1078430/15308914/b2cd8412-1bea-11e6-98b6-7d574471d9ce.gif)

PS: Designing a better UI is important, but let's not lose ourselves to bikeshedding here.

**Comment by OsaSoft** [comment]
oh that actually looks much better, as for the position, i personally prefer the right hand side

**Comment by Zenithtb** [comment]
Left, right, or inserted into the dead-centre of the anime's name, I just hope it makes it into an update. 

Anime
Anime (2006)
Anime (2008)
Anime (TV)
Anime (OVA)
Anime (Special)
Anime (OVA)
Anime (OVA)
Anime (Special)

Are surprisingly hard to tell apart with no other context. Even a year or season added to the end would make a huge difference.

</mythoughts>

**Comment by OsaSoft** [comment]
Ill add onto @Zenithtb's post and ask when can we expect this in a release? At first I just thought its a nice feature, but actually working on it and discussing it with all of you has made me strangely fond of the lone question mark :smile_cat:

**Comment by erengy** [comment]
> Is your Update History exposed through the MAL API?

Nope. Taiga keeps its own history. MAL's API is limited and wacky in general, not just in this case.

> when can we expect this in a release?

I'm not planning another v1.2.x release at the moment, and v1.3 needs a lot of work. But I'll update the [latest build](http://taiga.moe/latest.html) after committing this change.

**Comment by OsaSoft** [comment]
Thats awesome. Thanks!
Also never noticed the option of downloading the latest build! I love testing possibly unstable early builds :grin: 
Although I must say Nightly probably runs better than stable release Firefox :joy_cat:

**Comment by OsaSoft** [comment]
@Zenithtb I just realized you can probably use my build. So until the change gets merged into the main project and released as latest build as @erengy said, heres the link to my exe in zip (pass: ilovetaiga). Just drop it into your Taiga install folder (Just to be safe, backup your original Taiga.exe)
https://dl.dropboxusercontent.com/u/56623141/Taiga.zip

**Comment by Zenithtb** [comment]
Many thanks - it works  :)

![taiga](https://cloud.githubusercontent.com/assets/13133658/15396288/b3c39698-1ddb-11e6-8012-05708719a232.png)
