### ISSUE TITLE
Anime season data

### ISSUE THREAD

**Issue by healthstr** [erengy/taiga#244]
It seems that the anime data has to be made by hand then using a program to create it, also the anime season data is now out of date.

**Comment by erengy** [comment]
I have a Python script that automatically scrapes the necessary data from MyAnimeList and Hummingbird, although I usually go over the data to check for potential errors. This time I also had to update the script due to some recent changes at MAL's website. I wish they had an API method for this so that I could integrate it into Taiga, but they don't, unfortunately.

Spring 2016 season data is now available for v1.2.3 users. If it doesn't appear automatically at the Seasons page, try using the *Help → Check for updates* menu item.

**Comment by healthstr** [comment]
Hello, Thank you for explaining I did wonder why it was like this would you be able to link me to the python script so I could take a look at it? please

**Comment by erengy** [comment]
I would love to, but scraping HTML pages isn't quite ethical when the website in question (MyAnimeList) is openly against it, which is why I refrained from sharing it so far, here or elsewhere. I believe that the script should remain as something I wrote for personal use.

That said, there's nothing too fancy about the script anyway. Basically, I use the Requests library to fetch various pages and Beautiful Soup to extract the data. Aside from optimizations and handling of edge cases, it took me just a couple of hours to get it working, and I don't exactly *know* Python.

**Comment by healthstr** [comment]
fair enough, thank you for the tips.

**Comment by vonkun** [comment]
Hello , can you please Add the new Data of Anime season cuz Data is out of date , or u can share with us the meathod to get that Data from MAL ...

**Comment by tophf** [comment]
@vonkun, [the method I've used for 2017 spring](https://github.com/erengy/taiga/issues/390) seems to be still working. Here's the xml file if you'll have trouble making one yourself: [2017_summer.zip](https://github.com/erengy/taiga/files/1058460/2017_summer.zip)

**Comment by vonkun** [comment]
ty for that , i will try it , thank you Again :D
