### ISSUE TITLE
Invalid directory name

### ISSUE THREAD

**Issue by AeonLucid** [erengy/taiga#246]
There is a little bug with downloading some anime that contain special characters.

Take this anime as an example.
http://myanimelist.net/anime/28013/Macross_%CE%94

It contains a delta character (Δ) and it seems to mess up with deluge.
Here is an image with what is going wrong: http://i.imgur.com/C0zzX79.png

**Comment by erengy** [comment]
The thing is, Taiga passes on the path just fine (e.g. `C:\Media\Anime\Macross Δ`), it's Deluge that's unable to read it. For me, it created a new directory named `Macross ¢` as the download location, where the encoding issue is apparent. Also note that uTorrent doesn't have this issue. In other words, the bug is in Deluge rather than Taiga.

Here's a [relevant post](http://myanimelist.net/forum/?topicid=214500&show=380#msg35971713) from Nov 16, 2014:

> Could you add a feature that strips non-ANSI characters from a torrent file name? Deluge does not accept unicode arguments and as such does not automatically open files with unicode filenames, and just ignores them. I have to go into the Taiga folder and add the torrent manually through the deluge UI, or rename the file. They've got a fix in for deluge 1.4.0, but I have no idea how long that'll be.

> Commie's Fate Stay Night UBW is basically the biggest culprit right now, as they add a unicode Slash between "Fate" and "Stay", which breaks everything...

I don't think that I can (or should) do anything about this. I tried converting the path to its short form (e.g. `C:\Media\Anime\MACROS~1`) and it worked, but this would fail in other cases.

**Comment by AeonLucid** [comment]
Thanks, I'll switch to uTorrent.
