### ISSUE TITLE
Filename with "$" causes a freeze

### ISSUE THREAD

**Issue by treborabc** [erengy/taiga#256]
A new fansub group, $tore is subbing Re:Zero this season and when attempting to identify episodes, Taiga freezes and has to be force closed. Tested and only occurs with dollar sign.

**Comment by erengy** [comment]
I don't have the means to test it right now, but I imagine that this is related to format strings rather than the identification process (the dollar sign is used as function prefix in format strings). You could try disabling automatic sharing from Tools menu and see if that prevents the freeze.

**Comment by erengy** [comment]
I just looked into this, and it's indeed due to a bug in the function that parses format strings. There's a relevant [issue](http://myanimelist.net/forum/?topicid=214501&show=800#msg43866625) where `\$` causes a freeze due to incorrect handling of reserved characters. These issues will be resolved in v1.3, which will include a brand new parser.

**Comment by Stonedestroyer** [comment]
I noticed it happens if you have a password with long strings and it parses it outside the password, and I check config file and I see it's been passed outside, I can provide example if needed.

**Comment by erengy** [comment]
It sounds like a different issue than what we have here, but could you give an example?
