### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#267]
I have just received two copyright infringement notices from [Japan Creative Contents Alliance](http://www.japancreativecontentsalliance.com) and [Aniplex USA](http://www.aniplexusa.com) regarding the screenshots<sup>[[1]](http://taiga.moe/img/screenshot/2015-04-30_seasons.png)[[2]](http://taiga.moe/img/screenshot/2015-04-30_now-playing.png)</sup> on Taiga's website:

```
ELECTRONIC NOTICE OF COPYRIGHT INFRINGEMENT

I, the undersigned, CERTIFY UNDER PENALTY OF PERJURY that I am an agent
authorized to act on behalf of http://www.japancreativecontentsalliance.com/
whose exclusive copyrights are being infringed. The information in this notice
is accurate.

Original Works & Copyright Holder(s):
Japan Creative Contents Alliance LLC
1201 Orange Street, Suite 600,
One Commerce
Wilmington, Delaware 19801

The work in question is CCopyright Japanese Anime, Title(s):
Gintama

I have a good faith belief that the items or materials listed below are not
authorized by the above owners, their agents or the law and therefore infringe
the owner's rights. Please act expeditiously to remove or disable access to the
infringing material or items listed as follows - the images, videos and/or
download links at the following URL(s):

http://taiga.moe/img/screenshot/2015-04-30_seasons.png

Truthfully,
/S/: Eric Green
```

```
ELECTRONIC NOTICE OF COPYRIGHT INFRINGEMENT

I, the undersigned, CERTIFY UNDER PENALTY OF PERJURY that I am an agent
authorized to act on behalf of http://www.aniplexusa.com/ whose exclusive
copyrights are being infringed. The information in this notice is accurate.

Original Works & Copyright Holder(s):
Aniplex of America Inc
2120 Colorado Ave. Suite 220
Santa Monica CA 90404 USA

The work in question is CCopyright Japanese Anime, Title(s):
Fate/Zero

I have a good faith belief that the items or materials listed below are not
authorized by the above owners, their agents or the law and therefore infringe
the owner's rights. Please act expeditiously to remove or disable access to the
infringing material or items listed as follows - the images, videos and/or
download links at the following URL(s):

http://taiga.moe/img/screenshot/2015-04-30_now-playing.png

Truthfully,
/S/: Eric Green
```

Now, I could easily update the images to display different anime, obviously (they wouldn't send a notice for *Mars of Destruction*, would they). Or, I could upload them to Imgur instead. But how is this any different than MyAnimeList, Hummingbird or pretty much any other anime-related website that displays poster images?

I wonder if there was any human involved in the process, or if it was just an algorithm that stumbled upon the images and got a match.

PS: I'd rather not blur/pixelate the images as it is the case for mobile apps on Google Play, for instance.

**Comment by kdbcinco** [comment]
Taiga's fetching the images from MAL right? Not sure why they started with yours. I'm pretty sure MAL, HB, AniList, etc are getting far more hits. On a side note, you may want to check the anime listed on their site.

**Comment by ConnorKrammer** [comment]
First off: I am not a lawyer. I am first and foremost a tech person, and tech people tend to overestimate the bounds of free use and copyright flexibility, as well as underestimate the complicated factors that can become involved.

That said, in my opinion screenshots of media and the like fall pretty squarely under fair use—there's a reason that all of Twitter hasn't yet been incarcerated. In the U.S. (and countries with similar laws), to persecute a work as infringing copyright a claimant needs to prove grounds based on four points of consideration:

1. the purpose and character of the use, including whether such use is of a commercial nature or is for nonprofit educational purposes;
2. the nature of the copyrighted work;
3. the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and
4. the effect of the use upon the potential market for or value of the copyrighted work.

The second point isn't much help in either direction—the Supreme Court itself has stated that it isn't often much help. The other three points are significant though:

1. Taiga is not a commercial product and makes no commercial gain from using the screenshots
2. Not much help either way (see above note)
3. The image used is not a substantial portion of the original work
4. The effect of the image upon the potential market is negligible.
  - This one could potentially be claimed if it could be proved that association with Taiga reflected poorly on the properties in question, but that's a difficult claim.

Both Aniplex and the Japan Creative Contents Alliance probably outsource their copyright infringement monitoring to the same outside company, which would explain why you received both claims at the same time. These companies often search the web for related content and file claims if it looks like it might be even mildly objectionable. In this case Taiga probably failed that test because of its mention of downloading episodes:

> Taiga is an open-source desktop application for Windows. It automatically detects the episodes you're watching on your computer and synchronizes your progress with online services. It helps you manage your anime library, discover new series, share watched episodes **and download new ones.**

(emphasis added)

Copyright notices can also be handed out in cases such as these as a proxy for other issues. A while back there was a rash of takedown notices sent out to the Twitter accounts of well-known fansubbers for listing screenshots of Funimation anime episodes (but not for the actual fansubbing activities, which are harder to pursue). Though it doesn't make much difference, Funimation didn't order this itself: the companies issuing takedowns on its behalf were operating independently. This is likely a similar situation.

[This article is relevant in general here.](https://www.theguardian.com/technology/2016/may/23/copyright-law-internet-mumsnet?CMP=twt_gu)

I hate to say it, but the simplest thing to do is likely just change the images. In a worst-case scenario, the company could file a claim with Google and get you delisted from the search rankings. Their claim is tenuous at best, but copyright policy leans too far in favour of corporations currently to make the risk worthwhile.

Again: I'm not a lawyer, but those are my thoughts.

**Comment by ConnorKrammer** [comment]
You can also try contacting the company that filed the notices on behalf of the two parties concerned and see where that goes (or contact the parties directly, though in the case of the JCCA that might be tricky), but I'm not sure how often that course of action is successful.

**Comment by Injabie3** [comment]
That's a tough one...Like @ConnorKrammer said, I think it would be the best to just change the images for now, as it's the easiest.  You can think of other solutions afterwards, if that's what you want to do.

**Comment by erengy** [comment]
I contacted DigitalOcean and here's what they said:

```
Hello

Thanks for getting back to us.

If you do not believe this is a valid complaint, you would need to give us a
DMCA counterclaim and possibly resolve this in court at a later time.

After 5 days, if the content is still up, we will have to disable the
networking on the droplet as per DMCA safe harbour rules.

Let us know if you have any other questions or require any further assistance

Best Regards
GD
DigitalOcean Trust & Safety Specialist
```

**Comment by ConnorKrammer** [comment]
<sup>*mutters angrily about DMCA abuse*</sup>

@erengy That's unfortunate. Given how little time 5 days is to get this sorted out, it's probably best to just swap out the images for non-Aniplex and non-JCCA titles (for the latter, they appear to be listed in the right-hand sidebar of their [website](http://www.japancreativecontentsalliance.com/)).

Wish I could help out more, but I'm a bit at a loss of what to do.

**Comment by erengy** [comment]
I've removed the screenshots from my server and uploaded them to Imgur instead. `¯\_(ツ)_/¯`

DigitalOcean support told me that I can now consider the case resolved, unless they find another image to file a claim on. They also confirmed that my droplet is no longer at risk of being disabled.

Now we wait for the day someone sends us a copyright infringement notice about the Taiga icon. :tiger:
