### ISSUE TITLE
Make file category element consistent with the UI

### ISSUE THREAD

**Issue by otvenharom** [erengy/taiga#272]
![dsdgdfgfds](https://cloud.githubusercontent.com/assets/5750392/15884331/0c2cff4e-2d50-11e6-8e6b-91b03d803792.PNG)
I have batch releases set to hide, and as you can see, it's the first filter to be processed. And yet, some releases still get automatically downloaded.

**Comment by erengy** [comment]
The *File category* element in torrent filters corresponds to the value provided by the RSS feed:

```xml
<item>
  <category>Batch</category>
  (...)
</item>
```

However, as far as I know, only Tokyo Toshokan provides the "Batch" category. Taiga [goes beyond this value](https://github.com/erengy/taiga/blob/64bde3bc8485a65e79b0625db4dbed4fc6b27466/src/track/feed.cpp#L93-L111) to decide whether a torrent is a batch release or not; the resulting category is then displayed on the user interface, but it doesn't affect the filtering process.

For now, you could do something like [this](https://twitter.com/taigaapp/status/716472914451816449) to have a slightly more reliable filter. But I'm planning to make things so that what you see is more consistent with what you get.
