### ISSUE TITLE
Crash on parsing empty HTTP header value

### ISSUE THREAD

**Issue by zertap** [erengy/taiga#273]
Win10, Taiga 1.2.3
Crashes right after launching. Tried with clean re-install too.
Hasn't done this before. Log doesn't display errors and debug didn't seem to contain anything useful either.

**Comment by kanadakid** [comment]
I'm having the same issue. In my case, Taiga was working fine until I manually asked it to check for updates. It reported that no updates were found, and crashed right afterwards. Now it crashes any time I try to start it up again.

I'm running Taiga 1.2.3 on Windows 7 64-bit.

**Comment by ItaloKnox** [comment]
Same thing here, it was working fine before. Maybe something buggy with MAL's API?

**Comment by erengy** [comment]
In case it's related to #270 and #271, could you try the [latest build](http://taiga.moe/latest.html)?

**Comment by ItaloKnox** [comment]
No dice. MPC wasn't running and I didn't update it (or KCP) recently.
The latest build also crashes right after it starts downloading my list.

**Comment by jeremyedert** [comment]
Same problem here. Win10, with Taiga 1.2.3. Taiga crashes when checking for updates.

**Comment by erengy** [comment]
Looks like GitHub started responding with an `X-Geo-Block-List:\r\n` header, and [this line](https://github.com/erengy/taiga/blob/64bde3bc8485a65e79b0625db4dbed4fc6b27466/src/base/http_response.cpp#L41) is unable to handle the empty value. For now, I changed the update feed so that the anime relations file is downloaded from Taiga's server rather than GitHub.

**Comment by ItaloKnox** [comment]
Works fine now, opened Taiga and messed around for a while. No crashes.
Thanks!
