### ISSUE TITLE
How do i set up format string?

### ISSUE THREAD

**Issue by inounakade** [erengy/taiga#274]
I would like some help on setting up the format string to only update when i finish an anime series with the total episode count and url. I had a working string which used to do that, until i format my pc. 

I was using this one but it just annoyed my followers. (http://i.imgur.com/q9mnOQr.png)

**Comment by erengy** [comment]
This is the default format string for Twitter, which will post a tweet only when you watch the last episode of an anime:

    $ifequal(%episode%,%total%,Just completed: %title%$if(%score%, (Score: %score%)) %animeurl%)

Here's how it looks without the score part, if you don't need that:

    $ifequal(%episode%,%total%,Just completed: %title% %animeurl%)

When `%episode%` is equal to `%total%`, this will output `Just completed: %title% %animeurl%`. Otherwise it will output nothing, which basically means "don't tweet anything".

**Comment by inounakade** [comment]
I see, thank you so much. I been using taiga for years now. And never got the hang of the format string.
