### ISSUE TITLE
Scrape new season data directly rather than update manually

### ISSUE THREAD

**Issue by tactidact** [erengy/taiga#276]
As I understand the situation, currently data for new seasons is added manually through version updates. Is there anyway to automate this process? My thoughts were that it might be as simple as scraping [this](http://myanimelist.net/anime/season/2016/summer) page if we consider let's say Summer 2016 for the series that are linked on it, searching for them through taiga and compiling automatically an xml file of the like that I presume is released with such version updates.

I think this should work at least for the MAL case, though I am unfamiliar with Hummingbird. I'm actually a bit surprised that there isn't a straight forward implementation of this in the APIs (Perhaps there is, but I haven't bothered to check).

Sorry if I wasn't descriptive enough, my experience really lies in low level C and C++ stuff so I am completely lost with this kind of stuff. I am willing to help if need be though.

**Comment by erengy** [comment]
The process is already automated to some extent (see #244).

As a rule of thumb, it's best to avoid scraping HTML pages as much as possible. Their structures change all the time, without prior notice. If the code that scrapes anime season data was a part of Taiga itself, we would have to update the application executable in order to keep up with the changes, which defeats the purpose.

There are other reasons too, such as the fact that scraping the pages once and distributing the data is more efficient in terms of HTTP requests. All in all, I think that it's not a good idea to make Taiga scrape *any* HTML page directly.
