### ISSUE TITLE
Issue with identifying media, and potential solution

### ISSUE THREAD

**Issue by Qwerty-Space** [erengy/taiga#277]
Hello,

I have an issue where Taiga won't always detect the video I'm watching, I know others have this problem as well.  And I have a potential solution:

First, go to the anime list in Taiga, find the anime, right click > set file > then choose the correct file for that OVA or series.  I imagine that a series would be a bit more difficult, because it has to figure out the rest of the names from the name of the file you chose.

Alternatively when a video is playing, go into the list right click > set as now playing

Thanks!

![image](https://cloud.githubusercontent.com/assets/6967592/16388425/0a0fa8e2-3c91-11e6-8217-6fb0bf249f5c.png)

**Comment by CRS-ECHO51** [comment]
You should have the anime that you watch listed on your library or update the anime seasonal list.

**Comment by Qwerty-Space** [comment]
What do you mean?
It was in my "plan to watch" list on MAL, and downloaded onto my computer in the Videos library.

**Comment by erengy** [comment]
The problem here is that the filename says it's the 11th episode of *Kono Subarashii Sekai ni Shukufuku wo!*, where the series has only 10 episodes.

This kind of issues are resolved by adding a redirection to [`anime_relations.txt`](https://github.com/erengy/taiga/blob/master/data/db/anime_relations.txt). In this case, the 11th episode of the series needs to be redirected to the 1st episode of [the OVA](http://myanimelist.net/anime/32380/).

I've made the necessary update in b835ae571fb7a03681a6e317962728ee84e11890, so I'll close this issue now.

**Comment by Qwerty-Space** [comment]
Thanks @erengy!
Does the anime_relations.txt get updated with each new version of Taiga?

**Comment by erengy** [comment]
If you have the *Check for application updates* option enabled at *Settings* → *Application* → *General*, the file will be automatically updated at startup.

Otherwise you can hit *Help* → *Check for updates* manually. Taiga will report that there are no application updates available, but it will silently download the new `anime_relations.txt` in the background.

**Comment by Qwerty-Space** [comment]
Okay, thanks.
