### ISSUE TITLE
Vivaldi Web Browser Support

### ISSUE THREAD

**Issue by beesenpai** [erengy/taiga#278]
Would it be possible to support Vivaldi for media recognition in a future release?

**Comment by erengy** [comment]
I recently looked into this at erengy/anisthesia#2. Unfortunately, it's currently not possible to detect the URL and the tabs of the Vivaldi web browser.

**Comment by Fischmiep** [comment]
I would love to see this as well so I took a look. It seems like Vivaldi shows up as a window in the UIA Tree and uses the title of the currently active tab as the window name (according to Inspect).

I've never worked with UIA before so I have no idea whether or not it's possible to work with that but maybe it's possible to parse the necessary information from that?

**Comment by erengy** [comment]
Just checked Vivaldi 1.14.1077.60 in case something's changed since the last time I tried (1.10.867.48). It's still the same, though. While the window itself is available in the UIA tree, its descendants are not. Taiga reads the URL bar and the tabs for proper detection, which Vivaldi doesn't provide.

**Comment by WizardLink** [comment]
Couldn't you open a thread in the forum? I mean, it is a blind shot... But I know the Vivaldi users which use Taiga would support that thread. Specially because I have seen other developers asking for that information to be provided. Of course, it is just a possibility, but I still look forward seeing a Vivaldi support whenever it is possible.

**Comment by PESER** [comment]
I would love that, that's very unfortunate that it's not possible. But honestly the comments are from 2 years ago, Maybe something has changed since then.

**Comment by wizardlink** [comment]
@PESER, knowing Vivaldi... It probably has not; unfortunately. I have made a complete switch back to Firefox and I am happier than ever with my experience using it.
