### ISSUE TITLE
[Help] Can't Figure Out Torrent Filter

### ISSUE THREAD

**Issue by Adyel** [erengy/taiga#285]
# Hello Everyone,

I'm using Taiga for a while. I normally download Anime from different sites and watch them later. But downloading single file at a time is very annoying so I thought I should automate this process. I knew there is a feature in Taiga that supports automated downloading. I Added a custom rule See Screentshot 
![taiga](https://cloud.githubusercontent.com/assets/4653623/17079931/9f36092a-5140-11e6-91d8-29ea9cbbd432.PNG)
 
Other Settings are same as default except I unchecked "Download High Res" option
![capture4](https://cloud.githubusercontent.com/assets/4653623/17079934/d26934c0-5140-11e6-8979-22caa0b2c841.PNG)

But No Filters aren't working. No Files are Selected and There are many Resolution beside 480P and many Anime series are showing which are not on my Plan to watch list. What am I doing wrong ? Can anyone help me ?
![taiga 02](https://cloud.githubusercontent.com/assets/4653623/17079943/2a0cc1e2-5141-11e6-8b81-844e41b11a4b.PNG)

NB: I need 480P because I'm running out of space. I have already 700 GB+ Anime.

**Comment by Shinigami27** [comment]
Resolutions other then 480p are showing because you haven't said to hide them, you've just said to only tick 480p.

Here's a filter I have for 720p that just hides everything that isn't 720p.
![image](https://cloud.githubusercontent.com/assets/18045126/17081108/661cc37e-518e-11e6-9184-52814084ade7.png)

The reason that nothing is showing up (and correct me if I'm wrong) to be checked by your filter is because the  [Check new torrents] button that counts down only applies to the top RSS feed in the image which only remembers latest torrents out. You have to manually search to use the 2nd RSS feed which is when your filter will find and tick the ones you want (hopefully).
![image](https://cloud.githubusercontent.com/assets/18045126/17081114/bf04b992-518e-11e6-903d-adcade7ea455.png)

**Comment by Adyel** [comment]
It's a bit late now but thanks for your Replay. Now I know I can't download old Anime from Taiga :+1:
