### ISSUE TITLE
.ogm Video not detected

### ISSUE THREAD

**Issue by CRS-ECHO51** [erengy/taiga#290]
I try every video with extension .ogm and it seems Taiga doesn't detect the format.

**Comment by erengy** [comment]
Taiga does [support](https://github.com/erengy/anitomy/blob/577070c6dfc5c88a35d5b60ca0e20eb5a79a7cda/anitomy/keyword.cpp#L71-L73) .ogm files. I just tried playing a video with .ogm extension, and Taiga was able to detect the file.

In case your issue is related to something else, could you give an example filename that Taiga is unable to detect? You could also try renaming a random .mkv file to .ogm and see if that causes the same issue.
