### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by kirbymaster101** [erengy/taiga#304]
have like a dark theme option so its easy on the eyes.

**Comment by erengy** [comment]
Sorry, I have no plans for themes. Not until after v2.0, at least.

If you're okay with *everything* being dark rather than just Taiga, it's possible to make it look like [this](https://myanimelist.net/forum/?topicid=214500&show=490#msg43739691) by changing your Windows theme:

![](https://i.imgur.com/P2PIU6E.png)
