### ISSUE TITLE
Dark skin/theme

### ISSUE THREAD

**Issue by Antisocialoli** [erengy/taiga#320]
hello, I'm a huge fan of the app and I am not sure im on the right section because I created github account just to request if you guys can add a dark theme for the app? watching anime is best in dark room but with such brightness its hard to use the app, please consider ♥
Thank you so much for making this!

**Comment by erengy** [comment]
Hi there @Antisocialoli, and welcome to GitHub.

This has been requested a few times in the past years (most recently in #304), but there are currently no plans to add themes to Taiga. In fact, I won't be making any significant changes on the UI until v2.0.

If you're okay with *everything* being dark rather than just Taiga, it's possible to make it look like [this](https://myanimelist.net/forum/?topicid=214500&show=490#msg43739691) by changing your Windows theme, though:

![](https://i.imgur.com/P2PIU6E.png)
