### ISSUE TITLE
Setting download location doesn't work.

### ISSUE THREAD

**Issue by prodigyinspired** [erengy/taiga#324]
Ticking all the boxes in download location still forces me to manually set every episode's download location in deluge. I'm using deluge as a daemon (non-classic).

I set my "use this folder instead" to D:\Anime, then the subfolders are anime titles which each anime is specified. Automatic downloading prompts deluge, then sets the download location to my default, which is F:.

**Comment by lordage** [comment]
well as a utorrent user this may not apply but turn your deluge folder control off and set them up in taiga. 

ie look in deluge for an option upon completion move to. turn that off and use taiga to set the folders up.

look here https://github.com/erengy/taiga/issues/229

**Comment by prodigyinspired** [comment]
That's already off.

It's odd since pre-update it was working perfectly fine. Taiga already detects the anime and have the anime folders set.

**Comment by prodigyinspired** [comment]
# @lordage

That's already off.

It's odd since pre-update it was working perfectly fine. Taiga already detects the anime and have the anime folders set.

**Comment by erengy** [comment]
If the issue is related to 060d1326c051c0cb1118ad012dceb53ce080a5d4, this should help:

1. Select the *Use a custom application* option from *Settings* → *Torrents* → *Downloads* → *BitTorrent client*.
2. Select `deluge-console.exe` (e.g. `C:\Program Files (x86)\Deluge\deluge-console.exe`) as the custom application path.

**Comment by Thrackerzod** [comment]
I apologize for commenting on an ancient, closed thread, but I'm running into this exact same issue now as well. Deluge is not running in Classic Mode, connected to the local daemon, and tell Taiga to download torrents to my D:\Media\Anime folder, and create specified subfolders...but Deluge still downloads to its default directory, D:\Downloads. I've tried updating Deluge, and selecting deluge-console.exe as the target torrent client, but then nothing happens when I attempt to start a torrent from Taiga.
