### ISSUE TITLE
Hummingbird returned an error: Invalid credentials

### ISSUE THREAD

**Issue by Ghostpeach** [erengy/taiga#325]
So I've been trying to figure out why this happened for the first time since I normally use Hummingbird to synchronise with Taiga. I fully restarted my laptop because I felt that it was a bit slow like it normally would do at times. Yet for some reason, I can never make Taiga work again.

It would say, ''**_Hummingbird returned an error: Invalid credentials_**'' at the bottom which is shown in my screenshot. The metadata provider is on ''Hummingbird'' and my login is correct (checked plenty of times) so I don't know what exactly the problem is. I've tried reinstalling it and everything but its still dead to me at the moment. If anyone could help and direct me to try fixing it please, that'd be much appreciated.

![screenshot 2016-10-25 19 47 39](https://cloud.githubusercontent.com/assets/23061546/19699749/6fe3b8d4-9aec-11e6-8f09-8804b706c718.png)

**Comment by erengy** [comment]
Since the error message comes directly from Hummingbird, I'm inclined to think that what it says is true. But of course, it's possible that it happens due to a bug in Taiga or Hummingbird.

If you're absolutely sure that you've entered the correct password, try the following:

1. Temporarily [change](https://hummingbird.me/settings) your Hummingbird password to something simple (e.g. `qwerty`), and then enter the new password to Taiga's *Settings* → *Services* → *Hummingbird*.
2. If that doesn't work, run Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode). After you get the same error, send the `Taiga.log` file to me privately (e.g. upload it to your Dropbox and send the link via an email or a PM).

**Comment by Ghostpeach** [comment]
Late reply because I forgot to check if someone would replied to my post. I might cry, I literally changed the password to something different and Taiga worked again. Thank you so much. I can finally use Taiga again. Should of really thought about changing the password if it was that simple but my mind's always blank.

**Comment by erengy** [comment]
I wonder if Hummingbird too has a bug in their API similar to #170. Did your previous password include punctuation and stuff? Could you post it here, if it's safe (i.e. it wouldn't give away information about your other passwords) to do so?

**Comment by wopian** [comment]
Temporarily changing my password to include various common/obscure punctuation worked fine with Taiga for me.

**Comment by Ghostpeach** [comment]
@erengy Not that I remember, it should of been 11 characters long, that's including 3 numbers. I normally make my password moderate and easy to remember at the same time for Hummingbird. When you told me to change my password, I just made it to ''cakes231'' and Taiga worked again, _thank god_.

**Comment by erengy** [comment]
All right then, I'll consider this issue resolved.
