### ISSUE TITLE
Update failed: The anime is already in the list

### ISSUE THREAD

**Issue by yagamikisuke** [erengy/taiga#328]
![6a8edd92-a158-11e6-93b0-406661df2373](https://cloud.githubusercontent.com/assets/22899343/19954022/3f98e558-a15b-11e6-87af-80d0d09e88ab.png)

I don't know to what this id refers to, but there is no anime with same title in my list.

**Comment by erengy** [comment]
From [what I can see](https://myanimelist.net/animelist/yagamikisuke?status=2), the anime *is* in your list, which is why MyAnimeList returns that error. I imagine that either something went wrong with the MAL server while updating your list, or you'd already added the same anime via the website previously.

In any case, you can delete *[Musaigen no Phantom World Special](https://myanimelist.net/anime/33075)* from the update queue of History page, and then synchronize your list to get rid of the issue.

**Comment by erengy** [comment]
This turned out to be [an error](https://myanimelist.net/forum/?topicid=1566170) on MyAnimeList's part.

**Comment by louisch** [comment]
So I'm guessing that now we're waiting for MAL to respond to that thread, because there's a chance they'll revert the API?

**Comment by erengy** [comment]
Exactly. In the meantime, you may use the [latest build](http://taiga.moe/latest.html), which is able to handle the change.

**Comment by louisch** [comment]
Just to give you my own opinion, I don't really mind if I'm forced to update. I'm already using the latest build at this point, which works a treat. I think if the API is better then it would be best to just keep it.

**Comment by Fass-ohne-Hoden** [comment]
Just to make sure - this hasn't been resolved with the recent Taiga update (1.2.5 I think) and still depends on MAL to do whatever on their side? I am asking as the error still occurs and I wasn't sure whether the update had something to do with it.

Best regards and all :)

**Comment by erengy** [comment]
What happened was that MAL API suddenly started giving an unexpected response to Taiga's add-anime-to-list requests. This caused Taiga to interpret the new response as failure, even though MAL actually added the anime to user's list. This issue (the "Created" error) is resolved in v1.2.5. However, if you have an anime in your update queue that gives you the "The anime is already in the list" error, you still need to remove it from History page and re-synchronize. Because, the anime *is* in your list, so the error is appropriate.

**Comment by Fass-ohne-Hoden** [comment]
I see. Thank you very much. This helped. It seems, I had to look a bit longer to find all instances of that anime in my history list (and, well, there was a search window all that time ... I just didn't notice :D )
