### ISSUE TITLE
Fall back to window title for remote file with no handle

### ISSUE THREAD

**Issue by wiiaboo** [erengy/taiga#330]
I want to restrict the file handle recognition to within library folders but still try to recognize every http/https URL properly in f.ex. mpv.

**Comment by erengy** [comment]
Could you elaborate on your use case? In which situation a file handle is a URL? How can I reproduce the issue?

**Comment by wiiaboo** [comment]
A file handle can't be an URL, right. I wanted URLs opened to be recognized by window title if the file handle can't be retrieved. The commit in the PR probably explains what I'm trying to do better than by just words.

**Comment by erengy** [comment]
I've seen the PR, but I won't be able to accept it because I may have to release an update soon to address #328. Also, I'm in the process of extracting all media detection code to a separate library as per #316.

From what I understand, you're streaming anime with mpv, which is why there's no file handle that Taiga can detect. So you want Taiga to be able to identify the anime by mpv's window title instead. Am I correct? If that's the case, I'd like to know how to stream the same way so that I can test this situation myself.

**Comment by wiiaboo** [comment]
`mpv https://i.fsbn.eu/pub/[FDP]%20Detroit%20Metal%20City%20-%2004.mkv` or opening mpv and dragging [some direct link to a media file](https://i.fsbn.eu/pub/[FDP]%20Detroit%20Metal%20City%20-%2004.mkv) to the window.

Pre-#332 behavior:
- downloading the file and opening it inside a library folder works
- downloading the file and opening it outside a library folder ignores the file (this is expected behavior)
- opening the file using the URL fails because GetTitleFromProcessHandle returns true but doesn't set the title because no file handles are valid media files.

Post-#332 behavior:
- <same>
- <same>
- GetTitleFromProcessHandle now returns false due to failing to get the title from any file handle so GetWindowTitle gets a chance to try and get the window title.

**Comment by wiiaboo** [comment]
Seems to be fixed with media-detection branch. Thanks.
