### ISSUE TITLE
Trimming white space in HTTP announce format string.

### ISSUE THREAD

**Issue by ajseavey** [erengy/taiga#347]
I recently ran into an issue with the HTTP announce feature and Monthly.moe where, when I copied the format string provided there (accidentally copying and extra space at the end), I ended up with extra characters on the end which caused the request to fail. Specifically, looking in my settings XML, I ended up with `<http enabled="1" format="token=<removed>&amp;service=myanimelist&amp;id=%id%&amp;watched=%watched%&amp;total=%total%&amp;playstatus=%playstatus%&#13;&#10;" url="https://www.monthly.moe/api/v1/user/library/taiga" />`
My theory is that the `&#13;&#10;` breaks the request. Would these be trimmable white space, or are all characters assumed to be valid format strings?

**Comment by erengy** [comment]
`&#13;&#10;` is `\r\n`, so it's technically a newline rather than whitespace. Currently, they are both allowed in format strings.

This issue should be automatically resolved when we [switch](https://github.com/erengy/taiga/issues/316) to [atf](https://github.com/erengy/atf). The "standard" behavior is to ignore newline characters, unless they are output by `$crlf()`.

That being said, I just tried a couple of times copying the format string provided by Monthly.moe, but it didn't result in a newline being added to the end.

**Comment by Svered** [comment]
It basically only happened because of the way I was copying it. It got cut off on my screen after playstatus=%play, so I used shift + right arrow to select the rest as well as (accidentally) a single extra character, which ended up as the new line.
If this will be fixed in the future then all is well and good, though. Just figured I'd bring this behavior up in case it was unwanted.
