### ISSUE TITLE
Consistent incorrect recognition on Crunchyroll? "Mudai".

### ISSUE THREAD

**Issue by AtomicOtaku** [erengy/taiga#363]
So this has been happening to me a while and I wonder if anyone has the same issue. Whenever I try to watch something on Crunchyroll, when I first open the episode page, Taiga will recognize that I'm watching something called "Mudai" and prepare to update my list with that (MAL page for Mudai: https://myanimelist.net/anime/30771/Mudai). This is definitely never what I'm watching and I have no idea what it is. Once the player itself on the page loads, it usually corrects itself and switches to showing what I'm actually watching (unless I have multiple Chrome windows open, but that's another thing). I'm worried one of these days I'm gonna end up with Mudai in my anime list, and that's not a huge deal, but it is incorrect and a hassle.

Here's a quick video of the process and results: https://puu.sh/ttOPR/a49ac6c012.webm

On the MAL page one of the synonyms for the title is "Untitled", so my theory is that possibly Taiga is setting the title to "Untitled" until the player is loaded and therefore it's pulling up Mudai as the result? It's a possibility and at least something I thought was noteworthy (maybe not).

**Comment by erengy** [comment]
This seems to be a variation of the issue where Taiga briefly detects "Naruto Shippuden, Bleach, Anime Videos and Episodes Free Online", which is the default page title for Crunchyroll. The only difference is that, in your case, Taiga sees "Untitled" as the page title and is able to identify it due to that synonym.

I'll try to fix this while I'm rewriting media detection code (#316).
