### ISSUE TITLE
[Request] Is there anyway we can also see BluRay/BD/BDRip torrent?

### ISSUE THREAD

**Issue by morizuki** [erengy/taiga#367]
Good Day,

I'm not sure if this is the right to request.

I'm fan of your software and all is good. I'm also interested on your Torrent anime release, but I'm a huge fan of BD/BDRip/BluRay Release only. Is there anyway you can integrate this kind of torrent list?

Thanks

**Comment by erengy** [comment]
Hey @morizuki,

The RSS source for torrent releases is customizable via *Settings* → *Torrents* → *Discovery*. The default feed does include BluRay releases already.

As far as I know, there's no RSS feed that only consists of BluRay releases. If you don't need automation, you may manually search *Torrents* page for "BluRay" etc. for the same effect.

Otherwise, you may add an appropriate filter via *Settings* → *Torrents* → *Filters* to make Taiga ignore non-BluRay releases. Here's an example filter, although not 100% reliable:

![bluray-filter](https://cloud.githubusercontent.com/assets/1078430/22257459/ce78b040-e266-11e6-8a51-5c0d550813d8.png)

**Comment by morizuki** [comment]
Oh yeah, I tried using the filter after posting this request, but it seems I didn't get it. Thanks for giving me an example of it. I really appreaciate it.

**Comment by morizuki** [comment]
Oh btw.. @erengy Is it possible to Match Case the BD? I'm seeing some release that have BD but it is on the CRC.

**Comment by erengy** [comment]
Sorry, there's currently no filter element for the video source. Some false positives are to be expected when you search the entire filename. That said, you could do something like this to get somewhat better results:

- File name | does not contain | `[BD]`
- File name | does not contain | `BD ` *(there's a single space at the end)*
- File name | does not contain | `BD_`
- File name | does not contain | `BD,`
- File name | does not contain | `BDRip`
- File name | does not contain | `BluRay`
- File name | does not contain | `Blu-Ray`

**Comment by morizuki** [comment]
Oh that's very convinient. Thanks so much
