### ISSUE TITLE
Taiga not recognizing Little Witch Academia (TV) episode 1 in library folder

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#379]
I really have no idea as to what it actually thinks it is. It is not recognized as the movie or the TV series. It fails to recognize releases from both groups actively releasing it.

[eraser] Little Witch Academia - 01 [4586E154].mkv
[Asenshi] Little Witch Academia - 01 [6A9D1E5C].mkv

Screenshot: https://my.mixtape.moe/gvijef.png

v1.2.5

**Comment by erengy** [comment]
It's because `Little Witch Academia - 01` is ambiguous. It can refer to either the 1st episode of the TV series, or the movie. Taiga cannot know for sure without user input. There is no ambiguity for the 2nd episode and onward, because the movie consists of a single episode.

This is a general issue that happens when there are multiple anime with the same (normalized) name. It's also seen between some OVAs and TV series (as it's likely the case with #377), and even between two different TV series (e.g. *White Album 2nd Season* and *White Album 2*).

In this case, you need to add `Little Witch Academia` as an alternative title to the TV series to resolve the ambiguity. In fact, if you played the episode, Taiga would ask you just that in its Now Playing dialog.
