### ISSUE TITLE
Close/minimize the main window on Esc

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#392]
I find it useful to close the main window by pressing `Esc` key (Taiga is set to hide in shell tray in options).

Currently I use this code in my AutoHotKey script:

```
#ifWinActive ahk_class TaigaMainW
  Esc::winMinimize
#ifWinActive
```

**Comment by erengy** [comment]
<kbd>Enter</kbd> and <kbd>Esc</kbd> are the access keys to OK and Cancel buttons by default. But this is only the case in secondary windows. These keys are almost never used this way in the primary window of an application. In other words, <kbd>Esc</kbd> key is used to cancel an ongoing operation or dismiss a dialog box, rather than closing or minimizing an entire application.

Note: You may use #82 for other suggestions regarding keyboard shortcuts.

**Comment by tophf** [comment]
Yeah,  I know about Esc being an op canceler, but it's useful in some similar programs that pop up a small helper window like Taiga.

**Comment by erengy** [comment]
Taiga's main window is not really a "small helper window", though. It's a full-fledged application window with a menu bar, status bar, child windows and such.

Besides, the <kbd>Esc</kbd> key already has other uses: It clears the filter/search box, and takes the focus out of the menu bar when required. I imagine that closing the application when the key is pressed would cause more accidents than the occasional convenience it provides.

I'm closing this issue because I'm against the idea of making this the default behavior or providing a separate option for it. But perhaps this function can be added when the keyboard shortcuts become customizable.

**Comment by tophf** [comment]
Well, I'm fine with my workaround.

BTW, by a full-fledged application I usually mean something like Photoshop :-) Taiga is more like a language reference or dictionary lookup. Also, handling currently focused control when Esc is pressed is trivial if needed.
