### ISSUE TITLE
Transitioning from Hummingbird to Kitsu

### ISSUE THREAD

**Issue by FireFistAce42** [erengy/taiga#393]
Hey guys. This might be the wrong place to post and if so please delete. Im trying to transition from hummingbird to Kitsu. So far I have only changed the URL and now I am getting JSON errors. Could anyone help me with this?

**Comment by erengy** [comment]
Hi there. Could you explain what you mean by transitioning from Hummingbird to Kitsu? Which URL did you change? What errors do you get?

**Comment by FireFistAce42** [comment]
I went from this "https://hummingbird.me/api/v1/search/anime/?query=" to "https://kitsu.io/api/edge/anime?filter[text]=" and here is the problem I have "Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'DiscordBot.HummingbirdModule+Anime[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'data', line 1, position 8." 

Im just not quite sure how to change it properly as I dont use JSON much so Im not too familiar with it.

**Comment by erengy** [comment]
Kitsu's API is different than Hummingbird's. Changing the URL won't be enough. In this case, the new endpoint returns an object rather than an array:

```json
{ 
  "data": [],
  "meta": {},
  "links": {}
}
```

Here, search results would be located in the `data` array, so you'd need to parse that instead. Of course, the contents of each anime object are different from Hummingbird's too.

This is not quite the right place to seek general help regarding Kitsu API, so I'll be closing this issue. To get more information, [this thread](https://forums.hummingbird.me/t/kitsu-api-documentation/33367) might be a good start.
