### ISSUE TITLE
Doesn't suport custom Windows themes.

### ISSUE THREAD

**Issue by ignacy0109** [erengy/taiga#398]
![taiga](https://cloud.githubusercontent.com/assets/12091425/25064518/0fb49216-21fc-11e7-89f3-1cfbff77d8d5.jpg)

Steps to replicate: Just install any dark theme on Windows to see how hideous it gets.
Preferred solution: Either make Taiga completely ignore the Windows theme (set all colours) or make it take all colours from Windows theme.

**Comment by erengy** [comment]
Taiga does support custom Windows themes. There are only a few places (such as Seasons page) where Taiga uses pre-defined colors, everything else comes from Windows. The background is not supposed to look that way, unless there's something wrong with the theme itself.

Did you restart Taiga and/or Windows after changing the theme? If a restart doesn't fix it, please give me a link to the theme so that I can try to reproduce the issue.

**Comment by ignacy0109** [comment]
Sorry man, I'm retarded. I thought that if some part of the theme got applied then applying a theme doesn't require a restart.
Obviously a restart fixed it though.
Sorry for wasting your time.
