### ISSUE TITLE
Torrents keep downloading

### ISSUE THREAD

**Issue by seantc** [erengy/taiga#399]
Previously when a new torrent came out Taiga would just download it and that would be it, but since a few weeks ago it has been downloading every version of a torrent instead of just one. I don't recall changing anything, but it seems as if there's no check whether or not the torrent has been downloaded already? Did I do something wrong?

So to make it a bit more coherent: before, Taiga would download lets say [A]x-anime, and that would be anything from x-anime that would be downloaded, whereas now it will not only download [A], but also [B], [C], [D], [A]x-anime 1.2, etc.
![image](https://cloud.githubusercontent.com/assets/17458694/25066021/d7e0c0a2-221a-11e7-9f53-f9073ee939d7.png)

**Comment by erengy** [comment]
It all depends on your torrent filters. There's no default filter that prevents downloading multiple releases of an episode from different fansub groups. You need to set up some filters for that.

If you do have fansub group preference filters but keep having issues, please export your filters from *Settings → Torrents → Filters* so that I can import and examine them.

**Comment by seantc** [comment]
[Filters](https://hastebin.com/ocojoluqac.m)
Looking at it now, would it just be a simple matter of moving fansubs over 720p? If so I'm gonna be really sorry for wasting your time....

**Comment by erengy** [comment]
Your "[Fansub] Anime" filter is a general preference filter, so it discards releases from other fansub groups *if* a HorribleSubs release is available. Otherwise it does nothing and Taiga will download releases from other groups. If you don't want that, you may change the filter to:

```
Condition: Episode fansub group | is not | HorribleSubs
Action: Discard matched items
```

Looks like you changed "Discard watched and available episodes" filter's matching to "All conditions". Was that intentional? The default is "Any condition", which should work better in general. If you go back to the default one, you won't need the "watched" filter either.

Since you already have the "not 720" filter, you should disable the "720" one (it doesn't have any effect at the moment).

**Comment by seantc** [comment]
Thanks!
