### ISSUE TITLE
Flexible regex / urls for browser detections

### ISSUE THREAD

**Issue by ToastyStoemp** [erengy/taiga#401]
https://github.com/erengy/taiga/blob/39a90c0d35f422e4a4617290daba4e0c6f836f90/src/track/media_stream.cpp#L405

Allowing us to easily customized the regex and or let us set a path for the web applications.
my plex server runs on a sub domain.

**Comment by erengy** [comment]
Just to make sure I understood this correctly: You're using a personal domain like `plex.example.com` instead of the default `localhost`, `127.0.0.1:32400` or `plex.tv` that Taiga supports, right?

I can probably add this as an advanced setting, but I'd like to make sure that it cannot be abused to make Taiga detect unofficial streaming sites.

Another possible solution would be to forget about customization and support all URLs that include a `plex` subdomain (e.g. `plex.example.com`) or path (e.g. `example.com/plex`). Would this cover your use case?

**Comment by ToastyStoemp** [comment]
This would indeed cover my case
