### ISSUE TITLE
Consider putting the current 1.3.0-alpha to the release section

### ISSUE THREAD

**Issue by Cephel** [erengy/taiga#402]
Right now you have to dig through issue comments to find the working version. Since the beta release might take a bit longer, I think you should provide a proper download and mark it as "pre-release".

**Comment by erengy** [comment]
The digging part is intentional, because the latest build is not supposed to be downloaded by regular users. I don't want to encourage people by providing a setup file or making the download link easier to find.

I normally don't update the latest build unless I want to give it out to a specific person for testing purposes. The current phase has become an exception, where more than a few people wanted to try out Kitsu support.

Overall, I'd like to keep the distinction that v1.3.0-alpha is not an official release. Otherwise I'd provide automatic updates for it, which would be even more convenient than a GitHub release.

**Comment by Cephel** [comment]
I mean I get what you're coming from, but please note that the "old" option for hummingbird is gone, it's nonfunctional, and the client doesn't even tell you as such, it just keeps piling up entries in the history tab ready to be synced.

So users might be led to believe that the project is abandoned

**Comment by erengy** [comment]
v1.3.0-beta is now available:
https://github.com/erengy/taiga/releases/tag/v1.3.0-beta
