### ISSUE TITLE
Open folder in associated app

### ISSUE THREAD

**Issue by koteq** [erengy/taiga#406]
Currently "Open folder" opens "File Explorer" app. But I would like it to open "Total Commander" as I have [configured](http://www.ghisler.ch/wiki/index.php/Explorer_integration#Windows_7). For example qBittorrent [supports it that way](https://github.com/qbittorrent/qBittorrent/blob/ead1f6e1f6fa9b294306c0b74486117b216c697a/src/base/utils/misc.cpp#L597-L604).

Also it may be handy to have next or last episode file selected.

**Comment by erengy** [comment]
Taiga should be opening the folder with the associated application rather than Windows Explorer. Could it be because you modified the registry values in `Drive` and `Directory`, but not in `Folder`? Not sure if `SHOpenFolderAndSelectItems` would behave differently than `ShellExecute` in this case.

We can indeed use `SHOpenFolderAndSelectItems` to select the next episode after opening the anime folder. I added this in f0a04044ae9a415b493a70aac0ae9b97083436a8 now. But we cannot use it when the next episode is not available, because it would then open the parent folder rather than the anime folder, I think.

**Comment by koteq** [comment]
> Taiga should be opening the folder with the associated application rather than Windows Explorer.

You're right. Taiga uses [ShellExecute "open"](https://github.com/erengy/taiga/blob/f0a04044ae9a415b493a70aac0ae9b97083436a8/src/base/file.cpp#L136) but I was silly enough to name the key in a wrong way. I fixed it and it works as it should.

Anyway `SHOpenFolderAndSelectItems` functionary should be good enough to keep it.
