### ISSUE TITLE
Invalid page value issue.

### ISSUE THREAD

**Issue by ovingiv** [erengy/taiga#412]
Hello. I've received an issue when I attempt to resync my list from Kitsu and it gives me the following issue.
"Invalid Page Value: Limit exceeds maximum page size of 500."

I am using the alpha build. Issue is on both Windows 7 Pro and Windows 10 Home (both 64Bit).

If there is any other information needed, simply let me know and I'll post as soon as I can.

**Comment by erengy** [comment]
I'm getting the same error message now. It seems to be caused by a recent change on the server, namely hummingbird-me/hummingbird-server@e49958c72bf7b65897b24109d6c30058f672a469. /cc @NuckChorris

Taiga tries to retrieve the entire library in a single request by [setting the page limit](https://github.com/erengy/taiga/blob/f0a04044ae9a415b493a70aac0ae9b97083436a8/src/sync/kitsu.cpp#L156-L160) to `100000`. Using pagination doesn't make sense for Taiga, but I'll do that if I have to.

**Comment by ovingiv** [comment]
Doesn't the setting in Taiga "Download only a partial library" do anything anymore?

**Comment by wopian** [comment]
Large limits will cause the server to 503 - i.e a little over 2000 = 💀

**Comment by erengy** [comment]
> Doesn't the setting in Taiga "Download only a partial library" do anything anymore?

It still works, or at least supposed to. But that option is, for the most part, unrelated to this issue. When it's enabled, Taiga requests only the most recent library entries when possible, using `filter[since]`. This issue, on the other hand, is related to the `page[limit]` of the results. Basically, Taiga asks for everything, but Kitsu says "I can't give you more than 500 at once".

**Comment by ovingiv** [comment]
> It still works, or at least supposed to. But that option is, for the most part, unrelated to this issue. When it's enabled, Taiga requests only the most recent library entries when possible, using filter[since]. This issue, on the other hand, is related to the page[limit] of the results. Basically, Taiga asks for everything, but Kitsu says "I can't give you more than 500 at once".

So RIP to those who have a library larger than 500 for now...

**Comment by ShaunV2** [comment]
My total anime count is 976 (if the Statistics is correct) so I definitely have over 500 entries in my anime library.

**Comment by ovingiv** [comment]
The issue for me and erengy has started earlier today. I haven't had the issue until today.

**Comment by wopian** [comment]
The solution (& ideal way) is to just chain requests, i.e `page[limit]=500&page[offset]=0` -> `page[limit]=500&page[offset]=500` until there's no `links: { next: '' }`

**Comment by erengy** [comment]
I have some pagination code stashed in my local repository, from the time when @wopian first complained about the issue with large libraries. I'll try and see if it still works.

**Comment by erengy** [comment]
If you're having this issue, please re-download the [latest build](http://taiga.moe/latest.html) and try it out.

**Comment by ovingiv** [comment]
?

**Comment by lunyx** [comment]
I just tried the latest build and I get to downloading list with size next to it before it crashes.

**Comment by erengy** [comment]
@lunyx That's due to a different issue in Kitsu's database. Specifically, the server returns an invalid value for the synonyms of [Detective Conan](https://kitsu.io/anime/detective-conan) (and perhaps for some other series too). I reported it to Kitsu devs and added a countermeasure in ca3c916734b8513658a4486323ab4a789e580612 now. Re-downloading the latest build should fix the issue for you.

**Comment by lunyx** [comment]
@erengy I only put it here because this was the original issue I received and occurred as part of downloading the recommended build here.  Thanks for the fix, I'll check it tonight.

**Comment by Kusaha** [comment]
@erengy I'm having the same issue that lunyx had, once taiga starts to sync the Kitsu anime list it just crashes.

**Comment by erengy** [comment]
@Kusaha Yours seems to be another issue related to R18 media being hidden. I'll report it to Kitsu devs now. In the meantime, you can go to your [Profile](https://kitsu.io/settings/profile) and select Show Adult Content option to avoid the crash.
