### ISSUE TITLE
Taiga no longer recongnizes Firefox

### ISSUE THREAD

**Issue by RyanSpencer** [erengy/taiga#418]
Running on version 1.3.0 alpha right now but the problem was the same on 1.2.5 as well. No matter what website I'm on, it won't recognize anything being played. It recognizes almost immediately with chrome however.. Running version 53 of Firefox if it matters.

**Comment by wiiaboo** [comment]
Maybe some issue related to e10s?

**Comment by erengy** [comment]
[Anisthesia](https://github.com/erengy/anisthesia) is able to detect the latest Firefox. This issue is going to be fixed automatically once Taiga makes use of the library.

If I remember correctly, the issue was related to changed [properties](https://msdn.microsoft.com/en-us/library/dd319579(v=vs.85).aspx) of the address bar.
