### ISSUE TITLE
HTTP Request doesn't send everything on update.

### ISSUE THREAD

**Issue by Moravuscz** [erengy/taiga#425]
So I wrote a little script to keep an online log of episodes recently seen that works with MySQL that only inserts into table if the status is set to "updated". And a second one to fetch the last 5 and show them on my web. It's quite similar in looks to the signature you can make on MAL.

I noticed that Taiga sends HTTP requests on "playing", stopped and "updated".
Both playing and stopped send all the data that is shown in the preview when editing the request contents, but updated only sends id, anime title, episode, episode total and score. No group, no video or audio terms, no resolution.

Is this intentional? What could I do to get all the data but only insert if status is "updated".

**Comment by erengy** [comment]
> No group, no video or audio terms, no resolution.

This happens because, when the HTTP request is triggered with an `updated` status, the relevant function of Taiga is unaware of those information. Fixing this issue properly requires me to do quite some work, which is currently planned for v1.4.

I'm closing this issue because we already have #94, but feel free to comment on either issue.

**Comment by Moravuscz** [comment]
Ah, I see.
I shall make my script work with middle-stages as well then.
Might as well make a "watching right now" thingy on my web.
Thanks for explaining.

**Comment by Moravuscz** [comment]
I believe that sending HTTP request with "updated" should happen only if you click Update when prompted.
For some reason, it happens even without me confirming it. Is that intentional as well or is that one a bug?
