### ISSUE TITLE
Support for Recognition of anime playing on Plex

### ISSUE THREAD

**Issue by vruss** [erengy/taiga#426]
I don't know if this is easily implemented but it would be really great if it was possible to do.

**Comment by erengy** [comment]
Taiga already supports the web application of Plex (see *Settings → Recognition → Streaming media*).

If you mean Plex Media Player, we have an open issue for that at #115.

**Comment by vruss** [comment]
Oh really? When was this implemeted? I tried this a few months ago and it didn't work

**Comment by Diablofan** [comment]
You have to enable it, plus you can only use it in a browser. Streaming to
the Plex threater app I assume is unsupported, much as the uwp windows app
and streaming to other devices.

**Comment by erengy** [comment]
Plex Web App has been supported since 26105e234c61b4f2ba7373e78de795820692ab38, which is more than two years ago. If it's not being detected for you, yours might be a different issue. In that case, please provide more information on your use case, and try out other supported providers such as Crunchyroll to see if they're being detected or not.

**Comment by vruss** [comment]
Oh it I had it disabled haha. Thanks for the help
