### ISSUE TITLE
Taiga not recognizing some files in a folder

### ISSUE THREAD

**Issue by TheInfamousAlk** [erengy/taiga#430]
![ss 2017-06-10 at 12 26 06](https://user-images.githubusercontent.com/29339124/27004936-a2e703b8-4dd8-11e7-9bf1-d3eca3ad2219.jpg)

See JoJo's Bizarre Adventure towards the bottom of my list. Episodes 2-6 are not being recognized, but you can clearly see the episodes in the folder to the left, with the same naming scheme as the others that are being recognized. Yes, I have made it scan again for new episodes, multiple times. I have not specified a different folder in Taiga for this anime. There are no other folders for this anime in Z:\Anime, with either the same or different names. I don't think I'm doing anything wrong, but let me know if I am.

**Comment by tophf** [comment]
ep 1 is recognized because you probably manually selected the correct show from the list suggested by Taiga.
ep 2-6 aren't recognized due to ambiguity with the identically named 6-episode OVA.

That being said, Taiga can certainly be smarter at least in this case of sequentially numbered episodes that overlap or border the ambiguous range.

**Comment by TheInfamousAlk** [comment]
I don't remember if I manually selected #1 from the list, as I watched it weeks ago. But you're probably right. It's unfortunate that the problem is caused by identically named OVA episodes. 

I'll leave this issue open unless I'm told otherwise; maybe they can implement a solution to manually distinguish identically named shows without simply not recognizing them.

**Comment by erengy** [comment]
Quoting from the [FAQ page](http://taiga.moe/#support):

> When there are multiple matches that are equally likely, or when there are no direct matches, recognition fails. In these cases, Taiga displays a list of similar titles on the Now Playing page. You can click on a title to add the current title as an alternative title for that anime, after which it will be recognized. In other cases, you may need to manually add alternative titles via the Anime Information dialog. This is the primary method for resolving recognition issues.

This is indeed what you see when you play one of the unidentified episodes:

![jojo-unidentified](https://user-images.githubusercontent.com/1078430/28324290-9f95c356-6be3-11e7-98e8-e1d11fe4b14e.png)

In this case, as @tophf mentioned, episodes 1-6 can be either the [TV series](https://myanimelist.net/anime/14719/) or the [OVA](https://myanimelist.net/anime/666/). There's no ambiguity for episode 7 and onwards, because the OVA has only 6 episodes.

I'm closing this issue, but it's a common problem (e.g. #172, #379) that I intend to solve by making anime recognition context aware in certain scenarios such as this one.
