### ISSUE TITLE
Now playing notification + Virtuawin 

### ISSUE THREAD

**Issue by amezarashi97** [erengy/taiga#438]
Hello Taiga!

What is happening:
Now playing notification will appear each time you switch back (using VirtuaWin) to the virtual desktop where MPC-HC is and it does not seem to matter whether the media is paused/playing or minimized. What does affect this is whether I have minimized all windows on the virtual desktop where I am playing the media.

Expected: 
Notification only appears once and it is when I open the media.

**Comment by amezarashi97** [comment]
Could you please either delete my issue or delete it whatever I don't feel like filling up my issues list with reports I spent hours writing and no one bothered even answering to it. Yes I am angry.

**Comment by Abchrisabc** [comment]
I think this is because of the way how VirtuaWin works, it forces an App to turn into a Background Process (at least this is how I perceive it from Task Manager). Since how a background process doesn't have a window title attached to it (which Taiga will look at when determining what is "Playing") Taiga won't know of anything being played.
