### ISSUE TITLE
HTML5 Fullscreen detection

### ISSUE THREAD

**Issue by wenbei999** [erengy/taiga#445]
On some streaming sites that use HTML5 players, taiga would lose the recognition after expanding to full screen, but it would re-detect once I exit full screen. This does not seem to occur on flash players. Tested on Hidive and Crunchroll. Both Firefox and Chrome

**Comment by wenbei999** [comment]
It seems this is fixed in the latest commit, however there is now noticeable lag on the interface of all html5 videos. I don't mean slow buffers, but rather slow responses when switching full screen and play/pause lag. This also happens on sites where streaming is not tracked by taiga. It goes away if streaming detection is turned off or taiga is closed.

**Comment by erengy** [comment]
In order to retrieve information from web browsers, Taiga acts as a screen reader. Using an accessibility framework called Microsoft UI Automation, it reads the current URL and tabs from web browsers.

The problem is, when the user enables fullscreen mode of an HTML5/Flash player, other graphical interface features are hidden. The address bar and tabs simply don't exist, thus Taiga is unable to read their text.

Taiga gets around this by assuming that previously recognized anime is still playing when the current window title is the same as the previous one. This way it doesn't need to check the URL, which isn't available.

I haven't had time to optimize things before, but today's changes to the [media-detection branch](https://github.com/erengy/taiga/tree/media-detection) should address the performance issue you described.

**Comment by wenbei999** [comment]
Yes it's much better now. Thank you for the explanation on how Taiga works. 

I realize the anisthesia module is still in-progress and I apologize if I'm being too hasty to submit feedback. I just wasn't sure if you already knew or if it was a 'just me' problem.

**Comment by erengy** [comment]
No problem. I was vaguely aware of the issues, but your feedback helped me understand them better.

Note to self: If it ever comes down to it, we may be able to make use of `WS_EX_WINDOWEDGE` style to check if the browser window is in fullscreen mode or not.
