### ISSUE TITLE
Some questions about Taiga :)

### ISSUE THREAD

**Issue by TheMiziko** [erengy/taiga#446]
Hey ! So I have two questions 
- How do filters exactly work when searching for a torrent ? They are quite confusing :D 
- Is there any way to find  or "prefer" episodes with english DUB ? There are some anime I would prefer to download rather than watch it on website like 9aniem or kissanime, or some information if aniem has dubbing aviable ?

**Comment by erengy** [comment]
Hi @TheMiziko,

> How do filters exactly work when searching for a torrent ? They are quite confusing :D

Filters are indeed somewhat hard to grasp. "How do torrent filters work?" section of the [FAQ page](http://taiga.moe/#support) should help you a bit.

Note that filters don't directly affect search results. When you search for something, the RSS feed you chose (e.g. nyaa.si) will return a list of torrents, independent from your filters. Filters are then applied *on this list* to select/discard the torrents.

> Is there any way to find or "prefer" episodes with english DUB ?

If there are specific fansub groups that release dubbed episodes, you may add preference filters targeted toward those groups. Otherwise you can try creating a general filter with conditions such as `File name | contains | "English Dub"` to prefer those.

**Comment by TheMiziko** [comment]
@erengy Thank you for the information ! So, from what I understand after I search for torrent the filters are applied afterwards to the selection ? Seems good enough. 

And unfortunately it doesn't look like nyaa.si has any eng dubbed anime. So I will probably need ot wait for better source or do some more research. But thanks for the info !

**Comment by erengy** [comment]
> it doesn't look like nyaa.si has any eng dubbed anime

They do seem to have dubbed anime, though I don't know if it's what you're looking for:

https://nyaa.si/?f=0&c=1_2&q=dub
https://nyaa.pantsu.cat/search?c=3_5&q=dub
