### ISSUE TITLE
Sharing to Discord

### ISSUE THREAD

**Issue by pascaldulieu** [erengy/taiga#450]
Would it be possible to have a new tab under sharing to allow a user to show what anime and episode they are watching in the playing status area(Game Activity)?

**Comment by gablou** [comment]
You created the need for this feature on my side too.
Sadly seems discord is not too friendly to let you update the status message.
Still on the developer corner I found : 
https://discordapp.com/developers/docs/topics/rich-presence
`Rich Presence allows you to leverage the totally overhauled "Now Playing" section in a Discord user's profile to help people play your game together. `
But
`Rich Presence is currently in a private alpha phase. If you're interested in getting access, apply to our Gamebridge program and mention Rich Presence, and we'll review your application`
I'm pessimistic regarding approval of non-gaming software application.
But still looking good API as you could even change the 'playing' part of the status:
`state is the user's current context. This could be "In Game," "In Queue," "Looking to Play," or any other states you want to denote.`

It's all I can say for now on this topic. I might have missed something.
I might also dig a little more latter on as I think it could be a nice feature.

**Comment by pascaldulieu** [comment]
It seems like people are using rich presence to set what they are playing. [(Post from reddit)](https://www.reddit.com/r/discordapp/comments/6w6t2v/the_bee_movie_but_its_in_a_unique_playing_status/) and if people are doing it and not being told not to then it could be something that could be added to taiga if the devs feel like it

**Comment by Phokopi** [comment]
[https://twitter.com/discordapp/status/928712259945119744](https://twitter.com/discordapp/status/928712259945119744)
[https://discordapp.com/developers/docs/rich-presence/how-to](https://discordapp.com/developers/docs/rich-presence/how-to)
Discord just released Rich Presence for everyone. This can now be added to Taiga if anyone feel like it !

**Comment by Greydus** [comment]
Discord's game object now accept more types, just 2 new types, `` watching `` and `` listening to ``. [More info on the game object](https://discordapp.com/developers/docs/topics/gateway#game-object) [and a thread on reddit](https://redd.it/7cpakk)
![Discord's new presence update][https://i.redd.it/q1zsmvkbdsxz.jpg]

**Comment by gablou** [comment]
I give a try with rich presence but for now I'm quite disappointed.
Here's the result : 
![image](https://user-images.githubusercontent.com/13090374/34746799-b71b299e-f595-11e7-8199-81714691eb8a.png)

For now seems you cannot use what @Greydus report back in this thread. (should be reserved for bot or self-bot, but self bot are discouraged by Discord).

Interesting issues to follow up:
- Allow setting Rich Presence activity types via RPC discordapp/discord-rpc#71
It will let us set status : watching instead of playing

- [Feature Request] Dynamically Set Application name discordapp/discord-rpc#54
It will let replace the discord app name (here taiga status proxy) by the anim name

- Allowing upload of assets via Hash discordapp/discord-rpc#70
It will allow to have an image from the anim instead of one from the app

I suppose some of the items could be achieved via RPC (notably setting status) but need more complex setup/study.

So for now I have a little something that work on top of the http sharing function of Taiga. With some hacks and manual configuration I suppose Someone could emulate final functionality. If people are interested let me know.

Lastly from the network view it seems that @reverie-lu started to have a look into integrating taiga with discord.

**Comment by 0ANIMEFREAK0** [comment]
@gablou 
how did u do it

**Comment by gablou** [comment]
Hi,
I used the taiga http sharing with https://github.com/gablou/taiga-richPresence-proxy. It's a small nodeJS server that will forward taiga http notification to discord API. I will try to write a tuto tomorrow how to use it and what can be setup.

**Comment by gablou** [comment]
@0ANIMEFREAK0 I put in place a [wiki](https://github.com/gablou/taiga-richPresence-proxy/wiki) were you should find some basic doc. Let me know if you struggle with some part (open an Issue ?) so I know where I should explain more in details.

**Comment by andyvorld** [comment]
Just compiled finished playing around with the discord integration,
![capture](https://user-images.githubusercontent.com/24492062/37030572-8384c2c2-218f-11e8-8bd5-2569d0b6e2eb.PNG)

Download the portable version based on v1.3.0-Beta.2 here https://github.com/andyvorld/taiga/releases/tag/v1.3.0-beta.2-Discord

**Comment by 0ANIMEFREAK0** [comment]
![screenshot_12](https://user-images.githubusercontent.com/35454710/37216831-0560e778-23e6-11e8-95f4-7c3d5973a15e.png)
@andyvorld my anime name isnt showing up

**Comment by andyvorld** [comment]
@0ANIMEFREAK0 do you remember the name of the anime you were watching?

**Comment by 0ANIMEFREAK0** [comment]
@andyvorld it was saiki k kusuo s2

**Comment by andyvorld** [comment]
@0ANIMEFREAK0, can you check if it works now with the newest build?

**Comment by 0ANIMEFREAK0** [comment]
@andyvorld it isn't working

**Comment by pascaldulieu** [comment]
@0ANIMEFREAK0 Can you please open this up as a bug on his project page.

**Comment by erengy** [comment]
The problem with Rich Presence is that it's designed for game developers. As some of you pointed out, it doesn't support different activity types, dynamic application names or images yet, so we're stuck with "Playing Taiga" and a generic icon. Not to mention that it requires using the Discord desktop client (i.e. it doesn't work if you open Discord in a regular web browser).

I was planning to wait until v1.4, hoping that Discord's API would improve by then. But there's quite an interest for this feature, and it seems most of you are okay with the limitations mentioned above. So I gave this a try, and was able to integrate [discord-rpc](https://github.com/discordapp/discord-rpc/) into Taiga:

![discord-playing](https://user-images.githubusercontent.com/1078430/37434098-83c34176-27ef-11e8-8267-4fc919887534.png)

I used `smallImageKey` to display the active service (MyAnimeList, Kitsu or AniList). Let me know if you have any other suggestions.

I'll try to finish this up tomorrow and update the latest build for testing.

**Comment by ifonefox** [comment]
I'm not sure if its a good idea to use include the Taiga avatar and the service. The large icon could cause the part of the shows name to be cut off. In addition, there's no way to know the Discord users's MAL/Kitsu/AniList account. Maybe there could be a small/large image toggle in Taiga's advanced settings? 

![Image and no image comparison](https://user-images.githubusercontent.com/517314/37436863-8100557a-27c0-11e8-9814-2127141c17da.png) 
(The left side has a large image, but its just transparent)

In addition, it would be nice if there was an advanced setting to use our own Discord Application Client ID, since there's no dynamic name. This is a pretty niche feature request, so I can understand not wanting to add that complexity to Taiga.

**Comment by erengy** [comment]
You may now test Discord integration by downloading the [latest build](http://taiga.moe/latest.html). Note that you need to enable it from *Settings → Sharing → Discord* (make sure *Tools → Enable auto sharing* is checked too).

**Comment by wopian** [comment]
@ifonefox it displays your username on hover 

![](https://i.imgur.com/A9e5fWK.png)

**Comment by wiiaboo** [comment]
It doesn't update automatically, needs you to explicitly share to Discord, and it doesn't disappear if there's nothing playing, just shows Taiga's window title.

**Comment by erengy** [comment]
Discord support is now merged into `develop` branch. It's going to be available in the next release.

**Comment by CyberiumShadow** [comment]
Just as a side note: the Rich Presence API should support different activity types already. As applications such as Spotify have it as `Listening to Spotify` as shown here 
![image](https://user-images.githubusercontent.com/4259904/38244006-95898216-377c-11e8-812e-010a163d7708.png)

So it should be possible to have it state `Streaming` or `Watching` through the use of OP Codes through the websocket/IPC sockets for Discord.

Proof of this concept can be seen in a Discord Bot's status message where instead of the `playing` activity type. The `watching` activity type is used instead 
![image](https://user-images.githubusercontent.com/4259904/38244423-f80a2106-377d-11e8-906d-da6056217538.png)
