### ISSUE TITLE
Taiga refuses to recognize some episodes

### ISSUE THREAD

**Issue by oplexz** [erengy/taiga#451]
As the title says, taiga refuses to recognize some episodes
I have all (15) episodes of Bakemonogatari
![image](https://user-images.githubusercontent.com/12859907/29489239-bf7d45ae-8524-11e7-83ac-0f6feb871685.png)
But it says I'm missing 1-3 
![image](https://user-images.githubusercontent.com/12859907/29489254-06a59b34-8525-11e7-9a0a-41a91dc94403.png)
🤔

**Comment by erengy** [comment]
Apparently there's another anime named *[Bakemonogatari](https://myanimelist.net/anime/33715/)* in MAL's database. It's an [unapproved entry](https://myanimelist.net/forum/?topicid=1543837), so you can't even add it to your list. Nevertheless, it's confusing Taiga because of the ambiguity of the first three episodes.

There's not much I can do about this, but you may add `Bakemonogatari` as an alternative title for the [15-episode series](https://myanimelist.net/anime/5081/) to resolve the issue on your system (playing one of the first three episodes and choosing the correct title from Now Playing dialog has the same effect). See #430 for a similar issue.
