### ISSUE TITLE
windows 10 available episode bug

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#455]
since i switched from windows 7 to 10. taiga wont show me the new available animes anymore. it does tell me how many new episode are in my libary folder but dont show me witch one like i am used to in windows 7 where i can jsut klick the show and it plays the new episode.

**Comment by erengy** [comment]
Are you referring to the Continue Watching section at Now Playing page?

![now-playing](https://user-images.githubusercontent.com/1078430/29997442-ce24d638-901b-11e7-9317-08a67189f6fb.png)

That list is derived from your local History. If you haven't moved your Taiga installation from your old OS to the new one, then Taiga is no longer aware of your recently-watched episodes. You'll have to watch some episodes first so that Taiga can populate the Continue Watching list from your History.

**Comment by amboris** [comment]
"Are you referring to the Continue Watching section at Now Playing page?" yes

i did a clean windows install and new taiga install and relink my watching folder. i watched some animes and taiga did update the episode count but when i download new/next episode the "continue watching" does not pop up only "you've watched...." and "there are at least X new episodes..."

**Comment by ShaunV2** [comment]
I'm on Windows 10 myself and I do not have this issue at all, it is not a bug either, you likely don't have any history.

**Comment by erengy** [comment]
I'd suggest enabling the following options:

- Library → Folders → Real-time monitor → Detect new files and folders under library folders
- Application → General → Startup → Scan library folders for available episodes

Also make sure that Taiga is aware of the directory where you download the new episodes to. Now Playing page should be updated right after you scan for new episodes.

6f1397a5b6b05a956fa5f50140d568c5a19bc3c4 should make things a bit more intuitive in the future.

**Comment by amboris** [comment]
i am just curios how does current taiga recognise new series first episode when you need a history for it. for the old one i remember after i downloaded it into my folder it shows me there is a new episode of X series even without watch history first because it is the first episode of the series. and for the setting i have it set to not to ignore if epi number is higher.
