### ISSUE TITLE
Button for next and previous season

### ISSUE THREAD

**Issue by crse** [erengy/taiga#470]
Choosing season from dropdown sometimes could be a hassle.
A button for next and previous season would come in handy.

**Comment by Statharas** [comment]
Anilist and MAL have links available for this. Specifically, Anilist has Prequel, Sequel and Adaptation links available as seen at https://anilist.co/anime/21856/BokunoHeroAcademia2

**Comment by erengy** [comment]
@Statharas I think you misunderstood. This issue refers to the Seasons page of Taiga. More specifically, it's about adding new buttons to the toolbar so that it's easier to navigate from one season to another.

**Comment by Statharas** [comment]
@erengy I didn't misunderstand, I said that they have available links on their websites, so they probably have relations on their APIs as well

**Comment by erengy** [comment]
Seasons page of Taiga has nothing to do with anime relations, though. What this issue requests is to add new buttons next to "Winter 2018", so that you can switch to Fall 2017 or Spring 2018 without selecting them from the dropdown menu:

![seasons-toolbar](https://user-images.githubusercontent.com/1078430/36918847-4022298c-1e6c-11e8-89f9-d7942afca4f3.png)

This doesn't require any API. It's simply a matter of UI (hence the label above).

**Comment by Statharas** [comment]
OOOOh, honest mistake. Should've read the description :P

**Comment by inablock** [comment]
@erengy When this will be addressed? I'm using 1.3.1 and the feature is not there.
