### ISSUE TITLE
1.3.0-beta crashes while loading list from Kitsu

### ISSUE THREAD

**Issue by Daiz** [erengy/taiga#473]
Things have been working fine with 1.3.0-beta an Kitsu so far (last time I did anything was on Sunday), but today when Taiga tries to download my list it crashes every time at around ~160KB downloaded. Tried removing all my Taiga user data and redoing my settings, but the crash on list download persists. Latest entries from Taiga.log (I tried downgrading to 1.3.0-alpha.2 but it didn't help either, which is why there's the upgrade message again from today):
```
2017-10-10 14:29:13 [Warning] settings.cpp:65 taiga::AppSettings::HandleCompatibility | Upgraded from v1.3.0-alpha.2 to v1.3.0-beta
2017-10-10 14:30:17 [Warning] anime_db.cpp:442 anime::Database::LoadList | Reading list in compatibility mode
```

**Comment by erengy** [comment]
After some investigation, this turned out to be the same issue as [this one](https://github.com/erengy/taiga/issues/412#issuecomment-317268674):

> Yours seems to be another issue related to R18 media being hidden. I'll report it to Kitsu devs now. In the meantime, you can go to your [Profile](https://kitsu.io/settings/profile) and select Show Adult Content option to avoid the crash.

Apparently, it wasn't fixed entirely the last time. Filed another report to Kitsu devs now.

I'll try taking some measures against the crash, although it may result in some NSFW anime being ignored.

**Comment by Daiz** [comment]
Setting adult content to show seems to have fixed the crashing on my end. Thanks!
