### ISSUE TITLE
Episodes are ignored if anime is missing start date

### ISSUE THREAD

**Issue by wopian** [erengy/taiga#475]
Episodes with a missing (or incorrect) start date are ignored, but the folder the episodes are in is found

---

E.g [`Tsukipro The Animation`](https://kitsu.io/anime/tsukipro-the-animation) is currently missing its start date on Kitsu and 2 episodes have aired. It's found the folder the episodes are in:

![](https://i.imgur.com/c1AcxTb.png)

However the list shows I no episodes downloaded

![](https://i.imgur.com/pQghAf5.png)

**Comment by ShaunV2** [comment]
@wopian That's something you should bring up on Kitsu via Database Requests not here, I did notice this with a different series when the start date was 3 days behind for Net-juu no Susume since Taiga wasn't able to recognize the series at all due to the start date being wrong but once it was corrected on Kitsu's end Taiga was able to detect the series fine.

**Comment by wopian** [comment]
>That's something you should bring up on Kitsu via Database Requests not here

It was merely a working example, which Net-juu and Garo also would've been several days ago 😕

**Comment by erengy** [comment]
> My guess is this could be done on purpose since you wouldn't normally be able to watch something that isn't airing yet.

This is correct. In the identification process, Taiga's recognition engine checks the airing date of anime. The [switch](https://github.com/erengy/taiga/search?utf8=%E2%9C%93&q=check_airing_date&type=) for this feature is enabled for files and torrents, but disabled for directories.

Not sure if I should take any action here, since it seems to be primarily a data quality issue on Kitsu. I doubt this is common enough to justify disabling the feature entirely. Would disabling it only for series with missing date (but still ignoring not-yet-aired anime) be a good compromise?
