### ISSUE TITLE
Reddit Episode Discussion Search

### ISSUE THREAD

**Issue by ShyGuyFTW** [erengy/taiga#476]
The Reddit episode discussion search function doesn't work anymore on the 1.3.0-beta.

http://puu.sh/xYo5V/fa97031856.png

**Comment by wenbei999** [comment]
I don't think that's related to Taiga.

I think it doesn't work because you're using quotes, which usually means you want that exact phrase in that order. Try being less specific but still unique, like searching "Net-juu"

**Comment by wopian** [comment]
Seems to be working fine on 1.3.0-beta here 🤔 

![](https://i.imgur.com/dhX33pU.png)

**Comment by ShyGuyFTW** [comment]
Yeah the quotations caused the problem, its weird because the quotes never caused a problem before.

**Comment by erengy** [comment]
This issue was [brought to my attention](https://myanimelist.net/forum/?topicid=1666922#msg52407878) a couple of weeks ago. It seems like Reddit's looking for an exact match due to double quotes. This wasn't the case until recently, so I'm guessing that something on Reddit's end must have changed.

The problem is, double quotes are required for multi-word queries to determine where the query ends. Removing them would make the syntax ambiguous. Even their [wiki](https://www.reddit.com/wiki/search#wiki_field_search) still says:

> When making a multi-word field search, wrap the query in double-quotes. Single-quoted field searches are not supported. Example: `flair:"Multi Word Text"`

I'd appreciate it if someone could submit a post at [r/help](https://www.reddit.com/r/help/) (or where it's appropriate) and describe the issue. Perhaps it's an oversight on Reddit's part and they can fix it.
