### ISSUE TITLE
Unknown error (myanimelist|1|403)

### ISSUE THREAD

**Issue by GrandXark** [erengy/taiga#481]
Can anyone help me with this? I'm using 1.3.0-beta

**Comment by erengy** [comment]
You're getting a [403 Forbidden](https://en.wikipedia.org/wiki/HTTP_403) error from MyAnimeList while Taiga is trying to authenticate your account. This usually means that either your account or your IP address is banned. If it's a temporary ban on your IP address (possibly due to the latest [API security updates](https://myanimelist.net/forum/?topicid=1632480)), it should automatically be lifted after a couple of hours. Note that this issue is not specifically related to Taiga.
