### ISSUE TITLE
Problems recognising R-R releases

### ISSUE THREAD

**Issue by wiiaboo** [erengy/taiga#5]
R-R releases use the syntax:
[R-R] AnimeTitle.EPn (720p.Hi10p.AC3) [CRC32]

example:
[R-R] Diebuster.EP1 (720p.Hi10p.AC3) [82E36A36]

Anime titles get recognized as "Diebuster.EP1", "Diebuster.EP2", etc.
After selecting the correct anime title, only the same episode is recognized: http://i.imgur.com/iKK796i.png

What works:
Replacing the period between Title and EPn with space (i.e. "Diebuster EP1")
Replacing space between Subgroup and Title with period (i.e. "[R-R].Diebuster.EP1")

I have only ever seen this particular fansub using this syntax so this should only matter for whoever is watching their Gunbuster/Diebuster releases. But still, it's a format that could be used again.

**Comment by erengy** [comment]
Anitomy (the new filename parser Taiga is going to use in v1.2) is now able to handle multiple delimiters within a single group. This takes care of this issue and all the test cases I have. Currently the only exception is ` Aim_For_The_Top!_Gunbuster-ep1.BD`, because dash is not considered to be a delimiter.
