### ISSUE TITLE
Avoiding malicious torrents

### ISSUE THREAD

**Issue by Erionn** [erengy/taiga#510]
Every so often someone will upload malware disguised as currently airing anime so that it's picked up by your filter, [like this](http://puu.sh/yTMAo/c6ea8bbfd7.png). Is there any way for stricter filters to avoid this, like discarding extremely small file size torrents?

**Comment by erengy** [comment]
For nyaa.si, using the "Trusted only" filter (by changing the `f=0` in the feed URL to `f=2`) could help, but it may discard some valid torrents too.

Tokyo Toshokan allows setting a minimum size (e.g. `minMB=10`) in its [RSS Options](https://www.tokyotosho.info/rss_customize.php) page.

I can probably add a "File size" element to Taiga's filters, so that you can create a filter condition such as `File size (MB) | is less than | 10` to discard matching torrents.
