### ISSUE TITLE
HIDIVE/Crunchyroll Recognition issues

### ISSUE THREAD

**Issue by Assassin2244** [erengy/taiga#529]
HIDIVE detection doesn't work for me, I get a windows notification saying it didn't detect the episode.

Also currently watching Hoozuki no Reitetsu on Crunchyroll and it doesn't detect this show specifically, not sure if this can be fixed.

**Comment by erengy** [comment]
HIDIVE detection is now fixed with 1490429e1029ddb15ec0104afb9143192a82a56d. Look like they changed their page title format recently, which broke recognition.

The other issue you're having is likely because the series is named *Hozuki no Reitetsu* on Crunchyroll, with one "o". Adding it as an alternative title to the series should resolve the issue.

**Comment by Assassin2244** [comment]
How do I apply the fix you linked?

**Comment by erengy** [comment]
It will be included in the next application update. If you don't want to wait, you may download the [latest build](http://taiga.moe/latest.html).
