### ISSUE TITLE
Show downloaded files in completed column too

### ISSUE THREAD

**Issue by sand500** [erengy/taiga#534]
For those of us who are data hoarders, it would be nice if the completed tab showed the downloaded episodes like the currently watching tab does. Especially if we watch anime across multiple devices and have missing episodes. Also a column for maybe % of episodes missing would be nice too.

**Comment by erengy** [comment]
*Completed* tab does show available episodes in library folders. It's the same with all other tabs. You should be seeing a darker green line at the bottom of progress bars (#152). Hovering the cursor above a bar displays a tooltip that tells you which episodes are missing, if any.

Do you mean highlighting *Anime title* column? If so, note that a list item is highlighted only if the next episode is available in library folders. This doesn't apply to completed series, since there is no "next episode" to watch.

For more columns, we have a generic issue at #150.
