### ISSUE TITLE
Taiga doesnt want to recognize Yu-Gi-Oh! ZeXal II

### ISSUE THREAD

**Issue by kael070** [erengy/taiga#537]
I know its not the best one in the series but, come on...
it says taiga was unable to identify this title, then shows me some yugioh series i already watched, and its not one of those
I press search and it shows me the mal one called Yu-Gi-Oh! ZeXal Second, but i cant tell taiga this is the one im watching, its already on the list and yet taiga doesn't recognize it, and i cant rename the files since im seeding
Halp

**Comment by andyvorld** [comment]
![capture](https://user-images.githubusercontent.com/24492062/37242004-2633a672-24b6-11e8-8038-2aadda39bbc7.PNG)

Try adding it in the alternative title box.

**Comment by kael070** [comment]
![screenshot_306](https://user-images.githubusercontent.com/36388317/37245634-f86dddca-2479-11e8-8ebc-ea8c40d805e0.png)
Tried it and doesn't seem to work

**Comment by andyvorld** [comment]
I dont think you can really solve this problem, because Taiga detects the first episode labeled as episode 1, however your files have the season starting at episode 74. So Taiga has difficulty detecting it running.

![untitled](https://user-images.githubusercontent.com/24492062/37247561-106d0814-2511-11e8-83de-01aa140e131f.png)

Changing the file name from 076 to 003, lets taiga detect it.

**Comment by kael070** [comment]
Oh I see, too bad then, it would require a change in the file names and that would destroy the seeding proccess, thanks anyway.
