### ISSUE TITLE
MAL Statistics page

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#543]
If you use MAL account on Taiga and look at statistics page, the "Time spent watching" and "episode count"  is lower than what's on MAL page itself. I suspect its because that statistics in Taiga doesn't count rewatched times. Is this intentional and if not, can it be changed to be consistent with MAL? Also, the score seems to have decimal in wrong place. Using Taiga 1.3.0 beta 2.
![capture](https://user-images.githubusercontent.com/20476454/37779434-d1d3570e-2e05-11e8-9f25-82cdd96f86cd.JPG)

**Comment by erengy** [comment]
The inconsistency between the website and Taiga is inevitable, because MAL API doesn't provide the necessary information (rewatch count, episode duration). All that Taiga can do is to estimate. The numbers are fairly reliable in most cases, but not entirely accurate.

The issue with the position of decimal point is likely caused after 3f62fe885676f6819c7d66e4fec3735ddf4d5ed0. I'll fix that shortly.

**Comment by asakurato** [comment]
So it is exactly without rewatch times right? It's nice to have this difference actually, if you want to actually know that statistic.

**Comment by erengy** [comment]
That's right. For *Time spent watching* and *Time to complete*, Taiga assumes the following:

Anime type|Episode duration (minutes)
:--|--:
Movie|90
TV|24
OVA|24
ONA|24
Special|12
Music|5

Note that this is only the case for MyAnimeList. Other services (Kitsu and AniList) provide the relevant information in their APIs. This will no longer be an issue once MAL's new API becomes available.

**Comment by asakurato** [comment]
Doesn't MAL calculate anime watch times exactly as the length of actual episode/movie? If for example the episodes are half-long, or the movie is 3 hours, doesn't they calculate exact values? So Taiga uses it's own estimation or that data comes directly from MAL?
