### ISSUE TITLE
Pre-download information/details from all collected animes

### ISSUE THREAD

**Issue by rexisted** [erengy/taiga#548]
Hey

Is possible to let information such as details and synopsis to be downloaded beforehand so people who use their computer offline or wants to sort by score without having to go through each and anime information to get it to download.
I feel like this is possible but I can seem to find that feature and if it isn't I don't think it should be a hassle to implement.

Great job though this is a great application

**Comment by erengy** [comment]
Hey @rexisted,

Most of the information is downloaded along with your anime list when you synchronize. However:

- Some information (e.g. genres, producers, synopsis, average score) cannot be retrieved this way from MyAnimeList because of the limitations of their API.
- For Kitsu, synopses are not requested along with library entries, on purpose. Otherwise, in some cases, either it takes too long to download or the request fails.

**Comment by rexisted** [comment]
Even it means it will take a long time. Isn't possible to request the data
one at time automatically? Because other wise it seems pointless to allow a
feature to sort by average score if you can't even get that data without
going through all of the listed anime and that could be over 100+ which is
a very tedious task that could be automated.

**Comment by erengy** [comment]
It's technically possible to do that, but I'd rather not. Taiga avoids hammering MAL's servers where possible. Otherwise you risk getting your account, or even Taiga itself, temporarily banned.

Also note that when you enable the *Average score* column, Taiga warns you about the limitation.

Good news is that MAL is now working on a new API, which will hopefully resolve this issue (also at #309) and many others.

**Comment by rexisted** [comment]
Oh ok thanks. I guess I'll just have to wait
