### ISSUE TITLE
Airing status wrong for several titles

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#549]
I have noticed this mainly at the end of each season, when the shows finishes. I haven't found any similar issued opened here, so maybe it's indeed a very rare bug (or one of the MAL api limitations).

So. look at my current list
![capture](https://user-images.githubusercontent.com/20476454/38132201-214d8780-341b-11e8-8e82-c6e716fcf7c5.JPG)
"Beatless Intermission" and "Hakumei and Mikochi" are marked as finished airing and currently airing respectively, while it's the opposite for both entries:
![capture](https://user-images.githubusercontent.com/20476454/38132251-5df4b5fa-341b-11e8-9097-26b1f2f7db3d.JPG)
![capture](https://user-images.githubusercontent.com/20476454/38132341-c10bd4ca-341b-11e8-8fba-df525dc5e072.JPG)
So I guess it's something about different time zones used by MAL and Taiga? So the statuses are different.

**Comment by webtax** [comment]
also not sure if maybe related, season is wrong for [B: The Beginning](https://myanimelist.net/anime/32827/) and [A.I.C.O.: Incarnation](https://myanimelist.net/anime/36039/),

![msyzbeo](https://user-images.githubusercontent.com/15698145/38152918-6c888d42-3440-11e8-870e-aa8bc275322a.png)

puts them on spring 2018, should be on winter. Also [ReLIFE: Kanketsu-hen](https://myanimelist.net/anime/35466/), but not sure when spring starts to count.

**Comment by erengy** [comment]
@asakurato The first case is a long-standing issue where Taiga doesn't remove existing dates (i.e. the end date of the series was recently removed from MAL, but Taiga still keeps the old one). Fixing this issue requires some major changes, so I postponed it to v1.4. The other is most likely because of the fact that Taiga doesn't know the broadcast hour. It should be resolved by now.

@webtax All those series aired in March, which is considered to be in the Spring season. See the table at [erengy/anime-seasons](https://github.com/erengy/anime-seasons) for the convention used in Taiga.
