### ISSUE TITLE
Avast blocking 1.3

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#553]
never had a problem with taiga before but since the update to 1.3 my antivirus is blocking it and refuse to whitelist until the file is checked my avast.

**Comment by erengy** [comment]
This is usually what happens after a new release, unfortunately. Since the executable files are new, some antivirus products may see them as suspicious. Sometimes I end up filing [false-positive](https://github.com/erengy/taiga/issues?utf8=%E2%9C%93&q=label%3A%22false+positive%22) reports to multiple companies after each release.

VirusTotal reports for v1.3.0:

- [Taiga.exe](https://www.virustotal.com/#/file/a862b1db552332e69131dbc8c4f4a924f9670c70ea3d62bbd842498099a33a0c/detection)
- [TaigaSetup.exe](https://www.virustotal.com/#/file/17fe89bb7e28eb1fe52c9b50db1eb7aa9051280bbf43f50eae6ec0989823f74c/detection)
