### ISSUE TITLE
Auto recognition not working on NAS

### ISSUE THREAD

**Issue by NotDaniel59** [erengy/taiga#556]
I'm using the new 1.3 version and now Taiga won't detect when I open a file from my NAS, it still is able to scan all files though. It can detect files when I create a folder on my local HDD and add that to the library. It only detects the files on my NAS when I disable "Ignore files outside of library folders".

The way I've implemented my NAS is through the normal windows explorer. I have just added the folder as 
a drive called "Anime(A):". This is how it looks in Taiga.
![taiga_2018-04-06_11-19-34](https://user-images.githubusercontent.com/28601384/38413686-b57aec7e-398c-11e8-8045-ca30b2943728.png)

I'm on Windows 10 and it was working with version 1.2

**Comment by erengy** [comment]
This is most likely the same issue as #487. I wasn't able to figure out the cause for that, but:

> It only detects the files on my NAS when I disable "Ignore files outside of library folders".

> it was working with version 1.2

Knowing these really helps. I'll look into it.

**Comment by Akamaru** [comment]
I have the same issue. But I don't use a NAS, I have a local server with Ubuntu and Sama Share. My Anime folder is mounted as an network drive in Windows 10. Disable "Ignore files outside of library folders" does not work for me. It was working with version 1.2 for me too.

![taiga_2018-04-06_13-56-34](https://user-images.githubusercontent.com/8063440/38420059-e383a672-39a2-11e8-9f12-aed9005bb655.png)
![taiga_2018-04-06_13-56-54](https://user-images.githubusercontent.com/8063440/38420060-e39eeca2-39a2-11e8-8c56-556e679cdb23.png)

**Comment by LordZounds** [comment]
I can confirm that I'm having the same issue, and it also only started after updating to 1.3.

An additional minor problem that I'm not sure if it's related since I had it on earlier versions too is that ever since moving my files to a NAS, the file scan detects them but does not detect when they're deleted. Also, when I right click and select Open Folder on new episodes, it takes me to my in-progress torrents folder rather than the folder on the NAS where new episodes are moved to after downloading. Neither of these are a big deal but I thought I'd note them in case they're related.

**Comment by ovingiv** [comment]
I'm just speculating here but, it seams that there's some sort of 401 or 403 sounding issue.

**Comment by erengy** [comment]
I actually figured out the (most likely) cause already, just need some time to work on it.

Basically, it's because the path Taiga receives from [Anisthesia](https://github.com/erengy/anisthesia) is in a different format, so Taiga is unable to properly compare it with library folders.

**Comment by erengy** [comment]
Could you try out the [latest build](http://taiga.moe/latest.html) and see if it fixes the issue?

**Comment by NotDaniel59** [comment]
Yes, thanks it's working now.
