### ISSUE TITLE
Episode number not recognized if at beginning of file

### ISSUE THREAD

**Issue by TomQDRS** [erengy/taiga#561]
I recently downloaded a batch of an older anime. The episode files in that folder are titled like this:

`00 Anime Name (Year) [Quality Information]`

This causes Taiga to not recognize the anime at all. It seems to interpret the number at the beginning as part of the title. Taiga recognizes the anime correctly after changing the title to look like this:

`Anime Name 00 (Year) [Quality Information]`

Which is weird, since looking at [recognition.cpp](https://github.com/erengy/taiga/blob/master/src/track/recognition.cpp), that case seems to be specifically checked for:

```auto pos = find_number_in_string(filename);
    if (pos == 0)  // begins with a number (e.g. "01.mkv", "02 - Title.mkv")
      episode.set_episode_number(ToInt(filename.substr(pos)));
```

Any idea what could be going on here?

**Comment by erengy** [comment]
Assuming that the files are located in a directory named `Anime Name`, I think the issue here might be that `(Year)` doesn't match the airing date of the series. To give an example, Taiga is able to identify `Toradora!\01 Toradora! (2008) [720p h264].mkv`. But if you changed `2008` to `2007`, recognition would fail. If you removed the year from the filename, it'd work once again.
