### ISSUE TITLE
Taiga can't detect some torrent for anime that I have in the list.

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#567]
I discovered this only this season. I have some animes that I definitely have on my list. I have enabled torrent filter to not search animes that aren't on my list, but because of that, some of the entries aren't detected. Such example is Wotaku ni Koi wa Muzukashii. Here is screenshot of torrent
![capture](https://user-images.githubusercontent.com/20476454/38705734-9a486c40-3ebb-11e8-9373-a2c85a0b18a6.JPG)
It shows that it's not on my list (grey square)
And here is it on my list
![capture1](https://user-images.githubusercontent.com/20476454/38705746-ac696e74-3ebb-11e8-8cb6-2d3b760be7b2.JPG)
Now, if I enter the title of the file in alternative names on the anime, it will work, but I cannot know that until I discover that Taiga can't find some files. Hope I explained it well.

**Comment by erengy** [comment]
As you've discovered, adding `Wotaku ni Koi wa Muzukashii (Wotakoi)` as an alternative title to the series will work. I'm afraid there isn't much else to do here. Taiga must identify the anime first to see if it's in your list, and it cannot identify without the alternative title (because of the `(Wotakoi)` at the end).

As for the torrent filter, you should at least be able to make a distinction between unidentified anime and not-in-list ones. You can even combine the following conditions to only match identified not-in-list anime:

Element|Operator|Value
:------|:-------|:----
Anime ID|is not|`0`
Anime watching status|is|Not in list

**Comment by asakurato** [comment]
I would try the filter solutions in the morning, will tell if it worked

**Comment by asakurato** [comment]
After adding Anime ID is not 0, Taiga can't find the title anymore, even with alternative title entered. I think I'll use alt titles wherever possible, if nothing really can be changed here.
