### ISSUE TITLE
new tab for aired but unwatched anime ep

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [erengy/taiga#582]
i know u can see the aired but unwatched on currently watching but can u make a separate tab for that  it will be easy to see or u can change the colour of the progrees bar of those anime ep u havent watch that aired

**Comment by erengy** [comment]
This is similar to #559, except that it's for aired episodes rather than downloaded ones. In general, I'm not planning to add new pages or tabs for these kinds of things.

Also note that Taiga doesn't have reliable information about aired episodes (#59). All it does is to estimate based on how many weeks have passed since the airing date of the first episode. When that information becomes available, I might add a new column to Anime List (#150) to make it easier to parse.
