### ISSUE TITLE
MAL API is down

### ISSUE THREAD

**Issue by Akamaru** [erengy/taiga#588]
It seems that MyAnimeList has had a vulnerability in the API and has now disabled it.
Taiga does not work anymore and shows an error.

`MyAnimeList returned an error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Foud</h1> <p>The requested URL /api/account/verify_credentials.xml was not found on this server.</p> <p>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocu...`

![image](https://user-images.githubusercontent.com/8063440/40484193-09e1ae9e-5f5b-11e8-906a-ad0a68e8f10d.png)

I know it's not an taiga issue and erengy can't fix this. We have to wait for MAL.

**Comment by taigalover** [comment]
Phew, wasn't just me either

**Comment by moyitpro** [comment]
This is like a train wreck. The new official MAL API stop working and now this. This is very frustrating.

**Comment by erengy** [comment]
It's a serious issue. They completely disabled the API without prior notice to third-party developers, and even went as far as removing the [API documentation](https://myanimelist.net/modules.php?go=api) page. This affects all applications that make use of the official API. It's undoubtedly a new low in their track record.

There's no telling when the issue is going to be resolved, but contacting DeNA's [customer support](https://myanimelist.net/about.php?go=support) seems to be the best way to file your complaints at the moment. From what I can tell, this whole thing is related to DeNA (MAL's parent company) rather than the MAL staff.

Note that you can continue using Taiga while the MAL API is down, to some extent. But you won't be able to sync your list, retrieve new anime information, etc. Taiga will send any queued updates to MAL when the API becomes available.

**Comment by moyitpro** [comment]
Official response from Xinil:
My deepest apologies everyone. Trust me when I say Kineta and I fought tooth and nail to have this play out any other way, but our hands were tied. It’s no excuse, and we’re ultimately responsible for this awful public image. I take blame for building your trust for so many months, only to shove it completely aside.
We’re going to continue doing our best to try and mitigate the current situation. In the mean time, I would suggest you inform your users this API outage is for an indefinite period. I honestly do not know how long it will be

Ugh, not this again. I guess I should focus more on adding AniList support to Hachidori.

**Comment by onlybrad** [comment]
I don't even remember what email I used to create my MAL account. So not only I can't recuperate my account, I can't even resync my anime list with a new account because the API is down...

**Comment by erengy** [comment]
We've been told that the API outage is for an indefinite period of time. MAL staff are unable to comment further on the issue; they encourage us to speak with DeNA's customer support instead. Apparently there's been some disagreement between them and DeNA on the matter.

We currently don't know what this is all about, but [it wasn't due to a security breach](https://myanimelist.net/forum/?topicid=1731368). If I had to speculate, it might be related to [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation "General Data Protection Regulation") (aka "we've updated our privacy policy" regulation) coming into effect tomorrow. Perhaps they couldn't work out the issues in time and ended up shutting down the API entirely. In any case though, DeNA handled the situation quite poorly so far. We're hoping to get a proper response tomorrow.

In the best-case scenario, the API will come back online soon and Taiga will continue working as usual. In the worst-case (?) scenario, many third-party application developers, including myself, will stop using MAL altogether and suggest other people to do the same.

**Comment by guft** [comment]
Yes I believe it is GDPR related. Over the last week many online services have updated their privacy policies and forced users to reset passwords and reconfirm permissions. Considering that MAL's entire purpose is tracking stats and information about its users, it makes sense they would have to jump through a large number of hoops to be GDPR compliant. Taking the API down is a drastic step, but considering GDPR's fines for noncompliance are 20 million euros or 4% of global revenue (whichever is greater) it makes sense they would do this if they are afraid they are not in compliance. However, keeping the site on lockdown is not good for their business either, so if they can't satisfy regulator demands they will likely resort to blocking EU users and restoring the API everywhere else, which is what many other online services have resorted to doing in the last week.

**Comment by Ruhrpottpatriot** [comment]
GDPR is a bullshit excuse! That regulation is in effect since **TWO** years, today the transition period ended that was put into place by the EU to allow relevant services to migrate their stuff. That means, they had two years time to make everything GDPR compliant, yet sat on their asses and did nothing.

Is Kitsu still working? If so MAL has seen the last of me.

**Comment by moyitpro** [comment]
@Ruhrpottpatriot 

MAL importing on Kitsu still work and Taiga and other third party clients that work with Kitsu should still work.

**Comment by Azraelle** [comment]
REEEEE

**Comment by Kovaelin** [comment]
MAL's going to lose a lot of users if they don't fix their API.

**Comment by Ruhrpottpatriot** [comment]
@moyitpro Yeah, I figeured that out. But not I have to manually update my list, since Taiga first pulls the list, then pushes it back. That resulted in a loss of data for me.

@erengy Could you implement a way to force push the list to the selected online service. Sometimes the user knows that the online service is outdated and just wants to overwrite it with new data.

**Comment by Zenithtb** [comment]
@Ruhrpottpatriot - interesting idea - using Taiga as a pull-me-push-you of data to be able to change service... I like your thinking!

**Comment by taigalover** [comment]
> Taiga will send any queued updates to MAL when the API becomes available.

So do we now use our old password or new password to login to Taiga? So when (if) the API becomes available, taiga can send the queued updates?

**Comment by Azraelle** [comment]
Anilist is adding back xml import. I'm jumping the ship.

**Comment by asakurato** [comment]
![screenshot_gmail_20180526-220221](https://user-images.githubusercontent.com/20476454/40579047-9b98b180-6130-11e8-9c19-a7cc1b020e69.png)
Just received this from DeNa (MAL support), so maybe there is hope

**Comment by Akamaru** [comment]
There is now a statement https://myanimelist.net/forum/?topicid=1731860

**Comment by Ruhrpottpatriot** [comment]
Which, is a complete bullshit excuse as an admin (Xinil) has stated in the forum, that there was no security breach.

**Comment by tophf** [comment]
A weird workaround could be writing a Chrome/Firefox extension that communicates with Taiga via nativeMessaging and keeps MAL site in a hidden iframe with a content script inside that can supposedly do everything the API provided via page DOM. It can even run in a shell tray when all browser windows are closed unless the user explicitly exited the browser via Ctrl-Shift-Q or Exit command. Such extension seems relatively easy to implement.

**Comment by spillerrec** [comment]
Thanks for this issue even though it is not due to Taiga, as I came here to see what was going on.

To me it sounds like it might be a third party website that stole peoples login information, though the timing is suspiciously close to the GDPR deadline. (Correction for above, it is **up to** 20 million euros or 4% of revenue, whichever is greater.)
I do think it is a very bad idea that the API uses the username/password for credentials, now that they apparently have a store and can save peoples credit card information. **Very bad idea...** Some sort of API key system (such as SSH keys or whatever) where you can have multiple keys and set permissions for each would be much better.

I would give it a bit more time before putting in too much work on a workaround. I would prefer if everything was done in Taiga though, so there is no dependency on browsers and IPC. Just too much that can go wrong and I fear it wouldn't work in Wine either. I doubt their internal API is so weird that you can't simulate the requests without using a full-featured web browser.

For convenience, here is the MAL link to export your anime/manga list:
[https://myanimelist.net/panel.php?go=export]()

**Comment by marwanpro** [comment]
Fine I will develop a C# API tomorrow.

**Comment by moyitpro** [comment]
@spillerrec 
I have worked with the new MAL API before they closed down the new official MAL API. It was using OAuth2 with PCE challenge, which is more secure than using Basic Auth. If the username and password thing was an issue, they should of retrofit OAuth2 and require developers to register their apps to obtain a OAuth2 client and secret to the old API until the new API is ready.

**Comment by KrisKamweru** [comment]
I think I'll just be switching over to Kitsu. Would there be any reason why I should not, i.e. is Kitsu inferior in any way to MAL?

**Comment by Akamaru** [comment]
Hm, I hope they fix this now

![image](https://user-images.githubusercontent.com/8063440/40610759-eb70dfcc-6273-11e8-85b6-15ff181d0dc9.png)

**Comment by taigalover** [comment]
![](https://user-images.githubusercontent.com/8063440/40610759-eb70dfcc-6273-11e8-85b6-15ff181d0dc9.png)

Damn, forgot to export my list.

**Comment by erengy** [comment]
If you don't want to wait any longer:

- MAL → AniList: https://anilist.co/forum/thread/3151
- MAL → Kitsu: https://kitsu.io/posts/8930915

Note that Taiga may not have your entire list data due to limitations of MAL API (sigh).

**Comment by Ruhrpottpatriot** [comment]
@erengy 
> It does the opposite, actually. If you have queued updates, Taiga will always try to upload them first. The only exception is when the account password is unavailable. In that case, Taiga ignores the queue and downloads the list.

It also does that when switching to a different provider, and that's what has caused my data loss. I'd be great if you could implement a check to see if the provider was changed and if so, ask the user if he wants to
`pull` then `push`, or do a `push --force` (git terms seem appropriate here)
(Note: This would also be a nice little workaround to allow users to sync to multiple providers -- manually, yet better than nothing).

**Comment by erengy** [comment]
@Ruhrpottpatriot Could you open a new issue about this? In that issue, please describe the steps you took and the data you lost as a result.

**Comment by erengy** [comment]
I added an export feature to Taiga in 6af570edfc4836c448eea79a6af325f730ca9ded to make things a bit easier:

1. Get the [latest build](http://taiga.moe/latest.html) of Taiga.
2. Use the new feature via *Tools → Export anime list → Export as MyAnimeList XML*.
3. Upload the generated XML file to [AniList](https://anilist.co/settings/import) or [Kitsu](https://kitsu.io/settings/imports).

My previous warning still stands:

> Note that Taiga may not have your entire list data (e.g. how many times you've re-watched a series) due to limitations of MAL API (sigh).

Let me know if it works for you.

**Comment by EliEron** [comment]
AniList's importer did not do too well when I tried to import the XML Taiga generated. It was unable to import 127 series of 293. In contrast the XML that was generated by using the python script that Morimasa (https://anilist.co/forum/thread/3151) created it only failed to import one series.

The XML Morimasa's script generates list the names in this format: "<series_title>malID( 2167 )</series_title>"  in other words it provides the MAL ID instead of the actual name, which the AniList importer seems to be a lot better at handling.

**Comment by spillerrec** [comment]
> > I do think it is a very bad idea that the API uses the username/password for credentials, now that they apparently have a store and can save peoples credit card information. Very bad idea...

> That is (hopefully) not the case. Quoting from the recent Account Freeze/Password Reset & Broken Applications thread:

I didn't mean that you would be able to extract the credit card information, but if you enter your credentials to a service, they could log into your account and click that 'Buy' button for you. Or just use your account to post Russian propaganda on the forums. It is never a good idea, but adding money and potentially sensitive personal information into the mix makes it a lot more serious.


I tried switching to AniList personally, of the ~1060 entries in my list, 11 failed. (Export through MALs website.) Most of it was obscure stuff but a few OVAs/specials were not in AniList's database. An OVA series was listed as two seasons in MAL and only one season in AniList, causing the episode count to be wrong.
So just a heads up that those services might not be completely compatible and that AniList appears to be less complete, but an error rate of only 1 % is really good nevertheless.


MALs error page has been updated btw:

![mal](https://user-images.githubusercontent.com/2292170/40737187-5664d46e-6440-11e8-9b5e-d5171a6260a4.png)

Do you seriously want me to believe that you shut down a  site with millions of users for an undetermined amount of time just because there was a slight suspicion?

**Comment by erengy** [comment]
> AniList's importer did not do too well when I tried to import the XML Taiga generated.
>
> It was unable to import 127 of 293 series. In contrast the XML file generated by the python script that Morimasa (https://anilist.co/forum/thread/3151) created only failed to import one series.

Hey @EliEron, thanks for the feedback. I wonder why you had such a high error rate. I just tried importing 786 series, and only 5 of them failed. If it makes any difference, I deleted my anime list from AniList's settings before importing the XML file.

> The XML Morimasa's script generates list the names in this format: "<series_title>malID( 2167 )</series_title>" in other words it provides the MAL ID instead of the actual name, which the AniList importer seems to be a lot better at handling.

I'd assume that the Python script does that only because it doesn't know the actual titles. I doubt AniList uses that, since MAL ID is already provided in `series_animedb_id`.

**Comment by EliEron** [comment]
After some further testing and troubleshooting I now realize what the issue was, and it was entirely caused by a mistake I did. I accidentally used the export function while Taiga was set to my AniList account, meaning that the generated XML was filled with AniList IDs instead of MAL IDs, which of course confuses the importer.

When I switched it over to the MAL list and exported that the importer worked exactly as well as it did with the XML Morimasa's script generated.

I apologize for my mistaken report, and any confusion it might have caused.

**Comment by Ruhrpottpatriot** [comment]
@spillerrec I had the same issue, mostly Picture Dramas, but I opened a topic on their forums. If an anime is missing you can report it [HERE](https://anilist.co/guidelines?legacy=1#new)

**Comment by erengy** [comment]
The website is [back online](https://myanimelist.net/announcement/201806), but the API isn't. You still cannot use Taiga or any other application with MAL. You can, however, [export your list](https://myanimelist.net/panel.php?go=export) now.

**Comment by erengy** [comment]
It's been three weeks now. Still no news about the API. Their [latest tweet](https://twitter.com/myanimelist/status/1007284296070070278) says:

> Unofficial apps (e.g. iMAL, MyAniList, MALClient, PocketMAL) will still not be working properly as our public API is still disabled. We are aware this is an important issue for users, and apologize for not having any new information to provide yet.

I won't be posting any more updates here until something substantial happens.

**Comment by Fcort237** [comment]
Hello, very interesting your post, I want to thank you, but I would like you to answer me the following: which API anime database you currently use for your anime website, I'm starting in this I already have a movie website, but I want Can you make an anime one?

**Comment by Nevalopo** [comment]
I feel so lost without Taiga :(

I hope they fix their API really soon or i might have to go check out other anime databases

**Comment by Fcort237** [comment]
If you have a website from an anime series, what other databases do you
know? mention everything you know please, to investigate

2018-07-10 6:26 GMT-06:00 francisco jose rojas tellez <
josefcort237@gmail.com>:

**Comment by qgustavor** [comment]
@Fcort237 No te entiendo: ¿no conoces AniList y Kitsu? Ambos funcionan con el Taiga. También existe AniDB y Anime Planet. No soy el responsable de Taiga, pero por mi experiencia con el GitHub recomiendo que no quede enviando varios mensajes y espere que alguien te responda. Probablemente aún no te respondieron porque están sin tiempo. En cuanto a crear otra base de datos mi opinión es que ya hay varios de ellos, crear otro más [no sería una buena idea](https://xkcd.com/927/).

**Comment by Volatar** [comment]
iMAL, the iOS app, switched to spoofing the web interface to restore partial functionality to it's app. Might be time to consider that.

**Comment by qgustavor** [comment]
@Volatar Browser spoofing isn't hard to implement, but it's hard to maintain: as MyAnimeList never had a complete API clients used to spoof browsers and parse data which the original API don't provided ([example 1](https://github.com/AnimeNeko/atarashii-mal-api/blob/b68a05bcc96bac166e239f73bf6417d04b2da2b0/src/Atarashii/APIBundle/Parser/TitleParser.php#L18), [example 2](https://github.com/erengy/taiga/blob/42e944e6a2684aeefe55a7541ad327dfb329c2ac/src/sync/myanimelist.cpp#L300)). Because of this most clients already have tools in order to parse HTML.

One of the features the official API had is updating the anime list: it's not hard to implement spoofing a browser, just do a GET request to the edit anime page, edit the `<form>` as you want, add the CSRF token to it and then submit it. In the other hand it's likely to break as MyAnimeList is updating the entire website to fix "issues" and because there are some people thinking they're doing that in order to kill third party applications. I don't think they will put a captcha on this page - users would hate this - but there other things that they can do in order to make spoofing harder.

**Comment by Nevalopo** [comment]
I just went to https://myanimelist.net/panel.php?go=export To export my anime list from MAL and then imported it at kitsu now everything is working flawlessly agian.

**Comment by spillerrec** [comment]
@Volatar erengy added an export option from Taiga, so you should be able to use that to move to a different service without loosing your 2 months of progress I believe. See one of the posts above for details.

> Tools → Export anime list → Export as MyAnimeList XML.

**Comment by Zorua** [comment]
@spillerrec I'll let you know that even though
>Taiga is up to date!
>Current version: 1.3.0

the menu entry is not there.

**Comment by Akamaru** [comment]
@Zorua see the comment from 30. May [here](https://github.com/erengy/taiga/issues/588#issuecomment-393226127)

> I added an export feature to Taiga in [6af570e](https://github.com/erengy/taiga/commit/6af570edfc4836c448eea79a6af325f730ca9ded) to make things a bit easier:
> 
> 1. Get the [latest build](http://taiga.moe/latest.html) of Taiga.
> 2. Use the new feature via Tools → Export anime list → Export as MyAnimeList XML.
> 3. Upload the generated XML file to [AniList](https://anilist.co/settings/import) or [Kitsu](https://kitsu.io/settings/imports).
> This file will include your queued updates. However, my previous warning still stands:
> 
> Note that Taiga may not have your entire list data (e.g. how many times you've re-watched a series) due to limitations of MAL API (sigh).

**Comment by MatiasPi** [comment]
I know that this has already been said but I'll emphasize it: **There is no good reason to continue using MAL, or waiting for them to re-enable their API**. **Export your list to Kitsu and use Taiga that way.** I've been using Kitsu for about a month and I can see it has a much better looking website, has all the features MAL has and more, and their API is fully functional. I have not looked back since.

Only problem I had with Kitsu was the simplified ranking system, but I later found out that you can change it to a 10 point system in the settings, just like MAL. It is fully integrated into Taiga as well. I freaking love Kitsu/Taiga.

MAL used to be great, but it is time to move on, sadly.

**Comment by aftadizca** [comment]
Use Anilist now. Good feature..

**Comment by erengy** [comment]
If you have a large amount of changes waiting to be synced with MAL, here's something new you can do:

1. Upgrade to Taiga v1.3.1, if you haven't done so already.
2. Export your anime list via *Tools → Export anime list → Export as MyAnimeList XML*.
3. [Import](https://myanimelist.net/import.php) that file to MyAnimeList by choosing the *MyAnimeList Import* option.
4. Check your online anime list at MAL to make sure it's up to date now.
5. Go to History page of Taiga, right-click on the page, then select *Clear queue → Merge*.

Note that MAL will overwrite the entries you import, and Taiga doesn't have all the data for your list entries (e.g. how many times you've re-watched a series) due to limitations of MAL API. This shouldn't cause any issues for most people, though.

Also make sure to select the *Merge* option rather than the *Delete* option at the final step. Otherwise your local list will lose all the changes you made since MAL API went offline.

**Comment by Kovaelin** [comment]
Another month before we get an update on the API. https://twitter.com/myanimelist/status/1027084541268295681

**Comment by ifonefox** [comment]
There's a little more detail in the forum post:

> **What about the API?**
MAL is concentrating on bringing the site back to its full functionality before work on the API can begin. At this time, the work on the API has not yet been scheduled, but we will provide an update later this month. 


At least its better than radio silence on the API

**Comment by erengy** [comment]
The previously-announced [announcement](https://myanimelist.net/forum/?topicid=1732388&show=500#msg55589890) announces a series of announcements regarding the API in the upcoming weeks:

> We are currently reviewing the steps necessary to complete development of a new API, which would allow third party applications to function again. Up until this point, third party applications have made use of an older API to interface with MAL, allowing them to interact with the site and function. When the API was disabled at the end of May, this caused the majority of third party applications to stop functioning, as they were no longer able to interact with the site.

> At this point we have no other information to share, but aim to provide bi-weekly updates on the situation.

In addition, after 99 days of silence, a DeNA representative brought forward an apology in an internal post, claiming their limited resources in a billion-dollar company as the reason the API was put on-hold for so long. They promised to provide actual new information in time, while mentioning that they do not have a release date for the new API yet. We will see how long it takes for them to deliver.

**Comment by Volatar** [comment]
It's been four months now and the API is still not restored. I was patiently waiting, but I am now done.

As @erengy said

>  a DeNA representative brought forward an apology in an internal post, claiming their limited resources in a billion-dollar company as the reason the API was put on-hold for so long.

When it comes down to it, API users are the absolutely last priority for this kind of company. Facebook revealed for it's IPO that they simply could not figure out how to monetize (via advertising) their mobile users, which had that that time (IIRC) become over 2/3rds of the userbase. API users are even lower on the totem pole. You can _try_ and deliver ads to API users, and the application developers will throw the ads away. Reddit also ran into this problem, and ended up trying to solve it by buying up and killing the largest mobile apps that were using their API. Twitter bought their largest API application so they could put ads in it. They all know they can't fully kill their API's -- no one can if they want the vocal and influential power users that draw others to stick to their service, as such people do not use the web interfaces as a rule, but they can do their best to discourage the common man from such applications.

MAL has gone a step beyond all of those and actually killed their API. Not permanently (or so they say) but I have no faith at this point they actually even want to bring it back.

Thank you everyone for keeping up with this thread and it's discussion.

Today I evaluate the competition and decide where I am moving my database to, and I am not going back.

:wave:

**Comment by moyitpro** [comment]
Actually, there was an update recently regarding the API

> We are currently working a new terms of use for third party application developers. Also, we have mostly finished reviewing all the tasks necessary for completing development. We are planning to start work on the remaining development some time next week.

I wouldn't lose hope yet, but it will be a while and we still don't know if they will restore the beta or not.

**Comment by BlackJoe23** [comment]
Ye also I hate all the other services AI's myanimelist has the most decent desktop friendly one. And the other don't even store your entry update dates and have a shittier database. mal is the most anidb like without being out there to use.

**Comment by Volatar** [comment]
@moyitpro I was directly responding to that terrible ambiguous MAL update on their API

**Comment by timw4mail** [comment]
If you really want MAL updates, and you use Kitsu, you  can enable syncing on your Kitsu account. They use screen-scraping, but their syncing continues to work in spite of the MAL API nonsense.

**Comment by F1r3w477** [comment]
MAL was just acquired by Media Do, while the legal stuff is being worked out DeNA is still doing day to day maintenance and stuff (Source: [MAL Official Twitter](https://twitter.com/myanimelist)), but after that when Media Do takes over, maybe we can all spam the twitter asking for the API to be fixed?

**Comment by moepoi** [comment]
Now i'm using notify.moe and kitsu

**Comment by thoughtsunificator** [comment]
thanks for the link i didnt know notify.moe 

heard of https://jikan.moe/ ?

**Comment by Akamaru** [comment]
The API has been down for 1 year now

**Comment by taigalover** [comment]
An entire 1 year and still nothing on the API, at this point i don't think I'm going back even if the API is restored.

**Comment by ifonefox** [comment]
> An entire 1 year and still nothing on the API
The last comment was "only" about six and a half months ago
https://myanimelist.net/forum/?topicid=1740204&show=400#msg56198138

**Comment by moyitpro** [comment]
I am part of the Slack for MyAnimeList and all I can say is Xinil said that the closed beta is coming soon.

**Comment by Nevalopo** [comment]
> I am part of the Slack for MyAnimeList and all I can say is Xinil said that the closed beta is coming soon.

Closed beta for what?

**Comment by ifonefox** [comment]
I'm assuming its a beta for the new API. Is the slack public, or invite only?

**Comment by ifonefox** [comment]
> Closed beta for what?

"closed beta for the new API"

Is the slack public, or invite only?

**Comment by moyitpro** [comment]
> > Closed beta for what?
> 
> Moyitpro edited their comment and specified its for the new API.
> 
> Is the slack public, or invite only?

it's private, so you have to wait until the public release.

**Comment by ifonefox** [comment]
https://malupdaterosx.moe/2019/06/21/myanimelist-api-update-3/

> At last, the light is at the end of the tunnel. The owners of MyAnimeList will open the API up for closed beta for certain developers soon, which I am a part of. Since the public cannot use the apps that use the API during the closed beta, there will be no public testing for any of the apps nor any public commits pushed to the public repos until it’s made public again. The open beta will happen in September, meaning that there won’t be any public beta builds until then.

**Comment by Kovaelin** [comment]
It's rich that still none of this news is coming from MAL themselves.

**Comment by kiriya-aoi** [comment]
They got around to announcing it themselves. https://myanimelist.net/forum/?topicid=1794878

**Comment by Nevalopo** [comment]
I wonder if @erengy will use MAL's new api. Seems the admins of MAL really want him to use it and invited him to closed beta but as we last saw he said he was done with MAL and would never go back to anything related to MAL. I really hope he changed his mind because Taiga + MAL is best combo.

**Comment by ifonefox** [comment]
> he said he was done with MAL and would never go back to anything related to MAL

That's not exactly what [the post](https://github.com/erengy/taiga/issues/601) said.

> I'm not going to spend any more time working with the old API, checking out unofficial ones, or devising my own workarounds.
> I should note that I'm not burning bridges here. I will certainly reconsider my position, especially if the new MAL API becomes available. 

Then again, that post is from over a year ago, so I don't know if Erengy still feels that way.

**Comment by erengy** [comment]
I've personally moved on from MyAnimeList. I also decided not to support them in any way, until a decent official API becomes available. I put up with their problems for ten years. I say, no more.

But yes, I will be participating in the closed beta. I can't promise anything until actually using the new API. Hopefully we will see a public release in the following months.

**Comment by enzobes** [comment]
Future Plans for a Public MyAnimeList API

https://myanimelist.net/forum/?topicid=1794878&fbclid=IwAR1ubgF3MAsTeCInyDQ_7f1-VoNndyodqFqEswH9goFw92pLPTZZWWrzFn8

**Comment by erengy** [comment]
Closed beta of the new MAL API has begun. It currently lacks some features and has some minor issues, but works better than the old API overall. Several developers including myself are providing feedback on it. We'll see how the new owners will handle things this time around. If all goes well, I'll release a test version of Taiga in the following months, soon after the API goes into open beta.

**Comment by darkred3** [comment]
It's finally time. MAL API is in open beta: https://myanimelist.net/forum/?topicid=1804432

**Comment by erengy** [comment]
I'm about halfway there at implementing the new API to Taiga. Next week, I'll continue from where I left off, then open a new issue to release a test version and collect some feedback.

**Comment by asakurato** [comment]
I'll jump on testing new API right away when test version is released, thanks!

**Comment by tokiioKH** [comment]
Can't wait for the test version to be released :D!

**Comment by Gliscor** [comment]
Glad things are working out!

**Comment by darkred3** [comment]
Really interested in that test version. You got an ETA for the release yet?

**Comment by tophf** [comment]
First MAL will need to make their API public.

**Comment by darkred3** [comment]
erengy is in the closed beta so taiga doesn't need to wait for that.

**Comment by tophf** [comment]
The API was open to the developers, not to the general public. Just because the program's author is able to use it doesn't mean everyone can. We'll need to wait for the API to go public.

**Comment by darkred3** [comment]
Read some of the previous comments. There's already a different app that's gone public and erengy is working on releasing a test version soon.

**Comment by tophf** [comment]
I see, apparently I've mistaken what "public" means in their terminology. They mean it'll be open to those who writes their own apps. Gee, I wonder if more than 3.5 users even need that.

**Comment by erengy** [comment]
Taiga's integration with the new MAL API is done, except for a few issues (e.g. handling of expired tokens and different season intervals). Seeing how things are going, I decided to merge it with v1.4 rather than releasing v1.3.2.

Development on MAL's side is rather slow. I've reported about a dozen issues in the past two months, but AFAIK none have been fixed so far. There isn't even an app management page at their website, so users cannot see or revoke apps accessing their accounts. While the new API is better than the previous one, it's not quite ready for public consumption yet.

I'm currently trying to get them to invite more people to the "open" beta, hoping that it'll speed things up. In the meantime, I'll continue working on some other features of v1.4.

**Comment by darklinkpower** [comment]
at least there's light at the end of the tunnel. I'm not a programmer but I wonder why it took so long to develop the API? Was it something very difficult or did it have to do with something unrelated, like mismanagement of the site?

**Comment by erengy** [comment]
We've been waiting for a better MAL API for almost *ten years*. Can't explain that with technical difficulty, especially since I've personally seen people deploy similar APIs within *a few weeks*.

I believe it was a mixture of the following:

- Changing owners: CraveOnline (2008-2015), DeNA (2015-2019), Media Do (2019-)
- API not being a priority
- Having concerns over API usage
- Being understaffed
- Codebase getting stale and too complex over the years

**Comment by tokiioKH** [comment]
So, basically MAL just messin up then? Any ETA when you are going to push the Taiga v1.4 update?

**Comment by movibeast** [comment]
Any ETA when you are going to release Taiga v1.4 update? I am waiting for the update from last 2 months

**Comment by serjflint** [comment]
@movibeast It was only 2 months for you. Last release 1.3.1 was in 2018. AFAIK there is a huge rework going for the next release. It is not even at alpha stage now.

**Comment by movibeast** [comment]
Yay, that's true. For real?? Wow I am gonna wait for some more time and really excited for new version!

**Comment by bakwas247** [comment]
There's an app called AnYme that just gets you to login to the MAL website and then updates for you that way. Not sure the exact method but you can maybe ask Zunjae on their discord.

**Comment by tokiioKH** [comment]
Any ETA yet for v1.4?

**Comment by xRUSSELL** [comment]
How many times have I checked this Github page since last year! Every time I had my hopes up & after scrolling down my hopes also gets down. Looks like I need to settle down in Anilist because taiga sucks with Kitsu & it doesn't support Simkl. no more waiting for the API but the Taiga v1.4 update. Can't  wait XD

**Comment by crse** [comment]
Sorry for a little bit OOT.
@xRUSSELL Can you explain which part Taiga - Kitsu integration "sucks"?
I'm using it everyday and it works as intended.

**Comment by ifonefox** [comment]
@xRUSSELL Instead of waiting for 1.4 to release, you can compile Taiga yourself. The latest development version supports MAL.
https://github.com/erengy/taiga/wiki/How-to-Compile

**Comment by serjflint** [comment]
@ifonefox on 11/07/2019 erengy said about the development branch.

> It's very much unstable right now. I don't think it's ready even for an alpha release.
Master branch was updated 10 months ago.

**Comment by xRUSSELL** [comment]
> @xRUSSELL Can you explain which part Taiga - Kitsu integration "sucks"?
@ifonefox Sorry I didn't mean that much negative of way with the word "Suck" but I said it because I lose my list in Taiga when I'm offline & I don't lose it with Anylist. 

> @xRUSSELL Instead of waiting for 1.4 to release, you can compile Taiga yourself. The latest development version supports MAL.
Thanks, I will compile Taiga as it seems less hard then waiting XD

**Comment by ifonefox** [comment]
@serjflint Check the "develop" branch (the default).

**Comment by crse** [comment]
@xRUSSELL My friend also experience that bug when using Anilist. It's not Kitsu-specific bug.

**Comment by scese250** [comment]
> Thanks, I will compile Taiga as it seems less hard then waiting XD

did you compiled it? If so, can you share the installer? @xRUSSELL

**Comment by BigPimPimm** [comment]
> @xRUSSELL Instead of waiting for 1.4 to release, you can compile Taiga yourself. The latest development version supports MAL.
> https://github.com/erengy/taiga/wiki/How-to-Compile

I tried this. Every time I try to build the installer I get the same error. 😓
"Error in script "C:\Users\[user]\taiga\setup\Taiga.nsi" on line 128"

Anyone with more success or anyone willing to share the installer?

**Comment by spillerrec** [comment]
Worked fine for me, not sure how I feel sharing the installer when the dev isn't sharing a preview build themselves. (And in general encouraging people to run builds made by untrusted people.)
Line 128:
```
  File "..\bin\Release\Taiga.exe"
```
I think this might be because it has not been build correctly and can't find the file, try to see if you have the `Release/bin/Taiga.exe` file. Note that if you build from Visual Studio, it defaults to the Debug build, so you have to switch it manually to Release.

**Comment by BigPimPimm** [comment]
> Note that if you build from Visual Studio, it defaults to the Debug build, so you have to switch it manually to Release.

Yup, that's exactly what it was. Can't believe I missed that multiple times.
Thanks @spillerrec !

**Comment by erengy** [comment]
Besides what @spillerrec mentioned, third-party developers are required to let MAL know before releasing an application using the new API. So, I'd appreciate it if you don't publicly share any builds of Taiga for the time being.

I've been kind of waiting for MAL to fix the remaining issues with the API, but there hasn't been much progress in the past few months... I think I'll just give up and release v1.4.0-beta as is.

**Comment by scese250** [comment]
It's frustrating waiting more time because I don't like Anilist, guess I'll ask to someone else to compile for me the beta build.

**Comment by tokiioKH** [comment]
Releasing v1.4.0-beta would be really nice.

**Comment by movibeast** [comment]
Yes please release v1.4.0 beta

**Comment by darkred3** [comment]
So I compiled the 1.4.0-alpha but Taiga is showing less than half of all my entries. Is that a known bug?

**Comment by erengy** [comment]
[v1.4.0-beta](https://github.com/erengy/taiga/releases) is now available for testing. See the [changelog](https://github.com/erengy/taiga/wiki/Changelog) for more information.

This is the first public release using the new MyAnimeList API. They haven't fixed the issues I previously mentioned here, unfortunately. But overall it should be in a usable state. Special thanks to @paulo27ms for testing the alpha version.

Note that if you're having trouble viewing MAL's website due to the current [403 Forbidden issue](https://myanimelist.net/forum/?topicid=1841882), you will most likely not be able to use Taiga either.
