### ISSUE TITLE
Allow email address instead of username

### ISSUE THREAD

**Issue by wopian** [erengy/taiga#592]
![](https://i.imgur.com/rGdOhrB.png)

This string appears to be reused for all 3 services, however your email is the primary way for users to login on Kitsu - particularly with new users (after the display names feature rolled out several months ago)

Their profile URL (previously their username before the display name feature) also works for login, but this isn't asked to be filled in on registration for some reason.

Related: #589

**Comment by Koverpih** [comment]
Thought the reason for not allowing email in the first place to reduce user data needed and also protect privacy more stringently... 
I haven't verified my thinking: By this rationale, shouldn't user ID (as mentioned in #595) be a superior method of authenticating for Kitsu?

**Comment by erengy** [comment]
Taiga now asks for your email address instead of your username for Kitsu:

![kitsu-account](https://user-images.githubusercontent.com/1078430/40905510-ce123304-67e6-11e8-9e8d-171ee6544905.png)

Email address of existing users will be automatically retrieved from Kitsu, once they upgrade to v1.3.1.

Taiga also makes use of your display name now (e.g. in main window title). You can test it in the [latest build](http://taiga.moe/latest.html).
