### ISSUE TITLE
Prefer highest video resolution available

### ISSUE THREAD

**Issue by andrew-stclair** [erengy/taiga#602]
so for example, i want the highest quality available. so if 1080p is available, go for it, if not, 720p, if not 480p etc...

is this a possibility in the future?

**Comment by erengy** [comment]
It cannot be done with a single filter/condition, but you can create multiple filters for the same effect:

```
Filter name: Prefer high resolution
Condition: Episode video resolution | is greater than or equal to | 1080p
Action: Prefer matched items to similar ones
```
```
Filter name: Prefer normal resolution
Condition: Episode video resolution | is greater than or equal to | 720p
Action: Prefer matched items to similar ones
```

This is, of course, not a feasible solution for limited filters.

**Comment by OrangeFlavored** [comment]
Been using a similar filter to accomplish this for a while now, one problem though is that if 720p gets posted before 1080p it will often grab both.  Might be useful if you could set a filter so that it will only download if it doesn't find anything better within X amount of hours after it was first found, to get around problems like this.

**Comment by OrangeFlavored** [comment]
As long as you use the "use this fansub group for this anime" context option from the torrent search menu it seems like it includes resolution in the filters now too.  Just noticed this when I was gonna suggest something else which probably not needed now so deleted the other thing...
