### ISSUE TITLE
"Fix" sortByListProgress

### ISSUE THREAD

**Issue by vendethiel** [erengy/taiga#61]
Currently, sortByListProgress will put the currently-airing animes before the finished ones.
I don't think it makes sense: I want my "progress" sorting to be only dependant on progress (and have everything else used in tie-breaking); not the availability of new episodes or whatnow (else I'd sort by something else, I guess).

**Comment by erengy** [comment]
Should be "fixed" with 546c7b8864efba3e18f49b8e731ad7fd1bf1733c. The sorting algorithm had already used ratios rather than flat numbers, but they were calculated differently than the ratios that are used to draw progress bars. Now they're the same, and series with available episodes are no longer put in front of others.

**Comment by vendethiel** [comment]
Amazing, thanks!
