### ISSUE TITLE
AniList support

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#62]
https://github.com/Josh-Star/AniList-API-Docs

Doubt this is even the right place to mention this. But yeah, implementing it would be really easy.

Josh is in the process of updating the docs.

**Comment by Josh-Star** [comment]
[API docs](http://anilist-api.readthedocs.org/en/latest/) are now complete and API is pretty much stable with no real breaking changes being planned.

**Comment by Diablofan** [comment]
@Josh-Star, bumping again to try to revive this, but the API for AniList is stable right? I saw you commeted before, but at the time it didn't seem it had seen too much usage besides testing, now that its been out for 4-5ish months, you think the API is stable enough for Taiga to use safely? If it is I can try to start working on AniList for the next release.

**Comment by anon-e-moose** [comment]
Was just thinking about anilist support today. Glad it's already been put out there. Bumpin' because I want this.

**Comment by themoocow** [comment]
signed up to +1 this, would love anilist support <3

**Comment by nexia29** [comment]
+1 here too. Anilist is definitely better than MAL in a bunch of ways in my experience, and if Taiga supported Anilist, I'd probably stop using my MAL account altogether.

**Comment by SkepticalsArctic** [comment]
I would also like this to happen, Taiga is actually the only reason I'm not using AniList instead of MAL

**Comment by tuur29** [comment]
Looking to make the switch as well, would also like to see this added

**Comment by Statharas** [comment]
People still want this...

**Comment by Josh-Star** [comment]
Adding AniList support to taiga would be a fairly big task, especially considering we have a fair few additional features which would need to be supported (multiple score types, custom lists, etc). With no updates from @erengy in over a year I can only assume that this is unlikely the happen any time soon, if at all. 

So I will say that there is a desktop client very similar to taiga, but with just AniList support, [Shinjiru](http://app.shinjiru.me/features.php) [(github)](https://github.com/Kazakuri/Shinjiru).

**Comment by Diablofan** [comment]
I was planning on working on it as soon as I got a reply from you @Josh-Star but I never got a reply to my previous question on if the API is stable or not. I didn't want to spend too much time working on it before the API was completely stable as I didn't want to change too much of my work to make it work with the newer API versions.

If it is stable, I'll make a fork and working on it in a development branch for AniList support, probably called wip-AniList or something. Might not see too terribly much activity because I have school, but I do plan on working on it.

**Comment by Josh-Star** [comment]
Oops my apologies for my previous comment and lack of reply then, I though at some point I did make a reply about the API stability but I must be getting that mixed up with something else, very sorry!

API v1 is stable, no breaking changes are planned for this version. However we are [planning an API v2](https://github.com/Josh-Star/AniList-API-Docs/issues/63), but that won't be coming out for a fair while, its up to you whether you want to wait or not. I can't be completely sure but I do imagine API v2 is primarily going to be bug fixes and additional features so the upgrade from API v1 shouldn't be too bad.

**Comment by Diablofan** [comment]
On Tuesday, January 12, 2016 06:45:34 PM Josh Star wrote:
> API v1 is stable, no breaking changes are planned for this version. However
> we are [planning an API
> v2](https://github.com/Josh-Star/AniList-API-Docs/issues/63), but that
> won't be coming out for a fair while, its up to you whether you want to
> wait or not. I can't be completely sure but I do imagine API v2 is
> primarily going to be bug fixes and additional features so the upgrade from
> API v1 shouldn't be too bad.

Okay, I guess I could start work then. Hopefully APIv2 won't break v1 usage 
too terribly then. Since development of Taiga frankly seems slow (no offense) 
I really wanted to make sure, that before using it, that the API wouldn't 
break any time soon, and wouldn't break in ways that break Taiga from using 
properly working with AniList.

Hopefully I find some time in the coming weeks to start. School just started 
for my again so I don't have a lot of time now, plus weekend is busy with a 
convention going on I'll be attending. Probably next week is when I'll start 
work on it, won't be a while before I push anything public I think.

**Comment by Statharas** [comment]
We'd be willing to test out features as you develop the fork.

**Comment by Diablofan** [comment]
Alright, so I've started work on AniList support. I won't push anything to my repo until I get at least 3 or 4 of these working.
- [ ] Login
- [ ] Synchronize List
- [ ] Display List
- [ ] Detail View
- [ ] Search
- [ ] Add Entry
- [ ] Remove Entry
- [ ] Update Entry
- [ ] 100 Point Scale
- [ ] 10 Point Decimal Scale
- [ ] 5 Star Scale
- [ ] 3 Smilie Scale

By default Taiga uses a 10 point scale because of MAL and Hummingbird, so Display List, if no other Scale item is checked, will **only** support 10 point integer scale. Most of this list is fairly straight forward I think. Once I get back into AniList I can do more testing. I can probably get some bits of code fixed, but until I can get in and test, don't expect much progress frankly.

The most painful thing to get Taiga to support will probably the various scales that AniList support, mainly the 5 star and 3 smile support. The scale support would also be a slightly invasive UI change so this will only happen with 1.3 because of this. So those will probably be the last ones I work on before requesting a merge.

**Comment by Dormanil** [comment]
So... @Diablofan, did any progress in the quest for AniList support happen?

**Comment by Diablofan** [comment]
Oh wow, its been over a year already hasn't it. I've been busy with school and work, so I haven't had too much time to work on this feature. I'll see what I can do to push it forward more without disturbing too much of what @erengy is doing with #316 (shouldn't be hard to do).

**Comment by erengy** [comment]
It'd be nice if we could get this done before or within the upcoming beta period and release v1.3 with Kitsu *and* AniList support.

@Diablofan For now, don't bother with the UI (e.g. adding a new page to *Settings* → *Services*), AniList-specific things (e.g. custom lists, different scoring systems) or even the Seasons page. Let's try to get the basic request builder and response handler functions (i.e. `src/sync/anilist.cpp`) working first, for the following request types:

- `kAuthenticateUser`
- `kGetLibraryEntries`
- `kGetMetadataById`
- `kSearchTitle`
- `kAddLibraryEntry`, `kDeleteLibraryEntry`, `kUpdateLibraryEntry`

**Comment by Diablofan** [comment]
Okay, I figured some of the more UI facing changes would have to wait anyway.

**Comment by erengy** [comment]
AniList's new API is [going stable soon](https://github.com/AniList/ApiV2-GraphQL-Docs/issues/2#issuecomment-342381907). I gave it a try today, and I was able to get the most basic functionalities (retrieving anime list and information) working within a few hours.

@Diablofan If that's all right with you, I'll continue from here.

**Comment by Diablofan** [comment]
Yeah that's fine. I haven't had much time to actually work on it. Work has been keeping me plenty busy.

**Comment by erengy** [comment]
`anilist` branch is now [merged](https://github.com/erengy/taiga/commit/222bb9ad80efdb13762a019714e11a0e9ef959ee) into `develop`.

I haven't done much testing yet, but the next release (v1.3.0-beta.2) will support AniList.

**Comment by erengy** [comment]
[v1.3.0-beta.2](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta.2) is now available with AniList support.

**Comment by Statharas** [comment]
Took only three years. Worth every minute of waiting.
