### ISSUE TITLE
Discard 720p if higher resolution exist but if not show 720p.

### ISSUE THREAD

**Issue by Tensai-Otaku** [erengy/taiga#622]
Is it possible to make a condition like that?

**Comment by erengy** [comment]
See #602.

**Comment by Tensai-Otaku** [comment]
I see, I am doing it like that but it's not working properly. It chooses both 720p and 1080p and not one of them depending on which has highest priority.

**Comment by erengy** [comment]
Ignoring any other filter you may have, the filters I mentioned there should have the following effect:

- `[A-Subs] Anime - 01 [1080p].mkv` *(n/a)*
- `[A-Subs] Anime - 01 [720p].mkv` *(discarded)*
- `[A-Subs] Anime - 01 [480p].mkv` *(discarded)*
- `[B-Subs] Anime - 01 [720p].mkv` *(n/a)*

In other words, only the releases of the same episode from the same group are affected. You'll still have to have a separate limited filter to choose `A-Subs` or `B-Subs`.

(I'm closing this issue because it's the same as #602.)
