### ISSUE TITLE
Anime not showing up in the "Now Playing" section

### ISSUE THREAD

**Issue by ArgjendZ** [erengy/taiga#637]
I recently switched from MAL to Anilist in Taiga, exporting and importing my anime list. So good so far, but when I download a new episode of an anime for some reason it doesn't show up in the "Now Playing" section like it used to. I'm pretty sure it Taiga recognizes the new episodes by the dark green line the anime's have underneath in the "Currently watching" tab, but yet it doesn't show it on "Now playing", despite it saying "There are at least 6 new episodes available in library folders", where I have downloaded like 3 of them.

**Comment by erengy** [comment]
You mean the links under Continue Watching, right? That list is derived from your local History, which is kept separately for different services. Since you switched to AniList, Taiga is no longer aware of your recently-watched episodes. You'll have to watch some episodes first so that Taiga can repopulate the list.
