### ISSUE TITLE
strange deselect torrent behavior

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#642]
i try to describe the happening.

i go to torrent tab and see new episode(new season anime) are available and selected.
i press refesh before i klick download because i though there might be more releases but what happened was the selected files(anime) got deselected. it doesnt even give me alternative file selected.
although i got other new anime selected. but still if you dont watch out you could miss some releases.

is this helpfull to fix this bugg?

**Comment by erengy** [comment]
It's technically impossible for the same filters to produce different results under the same conditions.

If you're sure the exact same files got deselected, then something (e.g. your filters, your list, available episodes) must have changed in between. For example, if you watched a new episode and updated your list, Taiga could discard torrents for that episode next time you check for new releases.

Otherwise, perhaps it's been a while since the last time you refreshed the feed. When you did, you got different releases. This isn't a bug, it's just how RSS feeds work: They only return the latest (e.g. 50) releases.

**Comment by amboris** [comment]
guess its been a while and the other file got pushed out :(
