### ISSUE TITLE
'Now Playing' tab needs a scroll bar.

### ISSUE THREAD

**Issue by Kevvvn** [erengy/taiga#65]
With enough list entries and/or small enough screen you can't see all the information even when maximizing the window. 
![example](http://puu.sh/dxUEF.png)

**Comment by erengy** [comment]
I tried this out in the past. Twice. It turned out to be ridiculously hard. I gave up. :hurtrealbad:

Now Playing page feels like a placeholder at the moment, and I almost hate how it looks. I intend to make it look and behave a lot nicer, but again, it requires a huge amount of unpleasant work with the current UI framework Taiga is built upon. So, I decided to postpone the change until v2.0 arrives.

I'll close this issue, but I wholeheartedly agree that Now Playing page needs more love.
