### ISSUE TITLE
some torrent filter bugg

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#659]
I have the default filters on. Didn't change anything. there is a few problems I encounter regularly

*it happens from time to time that some torrents don't get selected to download when there is a release  or new out. especially when it's the first episode or a movie. (it is not grayed out, which mean it does somehow recognise the anime, but won't select it automatically for download) resent event with the gozilla movie release

*the filter "discard watched and available episode" won't gray out animes releases I completed or dropped

*there is no option to handle batches or volume releases. I get those selected even when they don't match the episode count I currently am :/

**Comment by asakurato** [comment]
1. Are you sure those anime are on your list? Default filters should select only anime that are on your list.
2. Double click the filter and try changing "Match" to "any condition".
3. There is option to limit torrent by sizes. Discarding batches entirely is not possible, because there is no such information coming from RSS feeds.

**Comment by amboris** [comment]
1. yes 100% as it was not grayed and i even checked the status.(planed to watch)
2. by default it is any condition
3. not possible to make a filter that filter out files that names or descriptions are "*batch*" and "*vol.*"?

**Comment by erengy** [comment]
Default filters are a good starting point, but they're not sufficient for serious use, especially if you want automatic downloads. There's no "bug" here, you just haven't set up your filters properly. If you can't make it work, try disabling the default filters that select all releases for multiple anime, then create limited filters for individual anime.

> some torrents don't get selected to download when there is a release or new out. especially when it's the first episode or a movie. (it is not grayed out, which mean it does somehow recognise the anime, but won't select it automatically for download)

Can't say anything without knowing your exact filters and the exact releases in question. There can be many reasons for why they weren't selected or why they were discarded.

> the filter "discard watched and available episode" won't gray out animes releases I completed or dropped

That filter works on episode numbers rather than your list status. It discards some releases, but doesn't gray them out (unless you modified the filter to deactivate discarded items). See #618 for dropped anime.

> there is no option to handle batches or volume releases. I get those selected even when they don't match the episode count I currently am :/

> not possible to make a filter that filter out files that names or descriptions are "*batch*" and "*vol.*"?

See [here](https://twitter.com/taigaapp/status/716472914451816449).
