### ISSUE TITLE
Progress exceeds Episodes count

### ISSUE THREAD

**Issue by subnet-** [erengy/taiga#667]
I've got this problem on Shingeki no Kyoujin S3 on Kitsu.  
Horriblesubs lists S03E01 as S01E38, taiga shows it as S03E01, but updates it as E38.
Taiga:
![image](https://user-images.githubusercontent.com/8416994/43372016-b38c6dc4-939c-11e8-855f-5e15d6cd60f5.png)
Kitsu:
![image](https://user-images.githubusercontent.com/8416994/43372061-d793ba4c-939c-11e8-948d-159816c3a7cd.png)

Is this a problem with Taiga or Kitsu?

**Comment by erengy** [comment]
Normally neither Taiga nor Kitsu allows updating the episode number beyond the last one. But the total number (24) was unknown at the time you watched the first episode, which is why you could update your progress to 38.

Taiga uses [a special database](https://github.com/erengy/anime-relations) to handle the case where fansub groups use continuous numbering scheme in their releases. Again, you probably watched that episode before *Shingeki no Kyojin Season 3* was [added](https://github.com/erengy/anime-relations/commit/f9a05f00ac99f5d701ee633275bd0b959700a278) to the database.

Change your progress from 38 to 1, use *Help → Check for updates* to fetch the latest anime relations in case Taiga hasn't got them already, then you should be fine for the upcoming episodes of the series.
