### ISSUE TITLE
Support for Funimation?

### ISSUE THREAD

**Issue by vhammer-tgm** [erengy/taiga#668]
Since I sometimes stream dubbed shows on Funimation support for it would be awesome!

Thank you for the great application either way!

**Comment by erengy** [comment]
Quoting from the [FAQ page](https://taiga.moe/#support):

> **Could you add support for other streaming sites?**
>
> As long as the site provides a consistent way to detect the anime title and the episode number in its URL or page title, it's possible. Some services such as **Funimation**, Hulu and Netflix aren't supported because it's technically not possible to detect the episodes this way.

It's been a while since I checked their website though, and I can't access it at the moment. Could you write down the address and the page title for an episode there?

**Comment by MinkiNTN** [comment]
I'm using Karakai Jouzu no Takagi-san Episode 1 as an example:

Page URL: ```https://www.funimation.com/shows/karakai-jozu-no-takagi-san/eraser-day-duty-funny-face-one-hundred-yen/```

Page Title: ```Watch KARAKAI JOZU NO TAKAGI-SAN Season 1 Episode 1 Anime on Funimation```

Episode Title: ```Eraser / Day Duty / Funny Face / One Hundred Yen```

**Comment by erengy** [comment]
@MinkiNTN Thanks! Could you try out the [latest build](https://taiga.moe/latest.html) and see if it can detect Funimation?

**Comment by MinkiNTN** [comment]
@erengy The latest build detect Funimation just fine. Just some nit-picking stuff: 

- Taiga tries to identify "show pages" (the pages where it shows the description, episode listings and what not) as an episode and complain that it can't find a show with that info.
- When I tried playing Takagi-san, it failed to detect the show and give me a list with Takagi-san as the first suggestion. At first, I thought because it tried to match "KARAKAI **JOZU** NO TAKAGI-SAN" against "KARAKAI **JOUZU** NO TAKAGI-SAN" and failed, but after manually clicking on the show name, the English one in there matched with "JOZU" so I don't know why it failed. After that one time it doesn't fail anymore.

Again, those are just me nit-picking. Taiga detects Funimation and track the information correctly.

**Comment by vhammer-tgm** [comment]
I was away so I completely missed the discussion here but thanks so much for the prompt replies!
