### ISSUE TITLE
mIRC sharing problems

### ISSUE THREAD

**Issue by iShyboy** [erengy/taiga#67]
It keep spamming to every channel open.
When like this http://i.imgur.com/mkeTZVP.png it share for everyone
When like this http://i.imgur.com/tvXuYem.png only for myanimelist
And when like this http://i.imgur.com/uGm4NGf.png send to all channels again.
Something like malup sounds cool. e.g http://i.imgur.com/ateTvd1.png

**Comment by erengy** [comment]
Looks like [this bug](https://github.com/erengy/taiga/commit/8025d9bc01016439644636ce96e30f923c86824a#diff-67878f3c0b7cc57967a39f2b6322aac0L67) has been around for about a year now. The fact that you're the first one to report makes me wonder if anyone else is using this feature. :worried:

Anyway, it should now be fixed with bfebdc4948ffdd1f7cd67ebde69cad9cc5c2a92b. I'll look into adding channels to the menu in the future.
