### ISSUE TITLE
Next airing episode dates are incorrect

### ISSUE THREAD

**Issue by rld243** [erengy/taiga#674]
Latest git version (d560f4d)

Example: Chuukan Kanriroku Tonegawa
![airing](https://user-images.githubusercontent.com/34302354/43954243-5567daae-9cce-11e8-9832-f93f7ccfb86b.png)

The MAL pages says the show airs at wednesdays at 01:59.

My guess the problem is that Taiga assumes airing dates as UTC+0 and then applies user's timezone offset (UTC+8 for me). Actually, airing dates are UTC+9 (Japan Standard Time). So in my timezone it should be Wednesday 00:59 (offset -1).

**Comment by erengy** [comment]
According to AniList (where Taiga gets the airing time from), episode 7 of the series airs at `1534265940`, which is `2018-08-14T16:59:00` (UTC+0). It seems Taiga's adding 17 hours to that, rather than 8 hours for your timezone.

47e2cde27c08f57703af5f7b590edbe12f273a21 should fix the issue, for the most part. But it might still be off by one hour due to some miscalculation of daylight saving bias.

**Comment by rld243** [comment]
Thanks! Times are displayed correctly now.
