### ISSUE TITLE
Failing Recognition

### ISSUE THREAD

**Issue by kobini2** [erengy/taiga#677]
Hello

I just noticed that my anime is wrongfully being recognized.

Anime: [Senjou no Valkyria: Gallian Chronicles](https://anilist.co/anime/5507/Senjou-no-Valkyria-Gallian-Chronicles/)

![taiga_2018-08-14_19-53-50](https://user-images.githubusercontent.com/7302579/44108917-072f86d0-9ffc-11e8-9f42-c25d4c3c4176.png)

- Taiga 1.3.1
- Windows 10 Pro (10.0.17134)
- VLC media player 3.0.3

**Comment by erengy** [comment]
Hi @kobini2,

This is likely the same issue as #628, only for a different release. See my last comment there for the details.

**Comment by kobini2** [comment]
It indeed seems to be the same problem.

Could you maybe make an option to disable recognition on a specific series?

**Comment by erengy** [comment]
I'd rather not add an option for that. I'd suggest one of the following:

- Temporarily disable anime recognition from Tools menu while you're watching that particular series.
- Watch that series on a different media player, as this issue seems to only happen on VLC.
- Download a different release for the series, as this issue likely happens due to misconfigured files by that release group.
