### ISSUE TITLE
Progress bar is displayed incorrectly when there are “too many” episodes available

### ISSUE THREAD

**Issue by Yuubari** [erengy/taiga#68]
Mushishi Zoku Shou is often considered one season and most groups number the episodes sequentially. When I have more than the MAL-reported number of episodes present in the anime series' folder, Taiga draws the light grey bar a bit too far:
![1419155807](https://cloud.githubusercontent.com/assets/7750448/5517819/07fac1b0-8912-11e4-9ce6-240f51950c03.png)

This happens when the series in question is highlighted. When it's not, the bar is still wrong but is obscured by the score and type columns:
![1419156212](https://cloud.githubusercontent.com/assets/7750448/5517820/0b20c524-8912-11e4-8b33-f44932306943.png)

**Comment by erengy** [comment]
Hi there @Yuubari,

I'd say this is impossible, because episode numbers are always [compared](https://github.com/erengy/taiga/blob/e2cff89f7223d74c1fa11627e2d613eed714ab9c/src/library/anime_item.cpp#L557) against the total episode count before being set as available, and `22 <= 10 || 10 == 0` should never yield `true`. Yet weird things in programming happen all the time, so I tried it out myself but still couldn't reproduce the issue.

Could you tell me the filenames in question? Do you have any alternative titles (e.g. "Mushishi S2") set up for the series? Any additional information would help.

**Comment by Yuubari** [comment]
File listing:
```
[Vivid] Mushishi Zoku Shou - 01 [8902B060].mkv
[Vivid] Mushishi Zoku Shou - 02 [6E0930E7].mkv
[Vivid] Mushishi Zoku Shou - 03 [4553DD44].mkv
[Vivid] Mushishi Zoku Shou - 04 [F7AB09E3].mkv
[Vivid] Mushishi Zoku Shou - 05 [C0D8C172].mkv
[Vivid] Mushishi Zoku Shou - 06 [EB52DFA3].mkv
[Vivid] Mushishi Zoku Shou - 07 [73B6AC67].mkv
[Vivid] Mushishi Zoku Shou - 08 [35ADEA29].mkv
[Vivid] Mushishi Zoku Shou - 09 [DE04C5DF].mkv
[Vivid] Mushishi Zoku Shou - 10 [56F65413].mkv
[Vivid] Mushishi Zoku Shou - 11-12 - Odoro no Michi [473403E4].mkv
[Vivid] Mushishi Zoku Shou - 13 [123088F5].mkv
[Vivid] Mushishi Zoku Shou - 14 [5E64C05B].mkv
[Vivid] Mushishi Zoku Shou - 15 [913C2F2C].mkv
[Vivid] Mushishi Zoku Shou - 16 [F781D7DA].mkv
[Vivid] Mushishi Zoku Shou - 17 [E118C325].mkv
[Vivid] Mushishi Zoku Shou - 18 [A14664C5].mkv
[Vivid] Mushishi Zoku Shou - 19 [9D42303E].mkv
[Vivid] Mushishi Zoku Shou - 20 [45C72B22].mkv
[Vivid] Mushishi Zoku Shou - 21 [B8C8FF5A].mkv
[Vivid] Mushishi Zoku Shou - 22 [60B7FF77].mkv
```

Settings:
![Settings](https://cloud.githubusercontent.com/assets/7750448/5599204/463b1a9e-9306-11e4-993e-f692976050f6.png)

**Comment by erengy** [comment]
I couldn't reproduce with the same files and settings either. The change in a6f15546ba9c196ee664bef385411df413d7bcf9 will at least get rid of the visual bug, though.

**Comment by Yuubari** [comment]
Built it on my laptop and It's indeed fixed; Taiga also no longer shows that there are unwatched episodes available for Mushishi Zoku Shou S2.
