### ISSUE TITLE
Taiga won't recognize the current episode I'm watching

### ISSUE THREAD

**Issue by DMGDMG1** [erengy/taiga#683]
It only happens when I'm watching Detective Conan, instead of recognizing the actual episode, it says I'm watching episode 1, as you can see on the screenshot attached. It happened when I started "season 21" and the episode titles changed, I tried adding the alternative title but it didn't work, I also tried to set the location to the Season 21 folder. Anything else I should try?
<img width="823" alt="captura" src="https://user-images.githubusercontent.com/42512914/44308338-f635e200-a3b3-11e8-8011-de88d47cdb41.PNG">

**Comment by taigalover** [comment]
Maybe you could try putting the season name and episode number into the folder name?
Like "S21E01" and "S21E02" and S21E03" and so on....
Hope this helps.

**Comment by such-doge** [comment]
This is an issue with how your files are named. There is no way to write a rule that accurately guesses that "Detective-Conan-656" is episode 656 of a show named "Detective Conan" and not a show named "Detective Conan 656", because there are shows with numbers at the end of the name, like "Galaxy Express 999". Right now it says episode 1 because it sees "Part 1" at the end and assumes that is the episode number. You need to rename your files. Try [BRU](https://www.bulkrenameutility.co.uk/Main_Intro.php).

**Comment by erengy** [comment]
Those files are using mixed delimiters for no reason, which confuses Taiga's filename parser. It's not possible to resolve this on Taiga's side. Renaming the files in the following manner should work:

Original: *(Bad. Dashes are almost never used in this way.)*
`Detective-Conan-656 Professor's Video Site (Part 1)`

Renamed: *(Still bad, but Taiga could handle this.)*
`Detective_Conan_656 Professor's Video Site (Part 1)`

Better: *(Consistent separation)*
`Detective Conan 656 Professor's Video Site (Part 1)`

Even better: *(Semantic use of dashes)*
`Detective Conan - 656 - Professor's Video Site (Part 1)`
