### ISSUE TITLE
Torrent with custom RSS Filter Rule

### ISSUE THREAD

**Issue by Punllarena** [erengy/taiga#689]
I'm using shanaproject RSS to filter my torrents then I input it as the source for checking new releases in Taiga for the convenience of putting the anime in the folders, I realized that Taiga was discarding some of the anime I ticked follow in Shanaproject yet wasn't included in my anilist because I only had the Default filters on. It was my fault for not checking the latest episodes but I'm just submitting this for a suggestion.

My current solution to it is making a custom filter where they select file category anime/batch/other.

**Comment by erengy** [comment]
I'm not sure if I understand the problem or the suggestion here. It's true that the default filters discard torrents for not-in-list anime, as most users will not be interested in them. You're welcome to modify the filters according to your use case.

Are you saying that you need a filter to select all torrents in a feed, because that feed is already customized to your needs? You can probably use any element to create such a filter. I think the easiest solution would be to create a filter with a single `File name | is not | (empty)` condition.

**Comment by Punllarena** [comment]
yes. my feed is already customized. thanks for your input, that's what I need.
