### ISSUE TITLE
How long does it take for a torrent to disappear from "Torrents" tab?

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#694]
i couldn't come up with better title, sorry for that. So basically what I'm asking is: Let's assume I watch 1 seasonal show and I use Torrent downloading feature of the app. When the episode is released on Nyaa (or the feed you are using), it's added to the tab on manual or scheduled refresh. But, if you for example do not download said episode for unknown time, it won't show up anymore no matter what you do (unless you disable all the filters). So my point is, what is this time when you no longer get to download the episode? I'm sure there is no filter to control that and there is no such option in the settings. Can we maybe have a feature to extend this time or somehow control it otherwise?

**Comment by slevir** [comment]
Short answer: we can't do that because search results are at complete mercy of the site you're using, Taiga simply displays them

Long answer: basically, how feeds on nyaa work is displaying X last torrents on the site, after processing the filters. So, when one new matching torrent appears, the last one gets ejected. Because of this, there's no way to predict when one particular torrent gets ejected, because it depends on how fast new ones are added.
