### ISSUE TITLE
Update failed to Kitsu

### ISSUE THREAD

**Issue by Andis59** [erengy/taiga#697]
When I update a anime or sync with Kitsu I get this error:

Update failed: Kitsu returned an error: "Internal Server Error: Internal Server Error"

The error has started yesterday or the day before(today is 2018-09-12).

What is the problem?

Edit: I have already reported this at the Kitsu Bug list, but they just closed and referred me here...

Edit2: Just realized that there is a log. It's full of lines like this

> 2018-09-12 18:51:49 [Error] http.cpp:94 taiga::HttpClient::OnError | >>
> HTTP error #6: Couldn't resolve host name (kitsu.io)
> Connection mode: 9

**Comment by erengy** [comment]
`Internal Server Error` means Kitsu was unable to process your request due to an issue with their server. Otherwise you'd see a more meaningful error message. It might be that they recently changed something in their API. I'll try to figure out the cause and report it to Kitsu devs. For now, you can try clearing your update queue: Go to *History* page of Taiga, right click on the page, select *Clear queue* and then *Delete*.
