### ISSUE TITLE
Not recognising JoJo

### ISSUE THREAD

**Issue by BradleyDS2** [erengy/taiga#717]
I haven't noticed this with other anime, but JoJo's Bizarre Adventure: Golden Wind isn't being recognised.

I have it saved in a folder called JoJo's Bizarre Adventure (2012) and the episodes are named like the following "S04E01 - Golden Wind.mkv".

I've set the folder for it in taiga, and if I right click and open the folder it opens properly.

I think this may be due to different seasons having different names, but A Certain Magical Index III is recognised, and it's in a folder named "A Certain Magical Index" with the files being named like "S03E01 - Chaos.mkv" Same with Railgun S being prefixed with S02 in a folder named "A Certain Scientific Railgun"

Is there any way around this other than making new folders for specific problematic anime, instead of storing different seasons together in one folder?

I am currently using Taiga 1.3.1

**Comment by erengy** [comment]
When Taiga can't identify the filename alone, it tries merging the filename with its parent directory and look that up as well (e.g. `A Certain Magical Index` + `S03E01 - Chaos`, although the process is a bit more involved than that).

In your case, adding `JoJo's Bizarre Adventure S4 (2012)` as an alternative title to the new series should work. You can write `4`, `IV`, `Season 4`, etc. instead of `S4` and it will work the same.

**Comment by BradleyDS2** [comment]
Alright, thank you. I shall do that. 

Am I correct in assuming there's no plans to add support for special cases such as these?

**Comment by erengy** [comment]
I don't think there's any other way Taiga could have handled your case.

**Comment by BradleyDS2** [comment]
Alright, thank you.
