### ISSUE TITLE
HTTP error #60: Peer certificate cannot be authenticated with given CA certificates 

### ISSUE THREAD

**Issue by REDRANGA** [erengy/taiga#747]
2019-01-28 14:57:49 [Error] http.cpp:94 taiga::HttpClient::OnError | >>
HTTP error #60: Peer certificate cannot be authenticated with given CA certificates
Connection mode: 11
2019-01-28
![http error 60](https://user-images.githubusercontent.com/47096610/51814839-5f316680-2311-11e9-9e29-b62405ab8fb8.PNG)
This error only happens when i try to search for torrents

**Comment by erengy** [comment]
You can try this for starters:

1. Go to _Settings_ → _Advanced_ and set _Application / Disable certificate revocation checks_ to `true`.
2. Restart Taiga.

If that doesn't work, replicate the issue in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) so that we can look for additional clues in the log file.

**Comment by wopian** [comment]
Nyaa and many others got blocked by Australian ISPs at the start of this year.

https://torrentfreak.com/australian-court-orders-isps-to-block-181-pirate-domains-including-subtitle-sites-181220/
