### ISSUE TITLE
Taiga doesn't torrents download automatically.

### ISSUE THREAD

**Issue by cartals** [erengy/taiga#750]
Hi, taiga doesn't download torrents automatically. I use nyaa's rss feed. I check new torrents but it doesnt download just marked. (sorry for bad eng.) I can tell my problem with Turkish.
Turkish: @erengy  Abi taiga'da ki şu ayar açık "Download immediately" nyaa'nın rss feed'ini kullanıyorum fakat otomatik yüklemiyor sadece işaretli bırakıyor ne yapmalıyım ?

**Comment by erengy** [comment]
If you let Taiga check for new torrents every 60 minutes, it will automatically download the ones selected by your filters. If you *manually* check for new torrents via the Torrents page, Taiga will just display them rather than automatically downloading them.

(Taiga her 60 dakikada bir torrentleri kontrol ettiğinde, filtrelere uyanları otomatik indirir. Torrents sayfasından sen kendin kontrol ettiğinde ise otomatik indirmez, sadece sayfada listeler.)

**Comment by cartals** [comment]
Okay it worked sorry for annoying you. TR: İşe yaradı abi sağolasın uğraştırdım kusura bakma
