### ISSUE TITLE
Taiga somehow doesn't detect certain episodes with full name but does with shorter

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#758]
https://youtu.be/OxXyi-SaMVk

Searching for Kaguya's full name gives raws. Cutting it down to less characters starts showing more episodes.

**Comment by erengy** [comment]
Quoting myself from #711:

> Search results depend on the search algorithm of the torrent site you selected. Taiga simply passes on your query, retrieves the results, tries to identify them and applies your filters.

Searching for `Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen` will of course return less results than searching for `Kaguya-sama wa Kokurasetai` or just `Kaguya-sama`, because the full name isn't used in most releases.

To see more releases, go to *Anime Information* → *My list and settings*, enter `Kaguya-sama wa Kokurasetai` as an alternative title and enable *Use the first alternative title to search for torrents* option.
