### ISSUE TITLE
HTTP error #28: Timeout was reached

### ISSUE THREAD

**Issue by inexplicabro** [erengy/taiga#766]
I use taiga to update kitsu. It has been working until today, with this error: 

`HTTP error #28: Timeout was reached`

**Comment by inexplicabro** [comment]
sorry, the problem is at kitsu's end

**Comment by TheMerricat** [comment]
For those who are looking for answers beyond that it's not Taiga's issue - Kitsu is down because they ran out of money and couldn't pay their bills. They are currently running a donation drive and on Discord at least they sound as if they are on track to be able to pay off the bill soon. But all the same you might want to be exporting your lists for import elsewhere, just in case.
