### ISSUE TITLE
Taiga won't open

### ISSUE THREAD

**Issue by zZLord** [erengy/taiga#770]
I need help, I've tried reinstalling it.

The Procmon's log is attached here:
[Logfile.zip](https://github.com/erengy/taiga/files/3036698/Logfile.zip)

**Comment by zZLord** [comment]
Is there someone willing to help me please?

**Comment by kayabe** [comment]
did you try run as admin?

**Comment by zZLord** [comment]
Yes, I did try run as administrator. Also tried doing what you said, but it didn't work

**Comment by kayabe** [comment]
in that case you might have to try and compile the debug version

**Comment by erengy** [comment]
What do you see when you run Taiga? Does a Taiga window appear and then disappear? Do you get an error message? Any detail helps.

The log file says that Taiga successfully runs, reads its initial data files, and tries to communicate with the update server. However, the process ends after ~1 second, as if it was terminated by you or another application.

I couldn't find anything odd in process profiling events, except for [one thing](https://jspin.re/2016/05/01/adventure-time-warsaw-osx/):
`C:\Program Files\Diebold\Warsaw\core.exe`

> Warsaw is an application developed by Gas Tecnologia, subsidiary to Diebold group, and has become the industry security standard used by most of the Brazilian banks. Under the guise of protecting customers during online banking transactions, Warsaw is mandatory to be installed on personal computers which users need to access Internet Banking.

It seems quite invasive, so I wouldn't be surprised if it somehow interferes with other applications. You might want to look into that.

Otherwise, I can't think of any reason why Taiga wouldn't run properly. Might be the same issue as #769.

**Comment by zZLord** [comment]
> What do you see when you run Taiga? Does a Taiga window appear and then disappear? Do you get an error message? Any detail helps.
> 
> The log file says that Taiga successfully runs, reads its initial data files, and tries to communicate with the update server. However, the process ends after ~1 second, as if it was terminated by you or another application.
> 
> I couldn't find anything odd in process profiling events, except for [one thing](https://jspin.re/2016/05/01/adventure-time-warsaw-osx/):
> `C:\Program Files\Diebold\Warsaw\core.exe`
> 
> > Warsaw is an application developed by Gas Tecnologia, subsidiary to Diebold group, and has become the industry security standard used by most of the Brazilian banks. Under the guise of protecting customers during online banking transactions, Warsaw is mandatory to be installed on personal computers which users need to access Internet Banking.
> 
> It seems quite invasive, so I wouldn't be surprised if it somehow interferes with other applications. You might want to look into that.
> 
> Otherwise, I can't think of any reason why Taiga wouldn't run properly. Might be the same issue as #769.

It was really this Warsaw termaning Taiga, uninstalling it made Taiga come back to life.  Thank you a lot. I'll install that app again in a VM.
