### ISSUE TITLE
Plex recognition?

### ISSUE THREAD

**Issue by DFKnight** [erengy/taiga#78]
I was wondering if it's possible to support the recognition of media playing on Plex. I've noticed that it displays the media name, season and episode number in the title.

**Comment by Wopian** [comment]
:+1:

**Comment by erengy** [comment]
Do you mean Plex Media Server or Plex Home Theater? (I haven't used Plex before, I don't know how it works.) Could you attach a screenshot of the application that displays the media name in its title?

**Comment by DFKnight** [comment]
![plex-title-1](https://cloud.githubusercontent.com/assets/295134/6048453/3f557ea4-ac7e-11e4-8f7f-3aac1cd2899c.PNG)

![plex-title-2](https://cloud.githubusercontent.com/assets/295134/6048459/445979aa-ac7e-11e4-887b-c2c8f1311225.PNG)

**Comment by WarheadKillor** [comment]
The only awkward thing I see weird with Plex and Taiga is the fact that Plex pulls info from TVDB for Anime series, and mostly combines most anime into a single show.

Observe: http://thetvdb.com/?tab=series&id=102261

Even though the Monogatari series airs mostly seperate from each other in MAL, the listings here make it apart of Bakemonogatari. So certain series would be Bakemonogatari - S3 - E02, even though that is Monogatari Series: Second Season's episode 2.

**Comment by Arararararagi** [comment]
That is no longer a problem since [this](https://forums.plex.tv/index.php/topic/105054-release-myanimelistnet-metadata-agent/) exists. It anything goes wrong, you can always edit the series and search and select the correct one.
And I'd love to see this feature as well, as I do most of my anime watching through Plex.

**Comment by DFKnight** [comment]
I would still like to see this implemented in Taiga since I don't use Plex plug-ins.

**Comment by Wopian** [comment]
The chrome app also has the `Show - Season - Episode` in the title.

![](http://a.pomf.se/amftkc.png)

---

> That is no longer a problem since this exists.

There's also [this](https://forums.plex.tv/index.php/topic/137203-release-hummingbirdme-agent-for-anime/) for Hummingbird users. :)

---

>Plex pulls info from TVDB for Anime series, and mostly combines most anime into a single show.

*Only if you're still using the default scanner and agent, and not a anime specific agent.

**Comment by erengy** [comment]
Added support for Plex Web App in 26105e234c61b4f2ba7373e78de795820692ab38. Note that you need to use an actual web browser for Taiga to be able to detect it; the Chrome app won't work.

**Comment by rcdailey** [comment]
What would be nice is if I could setup Taiga to monitor my Plex library and sync watch status on MAL based on that. The thing is, I watch anime on many plex clients in my home (PC web client, Roku, Chromecast).

**Comment by DFKnight** [comment]
I agree. That would be amazing!

**Comment by Diablofan** [comment]
@rcdailey @DFKnight I agree it would be useful as I find myself in a similar position, but I think that might be a little harder to do for various reasons. Recognition would have to make a web call to the Plex server, parse the result (eg, grab the name and episode), _AND THEN_ run the rest of the recognition code.

It's doable, however, I'm not sure if @erengy would be okay with that addition because to me it seems out of scope of what Taiga would do normally. But that's just my opinion.

**Comment by erengy** [comment]
I'm planning to rewrite Taiga's current media detection code as a separate library. Not sure if it'd work out for Plex, but I imagine we could define different methods for different sources eventually.

**Comment by Renari** [comment]
@erengy I could give you access to a server and the various players that are available if you'd like.
