### ISSUE TITLE
Waterfox support

### ISSUE THREAD

**Issue by Yaakushi** [erengy/taiga#79]
I don't want to be a bother, but I just noticed that Taiga doesn't support Waterfox (or at least, I think so). Could we please get Waterfox support on a future version? ;-;

**Comment by rr-** [comment]
@erengy, what if we let people choose which windows to track?
For example like this:

![out gif](https://cloud.githubusercontent.com/assets/1045476/5991525/505250ba-a9f4-11e4-8864-1b2da7ea092a.gif)

**Comment by DFKnight** [comment]
@rr- I think that would be a great idea.

**Comment by erengy** [comment]
@rr-
I was thinking of doing the same in the early days of Taiga. It turned out there really aren't that many media players around; I've received just a few requests in the past five years. Besides, media player detection is a bit more complicated than that. Taiga needs to know the class name of a distinct window of the application (which may not be the main window, and may be invisible). Some media players have APIs, which Taiga makes use of. For browsers, Taiga needs to know the browser engine (e.g. Gecko, WebKit) as well... I'm planning to look into improving the way detection works, but I think the current solution is still better than letting the user choose their own player (not to mention that [media.xml](https://github.com/erengy/taiga/blob/master/data/media.xml) is already editable).

PS: I'm actually an obsessive user of WinSpy++. Randomly spying on windows results in rewarding moments like "so the desktop is actually a SysListView32, huh?" or "WTF is a [DavesFrameClass](http://blogs.msdn.com/b/oldnewthing/archive/2007/07/25/4036123.aspx)?".

**Comment by erengy** [comment]
Unfortunately, Waterfox doesn't expose an [MSAA](https://en.wikipedia.org/wiki/Microsoft_Active_Accessibility)/[UIA](https://en.wikipedia.org/wiki/Microsoft_UI_Automation) tree. In other words, Taiga cannot retrieve the URL of the current page or tab titles from Waterfox as it does with Chrome and Firefox. Pretty much the only other reliable solution is to write an add-on/extension for the browser, though I'm not sure if it's possible to make an add-on directly communicate with an external application such as Taiga.

**Comment by erengy** [comment]
I've recently (in 0d18b7a614b35a568495affb9ea1029757308844) added a new method to detect web browsers, which is now in testing phase. It's not possible to detect Waterfox with it either, though; and I don't think it's worth the effort to look for another way. It seems that Waterfox is going to become even less relevant, since Firefox now provides [official 64-bit builds for Windows](https://hacks.mozilla.org/2015/03/firefox-developer-edition-38-64-bits-and-more/). According to Mozilla's release schedule, that's going to hit the stable channel on May 11th.
