### ISSUE TITLE
Option to group the media player together with Taiga in the taskbar

### ISSUE THREAD

**Issue by timeleaper** [erengy/taiga#80]
Is it possible to implement this functionality? I did some googling and apparently Taiga would need to launch the media player with the same Application User Model ID as the Taiga client itself ([source](http://stackoverflow.com/a/13924807)) in order for both to be grouped together under Taiga's icon.

This feature would be nice to have because it'd tidy up the taskbar a bit, and it's more intuitive to consider the media player a part of the Taiga client's group when Taiga launches it.

**Comment by erengy** [comment]
Thanks for the link, @timeleaper. At a glance, it seems technically impossible to group Taiga with an arbitrary external process. In any case though, I think this would be an inappropriate feature to have, and not just in Taiga. Changing the default behavior of the operating system would make things less intuitive for the vast majority of users. Honestly, I don't recall seeing any other application doing this.

Taiga doesn't try to do everything. It knows its boundaries. It searches your computer for video files, but it doesn't play them as a media player would. It checks for new releases, but it leaves the downloading task to a more competent piece of software. Likewise, tidying up the taskbar shouldn't be Taiga's responsibility.

In my mind, Taiga is an application that strives to be invisible. Its main purpose is to make things easier for many, at the expense of the efforts of one. While automatically handling some tasks that would otherwise be a chore, it tries to remain unobtrusive at all times. Thus, putting it in front of the media player wouldn't be appropriate. This direction may of course change over time. But even in that case, frankly, I'd rather embed an actual media player inside Taiga than to group an external process with it.

**Comment by timeleaper** [comment]
@erengy: Thanks for your response. I can understand how it wouldn't make much sense. A more viable solution would probably be to just have it minimize to the taskbar when it starts an episode in the media player, and optionally have it come back up when the media player's process terminates or something to that effect. If nothing else, the addition of such a feature would support Taiga's vision of being "invisible" and "unobtrusive" to the user.
