### ISSUE TITLE
Can't get Taiga to select torrents?

### ISSUE THREAD

**Issue by muea405** [erengy/taiga#816]
Hello, I'm trying to use the auto-download function of Taiga but I can't get any combination of filters that actually selects the files I want. I'm trying to auto select HorribleSubs files at 1080p, but I just get the image below.

![dl](https://user-images.githubusercontent.com/24590003/63482589-6fed2980-c467-11e9-9924-c7969f6b9539.png)

I'd appreciate if someone could help me understand how the filters work? Here's my filters if you want them.

`VEFJAQUAMS4zLjGNAYgGeJy9lE1vwjAMhs/jV1iR0I7AtEk7UA7TDhx2YAJpx8o0BiKlcZcPEP9+SfkQm1Y+htihqprab57XdtJXnkrAwis2mZDKFWilgBJ9scgEmrUArjY/F0qSADI41SQz4W2InwZLysTI0owsDMdi0LrrF2ykSjlAmkoyPhNUKceS8rnlUCVJsujZZsKwp8+A2glYog5Ra8jWqrjFOEzjYmfQ6ncSY3wfR9X6LNTXTR68vZ9iXUYRzi051iFFHGJrv+ftdZ+71RFQF4UL/zunpBmGpPUr6rjOhFVKVGbexBsc2dx59MEdIv4oa++WiKhsBAQ0qiRQBiqNBjxv0Ju4S/J4mvuh5r7C+NMlQ3TmvO+GSFquKpKdOMXJtlbOX9elx2vddm/otu4mydjm+CxR6RQL2+PiTh0nE8op2W+HiPbY7a12u9m/5gJ1vlPb73+kFpPaw99uEEkpbIm+sSj7ABhNPq6b8d6/zvhlNtnce5C8MppRwrRuU2OvZ0pTXkS1Odv1Ed6X+l44ZP4CHEI/dg==`

**Comment by erengy** [comment]
Hi there. Just tried your filters out and they seem to be working:

![2019-09-06 210528](https://user-images.githubusercontent.com/1078430/64451202-5c3ef580-d0ec-11e9-9bf2-2d35563ce25c.png)

I think the ones in your screenshot are not selected because they were previously downloaded (i.e. *Settings → Library → Cache → Torrent history*). Also note that the results are limited to the contents of the RSS feed, and the filters are applied on these results at client-side rather than being used as a query.

**Comment by muea405** [comment]
Yep that was it, it was my torrent client that wasn't opening properly. Thanks!
