### ISSUE TITLE
Alternative titels broken?

### ISSUE THREAD

**Issue by athleticalex195** [erengy/taiga#831]
Trying to add the new Hero academia sesson as only Boku no Hero Academia without the 4 in alternative titel becuse Horbilesubs releases it that way "Boku no Hero Academia - x" but taiga can't find anything.  Same with fairy gone. I feel like in general the Alternative titels option is broken.

**Comment by erengy** [comment]
This is related to [anime-relations](https://github.com/erengy/anime-relations) rather than alternative titles. Relevant rules were added with https://github.com/erengy/anime-relations/commit/c2bbadda3d59b0ced32b23013ea00a85484bf1ee and https://github.com/erengy/anime-relations/commit/1483766155586f7ea1eec1b0b9a6bc18383b0fef. Use *Help → Check for updates* to get the latest relations.
