### ISSUE TITLE
Doesn't show any torrent from Anidex

### ISSUE THREAD

**Issue by Kukurinpa** [erengy/taiga#845]
Since a couple of days, it doesn't load the torrent list from Anidex. It's the only source that doesn't work. Apparently they have now added a DDoS protector, although I don't know if this is really the cause.  

I've tried it on two different PCs and the same error occurs.

![Captura](https://user-images.githubusercontent.com/25968731/71903968-891c1b80-3165-11ea-97e6-6f3bc5ba1217.PNG)

**Comment by erengy** [comment]
This is indeed because of the "DDoS protection by DDoS-GUARD". Taiga expects an RSS feed, but the server returns an HTML page with some JavaScript code designed to be run by web browsers. You can try contacting AniDex and asking them to exclude their RSS feed from DDoS protection, if possible. See also #236 and #326 for similar issues.

**Comment by Kukurinpa** [comment]
Oh, I see, I hope in a couple of days they disable the protection. 
Thanks for the answer.

**Comment by Kukurinpa** [comment]
Somehow, I've solved the problem. I set the RSS feed to `http://anidex.moe/rss/?cat=1`  and modified    _Settings > Advanced > Torrents / Use magnet links if avaliable._  :  'false' to 'true' and i can download from anidex as before.

**Comment by erengy** [comment]
That could work, but note that you changed the domain from `anidex.info` to `anidex.moe`. I don't know if the latter is the same. Visiting it on a web browser shows a security warning.
