### ISSUE TITLE
Kitsu Update Fail

### ISSUE THREAD

**Issue by P4RI4H** [erengy/taiga#848]
Keep getting 'Update Failed: Kitsu returned an error: "Invalid Token: "' when trying to update my list. Trying to force sync gives same error.

Last synced Jan 6th and no changes have been made. They stay in History under "Queued for update." Just added my anime:

Sarazanmai episode 1
Boku no Hero Academia 4 episode 13

Windows 10

**Comment by wopian** [comment]
The access token for Taiga to login to your account expired and [Taiga] failed to refresh it, so it's attempting to login with the expired token.

**Comment by erengy** [comment]
> Update Failed: Kitsu returned an error: "Invalid Token: "

Does the error message end there, or is there any information afterwards?

Restarting Taiga makes Kitsu return a new access token, so it normally should fix this issue. Tokens do not persist between sessions, so it's not possible to have an expired token after a restart. Just make sure you're actually restarting Taiga and not closing it to tray (*Settings → Application → General → System tray use*).

You can try downloading the [latest build](https://taiga.moe/latest.html) in case this is somehow related to #722.

Otherwise double check if your credentials at *Settings → Services → Kitsu* are up to date.

**Comment by P4RI4H** [comment]
Credentials are good, that was the first thing I tried. Also, yes, the message ends there. I saw it looks like there was a spot for more information. It's been on for a long time because I keep this PC on 24/7 as a media PC. I'll try the restarting Taiga when I'm finished work and update this comment.

**Comment by erengy** [comment]
See #706 for the new error. Clearing the update queue at History page should work.

**Comment by P4RI4H** [comment]
> See #706 for the new error. Clearing the update queue at History page should work.

That seems to have fixed it.
