### ISSUE TITLE
Issue detecting Tsugumomo S2 alternative title

### ISSUE THREAD

**Issue by jakemoritz** [erengy/taiga#863]
I am having an issue with the torrent search feature properly detecting an anime using the alternative title feature. The show's proper title from AniList is "Tsugu Tsugumomo". HorribleSubs' listings for this use the title "Tsugumomo S2". I have that text in the "Alternative titles" section of the show. I also have the checkbox checked for using this title for torrent searches. Despite this, the torrent search is discarding results due to the default "Discard and deactivate not-in-list anime" filter. Can someone look into what's going on here?

EDIT: I did try running Taiga in debug mode but I couldn't see any output about the filters in the log.

**Comment by erengy** [comment]
Adding `Tsugumomo S2` as an alternative title works for me with the default filters and AniList. HorribleSubs' releases are correctly identified and selected.

Regardless of selection, if you're still seeing the anime title as "Tsugumomo S2" with a gray icon (unknown), then it's a recognition issue. You should double check the alternative titles for the series (and other relevant anime in your list, in case there's a conflict).

If you're seeing them as "Tsugu Tsugumomo" with a green icon (currently airing), then the torrent was identified. It could be discarded either by some filter or because it was previously downloaded. When you run Taiga in debug mode, the Description column of the Torrents page displays why a torrent was selected or discarded.

**Comment by jakemoritz** [comment]
![image](https://user-images.githubusercontent.com/5996706/79169264-f6b99280-7db9-11ea-8b96-525f2587fff6.png)

Here is what I'm seeing in debug mode. `Tsugu Tsugumomo` by `Erai-raws` is green and thus is identified and matched. `Tsugumomo S2` by `HorribleSubs` is gray.

**Comment by erengy** [comment]
Looks like you kind of have both the issues above.

"Archived" means the torrent was previously downloaded or manually discarded, so it will always be discarded regardless of your filters. You can reset the torrent history via *Settings → Library → Cache* (will be moved to *Settings → Advanced* in the next update).

That said, the torrent is still unidentified:

> You should double check the alternative titles for the series (and other relevant anime in your list, in case there's a conflict).

**Comment by jakemoritz** [comment]
It has these alternative titles: `Tsugumomo2, 継つぐもも, Tsugumomo S2`. The last one in the list is the title I manually added.

**Comment by ramma1** [comment]
I'm having the same issue for Fruits Basket and Kaguya-sama. How did you manually add alternative title?

**Comment by jakemoritz** [comment]
> 
> 
> I'm having the same issue for Fruits Basket and Kaguya-sama. How did you manually add alternative title?

I solved this for Fruits Basket by adding the alternative title `Fruits Basket S2 (2019)`. You need to double click on an anime in your list and in the "My list and settings" tab you see the option toward the bottom.

**Comment by ramma1** [comment]
Thank you very much.

**Comment by erengy** [comment]
@jakemoritz Could you try removing the alternative title and restarting Taiga?

I just tried installing Taiga to a sandbox VM and the torrents in question were identified out of the box (likely because AniList's `Tsugumomo2` is the same as `Tsugumomo S2` after Taiga's title normalization process). So, adding an alternative title doesn't seem to be necessary in this case.

You could also open `Taiga\data\settings.xml` and search for `Tsugumomo`, to check if there are multiple lines such as `<item id="108266" titles="Tsugumomo S2" />`.

**Comment by jakemoritz** [comment]
@erengy I removed the alternative title and now the torrent search is matching HorribleSubs' release for Tsugumomo S2 to the original Tsugumomo release.

![image](https://user-images.githubusercontent.com/5996706/79228482-80f00e00-7e2f-11ea-9a2d-bdcacbc8a4ae.png)

I reset all the Taiga settings and the same thing happened.

**Comment by erengy** [comment]
> now the torrent search is matching HorribleSubs' release for Tsugumomo S2 to the original Tsugumomo release.

Looks like you added "Tsugumomo S2" as an alternative title to the first season of the series too.

**Comment by jakemoritz** [comment]
Wow you're right. I don't know when or why I added an alternative to the original season. Removed it and everything is fixed. Thanks for the help.
