### ISSUE TITLE
Switched icons

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#882]
This is something I noticed before but confirmed when I saw what the next/previous season icons were meant to be.
For some reason not all the icons are in the right places.
![image](https://user-images.githubusercontent.com/13546823/83360892-aa7fdd00-a37c-11ea-80e9-6a94a40b5ef2.png)
![image](https://user-images.githubusercontent.com/13546823/83360898-b2d81800-a37c-11ea-815e-6f47c177d0e3.png)

**Comment by erengy** [comment]
This is likely because you haven't updated the default theme. Two new icons were added in 9183d5d1fc3efa4f03f895df1009b471c9191fc5.

You can simply copy the current `data\theme\Default\` directory over yours (which is what the installer does), or copy only the new icons and modify `Theme.xml` accordingly.

**Comment by paulo27ms** [comment]
Indeed. Thank you.
