### ISSUE TITLE
MAL returns empty string instead of Unknown for anime type

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#885]
I saw https://github.com/erengy/taiga/commit/ed5141eab75cc8ab2d5476cd84899493e7e3a00c and then looked at the code and it seems like entries without a type should be Unknown but currently with MAL they are just empty strings. Figured this might cause issues at some point.

![image](https://user-images.githubusercontent.com/13546823/83385418-1f84fe00-a3e1-11ea-9ae3-6ddf4f95fc83.png)

**Comment by erengy** [comment]
It's related to how Taiga displays the types:

https://github.com/erengy/taiga/blob/ed5141eab75cc8ab2d5476cd84899493e7e3a00c/src/ui/translate/anime.cpp#L59-L69

...rather than what MAL returns:

https://github.com/erengy/taiga/blob/ed5141eab75cc8ab2d5476cd84899493e7e3a00c/src/sync/myanimelist_util.cpp#L113-L134

I actually noticed this yesterday while trying to debug another issue, will commit today.
