### ISSUE TITLE
Select Matched/Prefer Items showing torrent that should be filtered out

### ISSUE THREAD

**Issue by Sileniful** [erengy/taiga#897]
noticed that when a subgroup is set to = matched group and select or prefer those torrents the filter doesn't match it properly 
eg
i use horrible subs 99% of the time and i never tried FFA but it still shows up with this

![image](https://user-images.githubusercontent.com/1914729/85213807-bc451680-b363-11ea-870c-f82129f2174f.png)

only time this works properly is when you set filter to discard everything that is not HorribleSubs

**Comment by paulo27ms** [comment]
Your issue is that you're misunderstanding how preference filters work.
If you have your general filters picking to select all anime in the currently watching list, every torrent will be picked, if you set a preference filter for HS then what's going to happen is if an episode has a torrent for a HS and a torrent for ER, it'll pick HS and ignore ER, in the case of Great Pretender, there's no HS torrent for it so your general filters are gonna pick everything they see for Great Pretender.
Again, note that the preference filter only works if you have HS and ER at the same time. Imagine HS is late for a day, during that day your filters will pick every torrent for an anime because HS isn't there to be the preference.

**Comment by Sileniful** [comment]
yes i am misunderstanding how preference filters work but honestly some tact would not hurt, this wouldn't happen if there was some information about how filters work aside from looking in code or trying to understand it by trial and error :)

**Comment by paulo27ms** [comment]
As erengy said in the other thread, the [support page](https://taiga.moe/#support) does offer that information.

> Discard and Select actions work the way you'd expect, whereas Prefer is a bit more complicated: If it's a general filter, torrents that don't match the filter are discarded. If it's a limited filter, torrents that match the filter are selected, and torrents that don't match the filter are discarded.

As I mentioned, in general filters it'll compare only to existing torrents, in the limited filters it'll compare for every torrent and only select them if they meet the criteria.

**Comment by Sileniful** [comment]
thank you
