### ISSUE TITLE
[Suggestion/Small Feature] Add a "TV Short Anime Type

### ISSUE THREAD

**Issue by IamMeWasTaken** [erengy/taiga#914]
From time to time I want to watch half an episode but Taiga only shows the way it was aired not what **type** of episode it is.

I would for Taiga to also recognize if it is a Short TV format show (so 10 to 14 minutes) instead of everything just being labeled TV.

With kind regards
IamMe

**Comment by paulo27ms** [comment]
This isn't something Taiga is going to do because it's categorization that's entirely up to the services Taiga uses to sync your list.

The better suggestion here is to expand UI options and let you add columns with more information as well as display more information in an anime's information page. Even MAL now includes episode length on their API, it's just a matter of Taiga adapting its UI to give you the option to see all the information you want.
Such UI reworks are something that's planned I believe but probably still far off.

**Comment by IamMeWasTaken** [comment]
That would be even better. I just know that anilist, which I use to sync,
shows Short TV anime so I was bumed when Taiga didnt.

**Comment by erengy** [comment]
Not exactly what you asked, but 1d9b9b49848173bdcb7230320dc75d762983e594 allows filtering Anime List by episode duration (e.g. `duration:<15`). Perhaps a column (#150) can be added too in the future.

**Comment by IamMeWasTaken** [comment]
That would be perfect!  But how do I use that in client?

**Comment by erengy** [comment]
It's an [undocumented feature](https://github.com/erengy/taiga/blob/1d9b9b49848173bdcb7230320dc75d762983e594/src/media/anime_filter.cpp#L66-L89) right now, but you just type it in the search bar:

![duration-filter](https://user-images.githubusercontent.com/1078430/96119758-1dd25780-0ef6-11eb-8385-66b8e68a7d22.png)

It's going to be available in the next release. If you can't wait, you may install [1.4.0-beta.2](https://github.com/erengy/taiga/releases/tag/v1.4.0-beta.2) and then copy the [latest build](https://taiga.moe/latest.html) over it.

**Comment by paulo27ms** [comment]
Can you filter out entries with no episode_length (not sure if you consider it null or how it's handled)?

**Comment by erengy** [comment]
You can combine filters. For instance, `duration:>0 duration:<15` will exclude series with unknown episode length.

As far as I'm aware, there's no difference between `null` and `0` in the APIs that Taiga use. The lowest valid value is 1 minute.
