### ISSUE TITLE
Adding the year/airdate breaks recognition?

### ISSUE THREAD

**Issue by Andy2244** [erengy/taiga#917]
I just noticed that simply adding the year/airdate in "()" breaks recognition?

So this wont be detected:
`A Place Further Than the Universe (2017) - 08 - [720p][www][HorribleSubs].mkv`
while this will:
`A Place Further Than the Universe - 08 - [720p][www][HorribleSubs].mkv`

Usually having the date helps finding the correct series/season, so i'm wondering why this common naming scheme actually breaks taiga?

Is it also not recommend to have the year in the parent folder, like the common Kodi naming?
| `A Place Further Than the Universe (2017) \`
|---`A Place Further Than the Universe - 08 - [720p][www][HorribleSubs].mkv`

**Comment by Abchrisabc** [comment]
For recognition a separate library is used which is also made by erengy: [Anitomy](https://github.com/erengy/anitomy). As far as I can see, it only checks the File names for recognition, so adding the year in a parent folder for recognition seems not to be a problem.

Looking at the file name you noted down, I do think it will recognize 'www' as the fansub group.

**Comment by erengy** [comment]
This is intentional, because some series are disambiguated with the year (e.g. "Kanon (2006)", "Fullmetal Alchemist (2009)", "Hunter x Hunter (2011)"). In your case, adding "A Place Further Than the Universe (2017)" as an alternative title should work.

Taiga does look up the parent directory's name, but only when the filename isn't enough for identification.

**Comment by Andy2244** [comment]
ok thanks for the explanation
