### ISSUE TITLE
"parent directory" recognition inconsistent?

### ISSUE THREAD

**Issue by Andy2244** [erengy/taiga#918]
I constructed the example given in the help.

Created the file and added the series as "watching", also in the settings "Lookup parent directories" is true.
`X:\Anime\Toradora!\01 - Tiger and Dragon.mkv`

If i manually play this file via a external player it is not recognized and taiga ask me to manually select the show.
Yet the `Now Playing` tab lists under `Continue Watching:` `Toradora! #1` and if i click on the link the file starts and is now listed correctly as "playing".

So whats going on here?
Why is the episode somehow recognized via "file scan", but not if i manually play the file?
Is taiga not able to check the parent folder from the media-player location or cross-check with the local file database?

**Comment by wopian** [comment]
`Lookup parent directories` only changes how Taiga's directory scanning works, due to limitations on how manually played anime can be detected.

>If I manually play this file via a external player it is not recognized and taiga ask me to manually select the show.

Taiga uses the application title (with https://github.com/erengy/anisthesia) to match the anime/episode you're watching when a video is opened outside of Taiga.

Your video player is likely setting the title as `01 - Tiger and Dragon.mkv` which taiga cannot recognise as an anime title. It cannot retrieve the file path or parent directory from this information, so there is no way it would be able to cross-check with the directory scan results.

**Comment by Andy2244** [comment]
> Taiga uses the application title (from the UIA tree with https://github.com/erengy/anisthesia) to match the anime/episode you're watching when a video is opened outside of Taiga.

> Your video player is likely setting the title as `01 - Tiger and Dragon.mkv` which taiga cannot recognise as an anime title.

Ahh thanks this explains it, was assuming there is some extra cross-referencing between the play detection and local scanned DB.
Checking the code i quickly found this and all i needed to-do was just change the titlebar info in MPC to "full path".

```
	strategies:
		open_files
		# Depends on: Options -> Player -> Title bar
		window_title:
			^Media Player Classic|(.+) - Media Player Classic
```
