### ISSUE TITLE
Now playing - vertical scrollbar or text wrapping?

### ISSUE THREAD

**Issue by respock** [erengy/taiga#93]
Hello
I am using Taiga on a daily basis, and it is really a great program, but recently I spotted a minor issue.
In "Now playing" tab if text exceeds the height of the window, it's no longer visible unless you resize the window.
It is especially noticeable now, as many series finished airing.
So maybe it is a good idea to move "recently finished airing" to new column next to "recently watched" and/or create vertical scrollbar in this section?

Anyway, thanks for this little gem, it really helps get things organized.

**Comment by erengy** [comment]
Hi there @respock,

Unfortunately, this is something I'm unable to fix due to technical difficulties involved. For a previous discussion of the same issue, see #65.

I can actually do the following, but I'm not sure if it looks any better, or just more complicated:

![now-playing](https://cloud.githubusercontent.com/assets/1078430/6991899/869af2fa-dab7-11e4-81bc-98562da17a15.png)

**Comment by respock** [comment]
I did not notice that the issue was already reported. 
As for the proposed solution I personally find it ad hoc, but still better than what it is now (i love the hyperlinks though - it should absolutely be implemented).

Anyway, thanks for your quick reply and support!
