### ISSUE TITLE
Support for Debrid?

### ISSUE THREAD

**Issue by unkn0wn234** [erengy/taiga#956]
Debrid services hold up a lot of torrents on their servers, a feature to view their torrents, and/or send torrents to a respective debrid service would be dope. Maybe even streaming back from them

**Comment by erengy** [comment]
Sorry, I'm not familiar with Debrid services. But if they work similarly to seedboxes, Taiga isn't really designed to be used that way. See #461 for a previous discussion.

**Comment by mathu204** [comment]
> Sorry, I'm not familiar with Debrid services. But if they work similarly to seedboxes, Taiga isn't really designed to be used that way. See #461 for a previous discussion.

Um I’m not completely sure what a seedbox is but a debrid service is a service that gives u access to premium torrents and hosters. The main use with Taiga is that if taiga supported debrid services u could access a boat load more torrents that are not available either publicly, or have long since stopped being seeded. For the latter, when a torrent is saved on a debrid service it stays cached on their servers indefinitely meaning if the original torrent has no S/L u can still download the torrent fast through Debrid. 

![46FBD026-E670-4C70-99D4-6826B4F92B5D](https://user-images.githubusercontent.com/52363082/104826999-71bb4800-5827-11eb-9d55-221c1d1c27b9.png)

Above is an image of a link search for an anime episode using debrids. Also if possible making it so Taiga could connect to a debrid service and play files from it (bc on top of the premium Torrents, they give u storage space to download torrents to as well, in their cloud) it would be dope, I tried using FTP or WebDAV to mount my cloud as a drive on my computer but taiga seemed to crash every time trying to play it hence why I made this request. But I also don’t think the crashing is taigas fault as I can’t play any files through the ftp or webdav af the moment, so I’ve raised an issue with them as well. 

Regarding this second one it may fall into the “not how taiga is meant to be used” in which case I understand. 

However the first part, even if it means I won’t be able to use Taiga, is still a viable and good feature to add in my opinion as it opens up to let you access much more torrents. I do think that they kind of go hand in hand tho if u can do the first (search for torrents from debrid servers) the second part (play from or access debrid clouds to play torrents from it) should come with fairly easily imo, but I also don’t code for shit so I don’t know how hard it is. Thank you for responding to me though and I hope you consider it.

**Comment by Accelyte** [comment]
If I understand it correctly, Taiga's torrent downloader is essentially

- pull the torrent RSS feed
- download specified torrent file
- open file locally

and is not designed to do anything beyond that. How your desktop handles opening torrent files is down to you, so you could (as #461 pointed out) change the behaviour of how torrents are handled locally on your desktop, and have them automatically uploaded to your Debris service instead.
