### ISSUE TITLE
Scanning Available Episodes (Folder length problem)

### ISSUE THREAD

**Issue by Hashi95** [erengy/taiga#966]
Taiga seems to have a problem with folder name length

It could not find the folder when it was named "Land of the Lustrous (Houseki no Kuni) (2017) [1080p] [kuchikirukia] [v2]"
It can find it when i changed it to "Land of the Lustrous (Houseki no Kuni) (2017"

Normally I would say this is not a big deal but for animes like "Suppose a Kid from the Last Dungeon Boonies moved to a starter town?" I cannot easily change the length of the folder name without also changing the actual title of the anime. 

For this anime I had to manually set the folder location while also clicking on open folder location in order to play the next episode. 

Obviously not a huge issue, but a small nuisance nonetheless.

**Comment by erengy** [comment]
This might be the same issue as #917, rather than something related to the length of the folder name.

Windows has a [limit](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) of 260 characters for the entire path. Taiga uses [extended-length paths](https://github.com/erengy/taiga/blob/fa3b4f782eca1e77d60d93973a22ad659194ff12/src/base/file.cpp#L200-L214) though, so this shouldn't be a problem.
