### ISSUE TITLE
Taiga detects non-anime videos

### ISSUE THREAD

**Issue by nolemretaWxd** [erengy/taiga#985]
![image](https://user-images.githubusercontent.com/31414969/111210901-1a8ae700-85ce-11eb-91df-65f62d155189.png)

In my opinion Youtube should be removed as it's near impossible to anime to appear there because of copyright

**Comment by wopian** [comment]
There are several big studios or licensees that upload their old anime back catalogue to their official YouTube channel.

**Comment by darkash** [comment]
> In my opinion Youtube should be removed as it's near impossible to anime to appear there because of copyright

You're wrong, there are now legal anime channel on Youtube

such example is: [url="https://www.youtube.com/channel/UCGbshtvS9t-8CW11W7TooQg"]Muse Asia[/url]

Also some old anime still can be found on Youtube which even had their fansub watermark. Just because you can't find any and don't have access to the said channel above means it's not there, in fact there's abundant of them if you're using correct term or using localized language which usually goes undetected

**Comment by MagikarpLaCarpe** [comment]
You are wrong. There is a thousand of multiples series avaible on youtube trough legal channel.
